### ISSUE TITLE
Cisco ASR9010 sampling rate not being recognised

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#101]
@phaag I guess we have more one router which sampling rate it's not beign recognised. I'm attaching pcap data from a router which is configured with a random 1:10000 sampling ratio. Thanks in advance!

[ASR9010.zip](https://github.com/phaag/nfdump/files/1769625/ASR9010.zip)

**Comment by phaag** [comment]
Thx. I will check it!

**Comment by phaag** [comment]
Your exporters do export just the samlper ID - Identifier shown in **show flow-sampler**, but no 
FLOW_SAMPLER_MODE - tag 49 and no FLOW_SAMPLER_RANDOM_INTERVAL - tag 50.

Therefore the sampling information in the netflow export is not complete and nfdump can not estimate packets and bytes. Maybe a configuration issue, or a CISCO bug?

**Comment by phaag** [comment]
@gabrielmocan Any news here?

**Comment by phaag** [comment]
closed meanwhile as no update. Please reopen on request
