### ISSUE TITLE
nfsen patch failed

### ISSUE THREAD

**Issue by guilhermefigueiredo** [phaag/nfdump#107]
Hi phaag!

i'm trying to apply extra/nfsen patches on the nfsen-1.3.8 but it is showing some errors

root@nfsen:/usr/local/nfsen# patch -p0 --dry-run < /root/install/nfdump/extra/nfsen/nfsen-trunk-stats-influxdb.patch 
checking file bin/nfsend
Hunk #1 succeeded at 62 with fuzz 2 (offset 7 lines).
Hunk #2 FAILED at 333.
Hunk #3 succeeded at 471 with fuzz 2 (offset 27 lines).
Hunk #4 succeeded at 807 with fuzz 2 (offset 47 lines).
1 out of 4 hunks FAILED
checking file etc/backend.conf-dist
Hunk #1 FAILED at 101.
1 out of 1 hunk FAILED
root@fastnetmon:/usr/local/nfsen# patch -p0 --dry-run < /root/install/nfdump/extra/nfsen/nfsen-1.6-stats-influxdb.patch 
checking file bin/nfsend
Hunk #1 succeeded at 62 with fuzz 2 (offset -4 lines).
Hunk #2 succeeded at 450 (offset 22 lines).
Hunk #3 succeeded at 472 (offset 22 lines).
Hunk #4 succeeded at 807 (offset 47 lines).
checking file libexec/NfConf.pm
Hunk #1 succeeded at 228 with fuzz 2 (offset 155 lines).
Hunk #2 FAILED at 140.
1 out of 2 hunks FAILED
root@fastnetmon:/usr/local/nfsen# 

Can u help ?

**Comment by exit2escritical** [comment]
I have the same problem :(
Any update?

**Comment by phaag** [comment]
Sorry for being late. 
This patch is a third party patch from Luca - https://github.com/lucadistefano. I just added this patch for convenience but can not maintain it
