### ISSUE TITLE
nfdump-1.6.17

### ISSUE THREAD

**Issue by alan-boey** [phaag/nfdump#110]
Hi,
I seem to not able to compile the latest nfdump-1.6.17:

root@orion:/usr/local/src/nfdump-1.6.17# ./autogen.sh
autogen.sh: could not find `autoreconf'. `autoreconf' is required to run autogen.sh.
root@orion:/usr/local/src/nfdump-1.6.17# ./configure.ac
./configure.ac: line 4: syntax error near unexpected token `2.59'
./configure.ac: line 4: `AC_PREREQ(2.59)'

Running Debian wheezy

**Comment by xtaran** [comment]
Have you installed the [package autoconf](https://packages.debian.org/wheezy/autoconf) which contains the missing `autoreconf`mentioned in the error message?

**Comment by alan-boey** [comment]
Hi @xtaran ,
I have tried install the package but it's forcing to use aclocal which I do not know what it is:
nfdump-1.6.17# ./autogen.sh
autogen.sh: reconfigure with autoreconf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --force
aclocal: couldn't open directory 'm4': No such file or directory
autoreconf: aclocal failed with exit status: 1
autogen.sh: autoreconf has failed (1), let's do it manually
autogen.sh: configure nfdump-1.6.17
aclocal: couldn't open directory 'm4': No such file or directory

**Comment by xtaran** [comment]
Can confirm that when trying to build from git HEAD on Debian 7 Wheezy, but not on Debian 9 Stretch.

Seems as if the older `autoreconf` is more picky about a non-existent `m4` directory while the newer `autoreconf` just issues a warning and continues:

```
nfdump → ./autogen.sh
autogen.sh: reconfigure with autoreconf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --force 
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: running: /usr/bin/autoconf --include=m4 --force
autoreconf: running: /usr/bin/autoheader --include=m4 --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:12: installing './compile'
configure.ac:12: installing './config.guess'
configure.ac:12: installing './config.sub'
configure.ac:10: installing './install-sh'
configure.ac:10: installing './missing'
Makefile.am: installing './INSTALL'
bin/Makefile.am: installing './depcomp'
configure.ac: installing './ylwrap'
parallel-tests: installing './test-driver'
autoreconf: Leaving directory `.'
autogen.sh: for the next step, run './configure' [or './configure --help' to check available options]
```

Interestingly, both, Debian 7 Wheezy and Debian 9 Stretch, have the same upstream autoconf version (2.69), just different Debian package revisions (2.69-1 vs 2.69-10), so the difference in behaviour seen above seems to be something that Debian decided to fix in their packages at some point between Debian 7 and 9.

I'm though not sure what's needed to make nfdump work properly with the vanilla autoconf/autoreconf without the Debian fixes.

**Comment by phaag** [comment]
Create an empty directory
mkdir m4

**Comment by alan-boey** [comment]
Hi,
Solution was to create M4 directory, thanks @xtaran.
I had to install the following packages as well:
pkg-config
flex
bison
