### ISSUE TITLE
sfcapd unknown record type

### ISSUE THREAD

**Issue by hamshiva** [phaag/nfdump#123]
Hi,

I'm trying to use sfcapd with the last stable version 1.6.17 and I do end up with some very strange result when I'm trying to read the nfcapd files with nfdump.

```
# nfdump -r nfcapd.201806121625 
Date first seen          Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
2018-06-12 16:26:42.580     0.000 TCP      xxx.xxx.31.11:443   ->    xxx.xxx.191.20:44911    10000   13.6 M     1
Skip unknown record type 1209

Skip unknown record type 0

Skip unknown record type 0

Skip unknown record type 0

...

Summary: total flows: 1, total bytes: 13580000, total packets: 10000, avg bps: 0, avg pps: 0, avg bpp: 0
Time window: 2018-06-12 16:26:42 - 2018-06-12 16:29:59
Total flows processed: 1, Blocks skipped: 0, Bytes read: 408372
Sys: 0.012s flows/second: 83.3       Wall: 0.050s flows/second: 19.7      
```

Any idea what is going on there ?
Looks like sfcapd is not storing data correctly...

**Comment by phaag** [comment]
could you please send me a pcap of the sfcapd trafffic, worth a few minutes. Actually type 0 records are not defined.

**Comment by hamshiva** [comment]
Well I just ran the same sfcapd version recompiled with -O0 and I do not have this issue any more.. There is something very weird about this. Seems that #121 is comes from the same issue.

Compilation was done in an LXD container. It might be the source of my troubles ...

**Comment by hamshiva** [comment]
Is there any way I can send you this pcap file privately ?

**Comment by phaag** [comment]
Sure! - check the AUTHORS file.

**Comment by phaag** [comment]
This should be fixed, otherwise please reopen
