### ISSUE TITLE
Support for replaying Ipfix file formatted files - RFC 5655

### ISSUE THREAD

**Issue by r4ravi2008** [phaag/nfdump#124]
Hi, 

1. It seems like nfcapd stores files in a proprietary format, where can I find the spec for the same?
2. Is there any plan to support storing and replaying ipfix messages in this format: https://tools.ietf.org/html/rfc5655

**Comment by phaag** [comment]
The format is basically explained in nffile.h.
I plan changes in the file format - however I am not sure if the ietf format will be supported.

**Comment by r4ravi2008** [comment]
Just as an FYI, wireshark supports RFC 5655 as well

**Comment by phaag** [comment]
IPFIX files are not going to be supported for now.
