### ISSUE TITLE
VMware-based flows not being accepted

### ISSUE THREAD

**Issue by philhagen** [phaag/nfdump#126]
We're receiving IPFIX from a VSphere infrastructure, confirmed nothing is being firewalled, etc.  However, nfcapd consistently says there are `Flows: 0` for the configured ident...  The other active exporter is fine - you can see in the logs below that the `172.16.1.20` exporter is handled.  However, there is no corresponding record for the `192.168.103.6` exporter, despite there being verified traffic from that host.

The VMware exporter is IP `192.168.103.6`, associated to ident `base-inf`.  I have a pcap I can send containing both templates and flow records.

Command line:
`/usr/bin/nfcapd -D -p 9995 -T all -u netflow -g netflow -4 -S 1 -w /var/run/nfcapd/nfcapd.pid -z -n base-rtr 172.16.5.1 /logStorage/flows/base-rtr -n base-fw 172.16.1.20 /logStorage/flows/base-fw -n base-inf 192.168.103.6 /logStorage/flows/base-inf`

Logs:
```<30>2018-08-01T18:12:53.940480+00:00 base-elk nfcapd[1011]:Startup.
<27>2018-08-01T18:12:53.940685+00:00 base-elk nfcapd[1011]:Init IPFIX: Max number of IPFIX tags: 65
<30>2018-08-01T18:13:07.345202+00:00 base-elk nfcapd[1011]:Process_v9: New exporter: SysID: 1, Domain: 0, IP: 172.16.1.20
<30>2018-08-01T18:13:46.906072+00:00 base-elk nfcapd[1011]:Process_v9: [0] Add template 1024
<30>2018-08-01T18:13:46.906531+00:00 base-elk nfcapd[1011]:Process_v9: [0] Add template 1025
<30>2018-08-01T18:13:46.906808+00:00 base-elk nfcapd[1011]:Process_v9: [0] Add template 2048
<30>2018-08-01T18:13:46.906857+00:00 base-elk nfcapd[1011]: Process_v9: [0] Add template 2049
<30>2018-08-01T18:15:10.940395+00:00 base-elk nfcapd[1011]: Ident: 'base-rtr' Flows: 0, Packets: 0, Bytes: 0, Sequence Errors: 0, Bad Packets: 0
<30>2018-08-01T18:15:10.941674+00:00 base-elk nfcapd[1011]: Ident: 'base-fw' Flows: 984, Packets: 3004, Bytes: 718101, Sequence Errors: 7, Bad Packets: 0
<30>2018-08-01T18:15:10.942275+00:00 base-elk nfcapd[1011]: Ident: 'base-inf' Flows: 0, Packets: 0, Bytes: 0, Sequence Errors: 0, Bad Packets: 0
<30>2018-08-01T18:15:10.943286+00:00 base-elk nfcapd[1011]:Total ignored packets: 0```

**Comment by philhagen** [comment]
BTW, I can provide a pcap of these exports if that would help.

**Comment by philhagen** [comment]
I'm still at a loss on this one - been trying to find a solution for quite some time.  There are no options on the vSphere instance - just enable and specify collector IP/port.

**Comment by philhagen** [comment]
I'm curious if this issue with logstash's IPFIX codec may be similarly related: https://github.com/logstash-plugins/logstash-codec-netflow/issues/62

**Comment by phaag** [comment]
Sure! - feel free to send my the pcap. I'll check

**Comment by philhagen** [comment]
I can't post the pcaps publicly - could you send me an email I can reply to?  Could not find a working one for you in the Sourceforge archives.  I'm phil(a)lewestech(d)com.  Thanks!!

**Comment by phaag** [comment]
Closed for now.
