### ISSUE TITLE
NetFlow v9 type 46 and type 47 missing

### ISSUE THREAD

**Issue by psafarik** [phaag/nfdump#127]
Hello,

your nfdump package is very great. Are you goint to implement NetFlow v9 type 46 and type 47 ?

type 46 - MPLS_TOP_LABEL_TYPE
type 47 - MPLS_TOP_LABEL_IP_ADDR

Mainly the type 47 is quite useful.

Thanks

Petr

**Comment by phaag** [comment]
Petr - Can you provide me a a few minutes of trafic (pcap) sending to pcapd? You'll find my email in the AUTHORS file.

Thx

**Comment by phaag** [comment]
Any chance of getting a pcap?

**Comment by psafarik** [comment]
Hi, see the sample.

Petr

**Comment by phaag** [comment]
Where is the sample?

**Comment by psafarik** [comment]
Hi,

I have already sent the sample in March. See the sample in the attachment.

Petr

**Comment by phaag** [comment]
No sample available.
