### ISSUE TITLE
List what's required to build in readme.md

### ISSUE THREAD

**Issue by mattie47** [phaag/nfdump#129]
Hi,

I spent some time trying to figure out how to build this, and it would be useful if there was somewhere in the readme doc which listed all the required packages.

Below is a rather bad Dockerfile (It builds, but I'm not actually using it) which I used to doublecheck required packages:

```
Dockerfile 
#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:latest

#Expose sflow port
EXPOSE 6343/udp


# Install.
RUN apt-get update && apt-get install -y \
  wget \
  unzip \
  man \
  apt-utils \
  dialog \
  pkg-config \
  rrdtool \
  librrd-dev \
  libtool \
  autoconf \
  autogen \
  bison \
  byacc \
  flex \
  libbz2-dev \
 && rm -rf /var/lib/apt/lists/*

RUN cd /usr/src \
  && wget https://github.com/phaag/nfdump/archive/v1.6.17.zip \
  && unzip v1.6.17.zip \
  && cd nfdump-1.6.17\
  && mkdir m4 \
  && ./autogen.sh \
  && ./configure --enable-nfprofile --enable-sflow \
  && make \
  && make install

RUN ldconfig

# Add files.
#ADD root/.bashrc /root/.bashrc
#ADD root/.gitconfig /root/.gitconfig
#ADD root/.scripts /root/.scripts

# Set environment variables.
#ENV HOME /root

# Define working directory.
WORKDIR /usr/src

# Define default command.
CMD ["bash"]

```

I thought perhaps listing the packages I used to get it working here might help someone else....

Thanks,

Matt

**Comment by phaag** [comment]
I can add your comments regarding docker file into the extra directory, as it covers a more special case not applicable to all *nix OSes. I can add a comment in the readme file refering to that.
If so, would it like to add more text, or should I take, what you posted above?

Many thanks for your input
