### ISSUE TITLE
Skip unknown record type 10 (error after moving files to new server)

### ISSUE THREAD

**Issue by anthonypy** [phaag/nfdump#133]
Hi all, 

after moving alot of collected nfcapd files to a new collector server. The following error occurs when executing the nfdump -R command

_Skip unknown record type 10_

Could it be the files were created with a different version of ncapd on the old server and now it can't be opened on the new one? Unfortunately the old server is decommissioned. Is there a way to check witch version was used?

thnx

**Comment by phaag** [comment]
It looks like the new server uses an older version of nfdump, as the old server. Please make sure to have at lease the same version or newer installed. Type 10 is common for a long time already, so you must have a very old version on the new server.
