### ISSUE TITLE
Print ERROR messages to stderr

### ISSUE THREAD

**Issue by philhagen** [phaag/nfdump#135]
Currently, a number of error messages are still printed to stdout.  This makes command pipes and scripting more challenging.

(I have a PR inbound for this)

**Comment by phaag** [comment]
I check your patch and fixed those which should be reported to stderr/syslog in normal operation mode. I  left those which are used for debugging purpose only, as this could mess up the order of correct printing, when the output is redirected to a file.
Thanks for the reporting.
