### ISSUE TITLE
Exporter_ip is being changed, when the repeater (-R) option is used

### ISSUE THREAD

**Issue by indirakas** [phaag/nfdump#142]
We have noticed that the exporter_ip is being rewritten by the collector, when it further replicates the packet to the remote repeater. It sets it up to its own IP address, instead of keeping the router IP.
Is there an option that can change this behavior?

**Comment by phaag** [comment]
exporter_ip is by implementation not a field from the router but the IP Address of the connecting stream. Therefore when replicating a stream, the replicator IP is inserted. A solution could be IP spoofing when resending the packet. I check, if this can be added as an option to be enabled with a command line switch.

**Comment by phaag** [comment]
If you need the original IP, I would recommend to use samplicator, which can be put bevor nfcapd.
samplicator splits the UDP stream in many different output stream and allows to keep the sending IP. For security reason nfcapd does not run as root, which would be required otherwise.
