### ISSUE TITLE
nfcapd -y option is unknown

### ISSUE THREAD

**Issue by antiuser** [phaag/nfdump#145]
Hi! I found one problem:
`usage /usr/bin/nfcapd [options] 
-y		LZ4 compress flows in output file.
`
but when i trying to start nfcapd with -y option i get next:
`/usr/bin/nfcapd: invalid option -- 'y'
`
but options -z -j works well
version 1.6.17

**Comment by phaag** [comment]
Oh - my bad. Fixed.
Thanks for the report.
