### ISSUE TITLE
[Feature request] nfcapd - add compression level 

### ISSUE THREAD

**Issue by antiuser** [phaag/nfdump#148]
Hi! Will be great if nfcapd support compression levels (for LZO,LZ4, BZ2 types). I cannot understand which compression level nfcapd use in 1.6.17 version.
Thank you much!

**Comment by phaag** [comment]
nfcapd supports all mentions compression levels. See -h help page.
Use one compression: -z for LZO, -j for BZ2 or -y for LZ4 compression

**Comment by antiuser** [comment]
@phaag sorry for my long answer time.
Yes im understand that nfcapd works with 3 types of compression, but when i compress file with nfdump with LZO compression - size of this file 50MB, but when nfcapd save file with LZO this size about 120MB.
Im assume there are different compression level (best compression level, fast compression level)
