### ISSUE TITLE
.spec fixes

### ISSUE THREAD

**Issue by rexy74** [phaag/nfdump#149]
Hi,
This is some fixes in the .spec file : 
--------------
Name: nfdump
Summary: A set of command-line tools to collect and process netflow data
Version: 1.6.17
Release: 1
License: BSD
Packager:
Group: Applications/System
Source: %{name}-%{version}.tar.gz
BuildRequires: flex
BuildRoot: %{_tmppath}/%{name}-root
Prefix: /usr
Url: https://github.com/phaag/nfdump

%description
The nfdump tools collect and process netflow data on the command line.
They are part of the NFSEN project, which is explained more detailed at
http://www.terena.nl/tech/task-forces/tf-csirt/meeting12/nfsen-Haag.pdf

%prep
rm -rf $RPM_BUILD_ROOT

%setup -q

%build
./autogen.sh
./configure --prefix=$RPM_BUILD_ROOT/%{prefix} --libdir=$RPM_BUILD_ROOT/%{_libdir}
make

%install
make install

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root)
%{prefix}/bin/*
%{prefix}/share/man/man1/*
%{_libdir}/*

%changelog
* Thu Jan 03 2019 Richard REY <Rexy>
- Version 1.6.17 (used in ALCASAR 3.3.3)

**Comment by phaag** [comment]
Thx. Updated.
