### ISSUE TITLE
Update sflow code to 5.x

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#150]
Hi there Pete,

Could you please update sFlow code to version 5.x ? I have a couple Huawei Switches (6720) which packets comes in but when it comes to nfdumping them I have zero data.

Best,
Gabe.

**Comment by phaag** [comment]
Would you be willing to share sflow v5 sample stream to test?

**Comment by gabrielmocan** [comment]
Sure. Sent via e-mail.

**Comment by gabrielmocan** [comment]
Sure, sent via email.

**Comment by phaag** [comment]
The pcap contains only counter samples - no flow samples. Any news on that?

**Comment by gabrielmocan** [comment]
Hey Pete, the problem was actually on the exporter side. Packets were coming with length error, according to sflowtools. I've patched the switches now they're working fine. We can close this issue for real. Thanks!
