### ISSUE TITLE
pipe output for bidirectional flows

### ISSUE THREAD

**Issue by nvitaly** [phaag/nfdump#151]
I would like to get easily parsable information for bidirectional flows, currently pipe output only shows single direction counters. ie I have ipkt/ibyt but no opkt/obyt.

Before I start changing sources, is it possible to get this information now? I like pipe because it gives IP as integer and because it is not humanizing bytes/pkts (M, G)

Let me know, thank you

**Comment by phaag** [comment]
The pipe output format is likely going to die in favour of the json format, as json is more flexible.
Is the -o json no option for you?

**Comment by phaag** [comment]
I close tis ticket due to no further discussion on this topic.
