### ISSUE TITLE
Allow sampling at nfcapd

### ISSUE THREAD

**Issue by natanmedeiros** [phaag/nfdump#153]
In some cases the router do not have sampling possibility. Example: Mikrotik.

That takes a high load of CPU to process tens of data analysis with tens millions of flows.

I want to use nfdump with sampled data even if router do not do it.

**Comment by hedibertosilva** [comment]
It would be awesome. I have the same problem.

**Comment by phaag** [comment]
Sampling nfcapd internally does not necessarily reduce data. Sampling means just taking every nth packet and for flows from that. But you still have 1 flow in the end, having either more or less packets/bytes recorded. It would not make sense. Furthermore you have to sample at router/exporter level to make sense. 

If you introduce sampling on nfcapd level, you would sample flows not packets, which would make you loosing a lot of data.

**Comment by phaag** [comment]
I possibility to reduce data size is aggregating flows. Sampling on nfcapd level is not an option.
Feel free to continue the discussion with any other ideas.
