### ISSUE TITLE
Reading nfcapd capture binary files in python

### ISSUE THREAD

**Issue by layeghy** [phaag/nfdump#154]
I wonder if there is any library/python package to be able to read the binary capture files of nfcapd.
Alternatively, I appreciate any formatting guide / help that can help me to figure it out myself.

**Comment by bbayles** [comment]
I made [this wrapper](https://github.com/bbayles/py3flowtools/blob/master/py3flowtools/nfdump_wrapper.py) around the `nfdump` CLI tool that may be of use.

**Comment by phaag** [comment]
I am not aware of any python package. I am not a python programmer. All you need can be found as comments in nffile.h
