### ISSUE TITLE
The sums of bytes in the resulting file of the pipe format with total bytes in Summary are different.

### ISSUE THREAD

**Issue by Farov** [phaag/nfdump#156]
I did several tests comparing the sum of bytes in the records of the resulting file of the pipe format
with the sum displayed in the Summary section of the same file and got a difference in the results.
It seems that, for some reason, not all records that pass through filtering and aggregation get into the resulting file ...
In the attached archive are: a data file and a script on the perl with which I check the results.
Tested on two different platforms, the version of the package NFDUMP is the same (1.6.17)

#tests:

#####  test_1
#nfdump -r ./nfcapd.201902270930  -f ./ip_stat.cfg   -o pipe  > result.txt
#perl ./test_sum.pl ./result.txt
#--------------------------------------------------
#OK: (Summary =  98657765773) = (Calc = 98657765773)
#Diff = Summary-Calc = 0

#####  test_2
#nfdump -r ./nfcapd.201902270930  -f ./ip_stat.cfg   -o pipe -A srcip  > result_source.txt
#perl ./test_sum.pl ./result_source.txt
#--------------------------------------------------
#ERR: (Summary =  98657765773) != (Calc = 98657765641)
#Diff = Summary-Calc = 132

#####  test_3
#nfdump -r ./nfcapd.201902270930  -f ./ip_stat.cfg   -o pipe -A dstip  > result_dest.txt
#perl ./test_sum.pl ./result_dest.txt
#--------------------------------------------------
#OK: (Summary =  98657765773) = (Calc = 98657765773)
#Diff = Summary-Calc = 0

#####  test_4
#nfdump -r ./nfcapd.201902270930  -f ./ip_stat.cfg   -o pipe -A srcip,dstip  > result_source-dest.txt
#perl ./test_sum.pl ./result_source-dest.txt
#--------------------------------------------------
#ERR: (Summary =  98657765773) != (Calc = 98657765639)
#Diff = Summary-Calc = 134

archive link  https://drive.google.com/open?id=1pC60wHMSsCOvRhWtN5xDAEC0KIfMYfnn
​
Test parameters and results - readme.txt

**Comment by phaag** [comment]
Hmm .. not good .. I have to check.

**Comment by phaag** [comment]
there is 1 flow missing in the output .. debugging continues

**Comment by phaag** [comment]
Fixed flowtable index error while printing flowtable.
