### ISSUE TITLE
Print debug messages to stderr

### ISSUE THREAD

**Issue by k0nd0r** [phaag/nfdump#157]
Would it be possible that the debug messages are printed to stderr instead of stdin?

https://github.com/phaag/nfdump/search?q=__VA_ARGS__&unscoped_q=__VA_ARGS__

**Comment by phaag** [comment]
Well these debug messages are meant to be used only while developing/debugging some code. If you plit stdout and stderr, you probably miss the order of regular output and debug messages. Therefore I decided to write all debug to stdout. If you need some output in regular operation, use syslog messages.
