### ISSUE TITLE
[Feature request] allow per source extension set

### ISSUE THREAD

**Issue by hansbogert** [phaag/nfdump#158]
we are receiving multiple streams on the same source port. For different streams we'd like to save different types of info by setting different extension tags per source.
So for the CLi,  I would envision an optional paramter to the `-n` option, e.g., `-n   Ident,IP,base_directory+3,+4` 

Of course we could change our environment to send to different ports on our sfcapd server, but then we'd need multiple sfcapd processes. However, due to circumstances this would be hard in our infrastructure.

Is this at all possible? If so, could this be implemented? If not, we are willing to spend some time on this and make a pull request., however could @phaag or other contributors describe how they would approach the feature request if they would have had the time?

**Comment by phaag** [comment]
Hmm .. I do not get it. Could you explain a bit more detailed, how 'base_directory+3' would work, and what for the addtional parameter/tag +4 is?

I am happy to add requested feature, or create a pull request. In order to make it into the master tree, I'd like to stay compatible with current cli switches. Otherwise it breaks too many users startup scripts. Adding a 4th tag to -n would be possible, if you stay compatible when given 3 args to -n

**Comment by hansbogert** [comment]
Hmm I did a bad job in explaining this:
`Ident,IP,base_directory+3,+4` should've been `Ident,IP,base_directory,+3,+4` (note the comma).

So in essence how I would envision this is that every extra parameter after `base_directory` would be refer to an extension, much like the how the '-T' option would receive them.

**Comment by phaag** [comment]
At the moment extensions are nfcapd globally defined and not per source. For nfdump 1.6.x I don't see any change here. nfdump 1.7.x - currently work inprogress - will change extensions anyway. While they still exist but differently, I am thinking about to make things easier, such as nfcapd automatically adds extensions based on what gets announced by the exporter.  This would mean, you will always get the largest common set between exporter and nfdump. 
As nowadays disk is less an issue it would ease nfdump handling. To my experience people use anyway -Tall to add all possible extension.
Comments? Suggestions?
