### ISSUE TITLE
Clarification request for template management

### ISSUE THREAD

**Issue by gauravagarwal** [phaag/nfdump#159]
Hi there, could someone please help me with this question around template management - if I have multiple reporting processes that use same reporter IP address, same template id and same observation domain id, but a different udp  source port per reportering process, is it a valid configuration as per ipfix rfc? And would nfcapd be able to handle decoding of data records in such a setting?

**Comment by phaag** [comment]
Currently nfcapd identifies an ipfix exporter by the sending IP address/obervation domain pair. The port is not taken into this consideration. Therefore nfcapd can not differentiate the two. To my knowledge the sending UDP port is not a reliable parameter, as it may vary.

**Comment by gauravvnera** [comment]
Thanks for the clarification. The reason we asked was because tshark supports this out of box when deciding ipfix traffic. And I assumed that it is therefore considered a standard behavior.

**Comment by phaag** [comment]
I am not aware of a specific standard for that. If you can point me to any document, it would be very appreciated.

**Comment by gauravvnera** [comment]
Thank you for following up on this!

Please refer to https://tools.ietf.org/html/rfc7011#section-8.4
Specifically, the points mentioned below. They seem to make it clear that collector should consider `Exporter source UDP port` for maintaining the template_id mapping.

Please let me know if there is anything you would want me to clarify on this.

```
8.4.  Additional Considerations for Template Management over UDP
   As Template IDs are unique per UDP session and per Observation
   Domain, at any given time, the Collecting Process SHOULD maintain the
   following for all the current Template Records and Options Template
   Records: <IPFIX Device, Exporter source UDP port, Collector IP
   address, Collector destination UDP port, Observation Domain ID,
   Template ID, Template Definition, Last Received>.
```
```
 The Exporting Process assigns and maintains Template IDs per
   Transport Session and Observation Domain.  A newly created Template
   Record is assigned an unused Template ID by the Exporting Process.
   The Collecting Process MUST store all received Template Record
   information for the duration of each Transport Session until reuse or
   withdrawal as described in Section 8.1, or expiry over UDP as
   described in Section 8.4, so that it can interpret the corresponding
   Data Records.
```

```
Transport Session
      In the Stream Control Transmission Protocol (SCTP), the Transport
      Session is known as the SCTP association, which is uniquely
      identified by the SCTP endpoints [RFC4960]; in TCP, the Transport
      Session is known as the TCP connection, which is uniquely
      identified by the combination of IP addresses and TCP ports used.
      In UDP, the Transport Session is known as the UDP session, which
      is uniquely identified by the combination of IP addresses and UDP
      ports used.
```

**Comment by phaag** [comment]
Thanks - I will check that

**Comment by phaag** [comment]
Implemented now for ipfix in master repo. New release follows soon.
