### ISSUE TITLE
How to set the Time window manually

### ISSUE THREAD

**Issue by fivestrong** [phaag/nfdump#163]
I had some trouble calculating the avg bps.
I use nfcapd to receive netflow data.This is the command I used.
```shell
nfcapd -T all -w -D -l /root/test/ -p 5555
```
then use nfdump to parse files
```shell
nfdump -r nfcapd.201905101125 | tail
```
this is the summary output: 
```shell
Summary: total flows: 106590, total bytes: 249211253, total packets: 270594, avg bps: 5402953, avg pps: 733, avg bpp: 920
Time window: 2019-05-10 11:22:50 - 2019-05-10 11:28:59
Total flows processed: 106590, Blocks skipped: 0, Bytes read: 10233656
Sys: 0.554s flows/second: 192388.6   Wall: 0.551s flows/second: 193216.5
```
As far as I know, nfcapd generates a file every 5 minutes by default.
but look at the  Time Window display, it's 369 seconds.So This is the problem.
"avg bps:5402953"  converted to 5.15Gbps, This is consistent with my calculation results using total bytes with Time Window.
But there is a gap between it and the actual router data with about 6.4Gbps.
If  I use total bytes divided by 300, The result is 6.34Gbps.Almost in line with reality.

So Is there any way to adjust the time window to 300s?

**Comment by phaag** [comment]
Hi,
By default nfcapd creates files every 300s, as you noted correctly. This is simply where flows get stored over time. Do not mistaken this with the Summary you read. This Summary reference the flows in that file. A flow is stored in that file, if it gets exported within this 300s windows. However, each flow has it's own start/end time markers, which means a flows can have started already bevor this 300s nfcapd time window and ends somewhere within this 300s window. The time window reported is the the earliest start among all flows up to lastest end among all flows, which may span more that 300s.
The avg bps and other avgs are calculated over this reported time window and the total sum od packets/bytes etc. These number may vary with those on the exporting device, as the device may use other time windows. 
The larges you take the nfcapd window the more are bps, pps etc averaged. 
Hope this helps.

**Comment by fivestrong** [comment]
@phaag Thank you for your patient answer.This is of great help to me.
