### ISSUE TITLE
Cisco WLC IPFIX apparently not recognised

### ISSUE THREAD

**Issue by mjsaarin** [phaag/nfdump#164]
Hi!

I didn't see the similar issue. Sorry if this is a duplicate.

We have been trying to export IPFIX data from two Cisco WLCs  running to our collector running latest nfcapd. So far, nfcapd hasn't stored any flow data. The logs just repor occasional sequence errors but the flow count is always zero. 

If I capture the traffic and examine it with Wireshark I see the packets contain IPFIX data. Could the support for WLC IPFIX be added to nfcapd? How can I help with this issue noting that I lack coding skills?

**Comment by mjsaarin** [comment]
Update: I have captured IPFIX packets containg data nfcapd won't parse. The contents of the data is such that I am permitted to send it to anyone willing to inspect this issue.

**Comment by bbayles** [comment]
@mjsaarin , I would be interested in examining the capture.

**Comment by mjsaarin** [comment]
@bbayles, Great! The pcap file can be downloaded from here:

https://datacloud.helsinki.fi/index.php/s/Ad9orX3NWWre7b2

**Comment by mjsaarin** [comment]
Also: After some alteration at the WLC end nfcapd was able to store the flows it appeared to find. The issue is that nfdump cannot parse the data, now.

**Comment by phaag** [comment]
Sorry, I do not understand what's wrong. If nfcapd stores flows, it's also able to process it. Make sure both binaries are from the same package. Your issue, that nfdump can not correctly decode stored data, is only possible with a *very* old nfdump binary. And if so you should see an error message in the logs. Can you check this and report the status of the WLC issue?
Thanks

**Comment by phaag** [comment]
No follow up received. Closed.

**Comment by mjsaarin** [comment]
Just an update:

After upgrading the WLC software to 8.5.151.0 it seems capable of sending IPFIX packets nfdump can parse. 

I see nothing in release notes that would indicate that anything IPFIX related has been fixed. Also, I can't find (could be just limited access) any resolved bug that would tell that something IPFIX/Netflow related has been fixed. 

In any case, I think the problem is on the WLC side and has nothing to do with nfcapd/nfdump.
