### ISSUE TITLE
accuracy on IPFIX export with duration 0

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [phaag/nfdump#166]
With Juniper PTX router configured 10s active/inactive flow timeout and 32767 sampling rate, all records have duration 0 (likely due to short timeout). With nfdump, bps is ~2x interface counter on most interfaces.
Is there a known limitation around IPFIX export with duration 0? How can I troubleshoot it?

IPFIX sampling rate is read correctly from nfdump (Add new sampler, interval: 32767)

The only thing that stood out is occasional sequence errors which is expected

**Comment by phaag** [comment]
Duration 0 is a bit odd, as you have at least flows running for 10s. The only thing I can imagine is, that
for some reason the exporter sends flow start/end with the same timestamp. Is at least tStart correct?

**Comment by jkldgoefgkljefogeg** [comment]
PTX has IE 152/153 (flowStartMilliseconds, flowEndMilliseconds). In my setup, they are always equal making duration 0. It is possible at 32k sampling rate the flow always get timeout evicted from cache before a second sample of the same flow is captured (or the delay in state update is >10s leading all flows to flow table lookup miss). A small percentage (~1%) of flow exports has more than 1 sample (2 or 3), but duration is still 0.

In my aggregator implementation by simpliy counting octetDeltaCount/packetDeltaCount the number seems to match interface counter, but nfdump aggregation is very far offt.

**Comment by phaag** [comment]
nfdump multiplies packets/bytes received in netflow data by the announced sampling rate. If octetDeltaCount/packetDeltaCount is already corrected by the sampling rate, then it is way off, if not you need to adjust those values. If the values are already corrected, the force ignore the sampling rate by hard wire it to "1" - telling nfcpad with -s -1.
