### ISSUE TITLE
nfpcapd - Unsupported link type

### ISSUE THREAD

**Issue by achillesheald** [phaag/nfdump#169]
I am using nfpcapd to convert some recent pcap to netflow and the standard output is printing "Unsupported link type: [0x6004 or 0x6002], packet: [packet_number].

I received this pcap from a trustworthy third party and I am able to pull some flows out of it however I believe the majority of the traffic is not reflected when importing it into sof-elk. Is this an issue anyone else has seen?

**Comment by phaag** [comment]
can you share a couple of those packets in a pcap?

**Comment by phaag** [comment]
No answer on pcap request.
