### ISSUE TITLE
almost all data is lost when aggregating with -A

### ISSUE THREAD

**Issue by az143** [phaag/nfdump#17]
for a variety of reasons i need to aggregate some flows by the usual quintuple PLUS the submitting agent/router. however, as soon as one uses any -A with any aggregation choice, GetMasterAggregateMask() is triggered which nukes almost all useful information from the resulting record: for example, the router and the in/out interfaces are gone, all icmp types become 0, and the received timestamp becomes 0/1.1.70.

to reproduce: nfdump -r somefile -a -o raw (or a -o fmt that includes %tr), produces the expected "good" output and the data from the first aggregated flow comes through fine.

now try nfdump -r samefile -A srcport,dstport,srcip,dstip,proto -o raw, and you'll see almost everything
come out as zero.

the culprit/cause: the memset(...,0) line in GetMasterAggregateMask().

personally i think that passing through the data from the first matching flow should take place
both when using -a and with -A; i'm not sure under what circumstances you'd ever want to zero anything with GetMasterAggregateMask(),  but maybe peter can provide a good rationale?

if there are such situations, then i'd suggest adding a cmdline option to pick the desired
pass-through behaviour for -A (and i'll cook up a patch/pull request for that on monday).

**Comment by phaag** [comment]
This is a matter of how you interpret the data. Filling the very first record with data and summing everything else up to that record can be heavily misleading! It also depend what you aggregate. In order to prevent these misleading interpretation of record data, the not affected fields are deliberately zeroed out, as you have in the resulting output no longer any indication, how the aggregation was done.
Therefore, I would like to keep the way it is.

**Comment by az143** [comment]
On Fri, 06 May 2016 04:07:11 -0700, Peter Haag writes:
>This is a matter of how you interpret the data. Filling the very first
>record with data and summing everything else up to that record can be
>heavily misleading!

i agree...

>It also depend what you aggregate.

...and i'm primarily concerned with the case of aggregating /more/
specifically than -A (e.g. the quintuple plus reporting agent),
and in that case i think getting results similar to -A, i.e. with first
values, should be possible (i'm not saying this should
be the /default/ behaviour).

>Therefore, I would like to keep the way it is.

i hope you will still consider the push request i sent, which makes
the behaviour for this situation selectable by adding the option "-1":
without that one gets the default behaviour and zeroed fields;
with it the first record's data is kept.

i think that provides a good compromise between not surprising people
with misleading data and flexibility on the other hand.

regards
az


-- 
Alexander Zangerl + GPG Key 0xB963BD5F + http://snafu.priv.at/
He who joyfully marches to music in rank and file has already earned my 
contempt. He has been given a large brain by mistake, since for him the 
spinal cord would fully suffice. -- Einstein
