### ISSUE TITLE
nfcapd.current file reading

### ISSUE THREAD

**Issue by tvc-dps** [phaag/nfdump#172]
Hello
I am using quite old, but working nfdump version 1.6.15.
I have custom script that read nfdump.current. file for each device and generate output it in geoip information base. I have multiple devices, for device that have ~>1Gbps traffic I see and can read data from nfdump.current. file, for devices with low traffic rate <100Mbps I do not see records in nfdump.current. file.
At same time for devices with low rate I see correct records in historical files in 2019/07/26/nfcapd.201907261305 as example.

I have treied to play with nfcapd -B value but it have not change anything.
is there anyway to see collected data in nfdump.current. file for small rate traffic devices?

**Comment by phaag** [comment]
That is not an issue from nfdump. It may a behaviour of your exporter. There is not difference if it's a current file or not. 
Processing the current file ist not recommended anyway, as this file is constantly being written.
