### ISSUE TITLE
Can't compile 1.6.18. Undeclared variables?

### ISSUE THREAD

**Issue by borjam** [phaag/nfdump#178]
Compile is aborting on bin/nfprofile.c on an undeclared variable.

`nfprofile.c:179:49: error: use of undeclared identifier 'record_ptr'
  ...if ( (sumSize + flow_record->size) > ret || (record_ptr->size < sizeof(r...
                                                  ^
1 error generated.
*** Error code 1`

I see that the variable is not declared indeeed and the same problem is present on bin/nfreader.c line 223.

Did you intend to write flow_record instead of record_ptr maybe?

**Comment by phaag** [comment]
Ups .. true - my bad! Fixed. I will update 1.6.18
