### ISSUE TITLE
nfcapd (1.6.17 or 1.6.18) compress, nfdump 1.6.18 cant decompress

### ISSUE THREAD

**Issue by Lelik13a** [phaag/nfdump#180]
Uncompress_Block_LZO() error decompression failed in nffile.c line 230: LZO error: -5
nfcapd uses  default  -z Compress flows. Use fast LZO1X-1 compression in output file.

With nfdump 1.6.17 possible change compression to bz2
nfdump 1.6.18 can work with it.

Debian stretch.

**Comment by phaag** [comment]
Thx. Fixed in repo. The switch to lzo1x_decompress_safe() requires a valid output buffer size.
I will replace v1.6.18
