### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by rafoko** [phaag/nfdump#181]
Hi
During make nfdump v 1.6.18 i get this error:
mv -f .deps/nfcapd-netflow_v9.Tpo .deps/nfcapd-netflow_v9.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -MT nfcapd-ipfix.o -MD -MP -MF .deps/nfcapd-ipfix.Tpo -c -o nfcapd-ipfix.o `test -f 'ipfix.c' || echo './'`ipfix.c
ipfix.c: In function ‘reorder_sequencer’:
ipfix.c:756:12: error: redeclaration of ‘i’ with no linkage
  for ( int i=0; i<table->number_of_sequences; i++ ) {
            ^
ipfix.c:670:5: note: previous declaration of ‘i’ was here
 int i, n;
     ^
ipfix.c:756:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for ( int i=0; i<table->number_of_sequences; i++ ) {
  ^
ipfix.c:756:2: note: use option -std=c99 or -std=gnu99 to compile your code
In file included from ipfix.c:335:0:
ipfix.c: At top level:
nffile_inline.c:41:19: warning: ‘ConvertCommonV0’ declared ‘static’ but never defined [-Wunused-function]
 static inline int ConvertCommonV0(void *record, common_record_t *flow_rec

What can I do ?
Thanks for advice

**Comment by phaag** [comment]
Thx for the hit. I fixed that in the repo. Please clone the repo and start from there. I will update the 1.6.18 release
