### ISSUE TITLE
Compile Error  v1.6.18 on Centos 7

### ISSUE THREAD

**Issue by takizo** [phaag/nfdump#184]
Greeting, we face an error when compiling on latest version  v1.6.18. Here is the info 

configure: WARNING: fts.h: present but cannot be compiled
configure: WARNING: fts.h:     check for missing prerequisite headers?
configure: WARNING: fts.h: see the Autoconf documentation
configure: WARNING: fts.h:     section "Present But Cannot Be Compiled"
configure: WARNING: fts.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------- ##
configure: WARNING:     ## Report this to peter@people.ops-trust.net ##
configure: WARNING:     ## ----------------------------------------- ##

Server OS: Centos 7.6.1810
autoconf 2.69

Currently we fall back to 1.6.17.

**Comment by phaag** [comment]
Hmm .. I can not confirm this error. On my Centos 7.6.1810 nfdump-1.6.18 release as well as master branch do compile without any problem.
Have a look into config.log, or send me config.log by email. I can check.

**Comment by takizo** [comment]
Thanks @phaag for looking into this. I've have the log on Pastebin. https://pastebin.com/5sJUQuun

**Comment by phaag** [comment]
Hmm .. but your config.log is not from release v1.6.18. Maybe from a later master branch.
Could you please try the master branch now, as I changed some compile issues on other platforms.
If it still does not compile, pls upload config.log again

**Comment by takizo** [comment]
The latest master work flawlessly! Excellent work! Thanks a lot @phaag ! Great work.
