### ISSUE TITLE
[Feature request] nfcapd: custom output filename

### ISSUE THREAD

**Issue by freeriderND** [phaag/nfdump#185]
Hi

First of all, thank you for a stable and functional product!

There is a need to use custom output filename for nfcapd.
Something like this option:

`-C <output_filename_template>`

where <output_filename_template> may look like: `tmpl%Y-%m-%d-%H-%S.ext`

In fact, we need to add seconds to the file name, because we use a file rotation interval of less than a minute. But it would be more correct to implement more flexible functionality.

Thanx!

**Comment by vslabs** [comment]
Feature request supported.

A 60s cycle results in over 4.1 million nfdump flow records/lines, and a 27s (or more) load to get this data into the database. I need load times of 10s or less, for the semi-realtime processing and reporting requirements in the database.

A 30s cycle should result in smaller dataset and much faster load times. A 170K flow record dataset for example, loads in 0.82s.

Thanks for an excellent s/w product.

**Comment by phaag** [comment]
60s?  4.1 million flows?? - I wasn't even aware nfdump takes that amount of flows ..
Actually it would be possible, but you break nfexpire or builtin expire option (-e) as this would need a bigger rework effort.
I will check it

**Comment by vslabs** [comment]
Hi Peter

Appreciate the response.

I designed & developed an in-house VPN client Netflow collection and reporting solution for a large telco.

Currently collecting Netflow (v5 & v9) using 16 servers - where the 8 old servers run my old SVR4 Netflow 5 capture s/w, and 8 new servers (in the process of being deployed) are running your nfcapd. These servers currently collect Netflow for 450 corporate client VPNs (WAN ingress traffic from over 16000 client edge routers).

It is a 3 step process with both old and new s/w:
- capture UDP to file
- when file is cycled, convert/dump file to plaintext CSV format
- load CSV file into database cluster

Thus data volumes are pretty large. Around 170+ million rows (IP flows) loaded into the database every 10 minutes.

Largest 10 loads of nfcapd files yesterday, with files being cycled every 60s:

SQL> select date_loaded, elapsed_time, cpu_time, rows_loaded from raw_files where date_loaded >= trunc(sysdate-1) and collector = 'rndf-ip-nfl-2' order by rows_loaded desc fetch first 10 rows only;

DATE_LOADED         ELAPSED_TIME         CPU_TIME     ROWS_LOADED
------------------- -------------------- ----------- ------------
2019/10/22 09:11:45 00:00:32.48          00:00:22.74    4,223,550
2019/10/22 11:08:56 00:00:33.81          00:00:20.45    4,174,080
2019/10/22 11:03:32 00:00:28.02          00:00:18.92    4,164,150
2019/10/22 10:33:34 00:00:29.94          00:00:18.78    4,153,020
2019/10/22 09:59:40 00:00:34.72          00:00:18.72    4,150,860
2019/10/22 10:50:35 00:00:30.54          00:00:18.73    4,141,140
2019/10/22 10:25:52 00:01:29.85          00:00:37.26    4,136,760
2019/10/22 10:59:47 00:00:36.79          00:00:19.13    4,133,370
2019/10/22 09:30:45 00:01:34.14          00:00:20.54    4,130,250
2019/10/22 11:12:33 00:00:27.42          00:00:19.16    4,120,080

10 rows selected.


Oh yeah - I have nfcapd creating its files in /dev/shm, to decrease I/O latency when using spinning rust. Also added some new formats to nfdump as I need data such as tcpflags and protocol, as integers - and not text. Analysis of flows happen in the database cluster using MPP (massive parallel processing).

And this is it, in a nutshell.

Your s/w is excellent - and seems to keep up with the UDP volumes to collect. So, thanks! :-)


regards,
Billy



----- Original Message -----

**Comment by phaag** [comment]
The master repo has been updated to accept time intervals down to 2s. For example -t 10.
If the time interval is set to values smaller than 60s the file naming extends to seconds e.g. nfcapd.20191117133040. Otherwise (t >= 60s) the file naming remains for compatibility. nfexpire handles both formats.

**Comment by freeriderND** [comment]
Thanx!
So good too

**Comment by vslabs** [comment]
Thanks! New file cycle/interval time is much appreciated.

**Comment by piorek94** [comment]
I was wondering why you limit time interval to 2 sec? Could you explain please? I tried to find any comments in code but without any success.
