### ISSUE TITLE
sflow from hsflowd undefined headerprotocol

### ISSUE THREAD

**Issue by csszep** [phaag/nfdump#186]
Hi!

I'm sending sflow from Cumulus switches to sfcapd. Cumulus use the hsflowd daemon.
The hsflowd.conf  is exactly the same as in the documentation:

https://docs.cumulusnetworks.com/cumulus-linux/Monitoring-and-Troubleshooting/Network-Troubleshooting/Monitoring-System-Statistics-and-Network-Traffic-with-sFlow/

I get the following log from the sfcapd:

 sfcapd[15761]: SFLOW: readFlowSample_header() undefined headerProtocol = 0
sfcapd[15761]: SFLOW: caught exception: -12

sfcapd -V
sfcapd: Version: 1.6.18

Thx
csszep

**Comment by csszep** [comment]
If i search something, i get the following:

** nfdump -M /opt/nfsen/profiles-data/live/cumulus1  -T  -R 2019/09/08/nfcapd.201909081350:2019/09/08/nfcapd.201909081400 -n 10 -s ip/flows
nfdump filter:
any
Skip unknown record type 0

Corrupt data file. Inconsistent block size in nfdump.c line 480

**Comment by phaag** [comment]
This "Corrupt data file" message means, that you most likely have a version mismatch of old/new software versions of nfdump. Make sure no old debris of system packages and/or self compiles binaries interfere with each other.

**Comment by csszep** [comment]
Cumulus has a bug id for this, so not an sfcapd issue i think.

https://docs.cumulusnetworks.com/cumulus-linux-37/Whats-New/rn/#CM-28212
