### ISSUE TITLE
[Feature Request] Full IPFIX definition/fields/entities/elements support

### ISSUE THREAD

**Issue by dwdixon** [phaag/nfdump#188]
Per the README, I wanted to voice/request that full IPFIX support be added to the nfdump suite of utilities.   I believe it's very important that great open source tools such as this project begin to fully support IPFIX as it's popularity and desirability seems to be growing fairly rapidly and having full IPFIX support would be very useful for many.  

A project I'm aware of that could help as a reference aside from the [RFC](https://tools.ietf.org/html/rfc7011) and [RFC Information Model ](https://tools.ietf.org/html/rfc7012) might be the [logstash "netflow" codec's ipfix.yaml](https://github.com/logstash-plugins/logstash-codec-netflow/blob/master/lib/logstash/codecs/netflow/ipfix.yaml).  

I would think there are many people and organizations that would love to have this excellent project fully support IPFIX.

Thank you!

**Comment by phaag** [comment]
I am open to add any given IPFIX elements, if they are required. However, I need for each new single or collection of new IPFIX elements a sample trace from an exporting device, as I want to verify the correct implementation. Furthermore, in 1.6.x there will be no new elements added as the backend format will change in 1.7.x 
I am very open for new ideas and try to hear what people may need, so the tool stays always most useful for anyone. But just taking the RFC and implementing everything on a theoretical basis is less what I want. nfdump is intended to be used as a netflow collection and processing tool and may not compete with logstash/elastic. 
If there is a specific IPFIX exporter you need to have supported, feel free to open a ticket.
