### ISSUE TITLE
JSON output is not valid JSON

### ISSUE THREAD

**Issue by falc410** [phaag/nfdump#189]
When using nfdump with -o json the output generated is not valid JSON (use jsonlint.com for example to verify) and thus it can not be parsed by any JSON library.

The current output looks like this:

```
{
	"type": "FLOW",
	"sampled": 0,
        ....
}

{
	"type": "FLOW",
	"sampled": 0,
      ....
} 
```

However it should have squared brackets surrounding the structure and each flow should be separated with a comma, like this:

`[ { ... }, { ... } ]`

**Comment by falc410** [comment]
Also noticed another bug. When using JSON output the bi-directional argument `-B` get's ignored.

**Comment by phaag** [comment]
Fixed bug for invalid json output.
Actually -B is not ignored as, since it outputs everything in the aggregated and accumulated flow. All relevant input/output values are printed.
Could you please elaborate, what's missing?
Thanks

**Comment by falc410** [comment]
Thanks for the bugfix Peter. 

Actually you are correct. It was my mistake, I double checked it and JSON does indeed put out aggregated flows. I must have did something wrong when I tested it last.
