### ISSUE TITLE
strange flows when allowing nat events on juniper mx480

### ISSUE THREAD

**Issue by romeor** [phaag/nfdump#190]
Hello,

We see a lot of 

`2019-10-14 13:32:44.000 UNKNOW  Ignore     0     10.36.58.173:0     ->          0.0.0.0:0        87.119.179.89:0     ->          0.0.0.0:0            0        0`

when we send nat events from juniper mx480 device to nfdump. The NAT CREATE and DELETE events are fully logged only for some random ports, non of well-known ports are seen:

`2019-10-14 11:59:56.490 CREATE  Ignore TCP      10.35.176.164:57363 ->     81.21.246.66:65215   146.255.182.23:58436 ->     81.21.246.66:65215        0        0`

which tells me there is some trouble with nfdump understanding flows sent from juniper?

Juniper is configured according to this:  https://www.juniper.net/documentation/en_US/junos/topics/example/services-flowmonitoring-logs-nat-configuring.html

nfdump ver:
/usr/local/bin/nfdump: Version: NSEL-NEL1.6.18

Any advices?

**Comment by romeor** [comment]
Just to mention, I am speaking of jFlow type nat event messages. Are these supported? If not, any way to support them also?

**Comment by phaag** [comment]
JunOS uses different templates in order to announce the NAT events, depending on the NAT type.
The Information Element (IE) IDs correspond to the IP Flow Information Export (IPFIX) Entities specification. So far so good. However, CISCO and JunOS do not agree on the interpretation of the value nat_event (ID: 230). For historic reason, the current implementations is bound to CISCO's interpretation. All other information elements are correctly interpreted, if sent by JunOS.. 
Note: Not all fields in all templates are sent!
In order to fix this, I can do a quick fix for JunOS at compile time.

**Comment by romeor** [comment]
Great news. Is there anything I can assist you with? IE ticket against juniper support or more dump data? Also could you please give some information on time when to expect the fix?

**Comment by romeor** [comment]
oh, as I can see, there is a fix included already. Unfortunately I get error about this file missing during make command
nfdump-master/doc/html/structSFLSampled__APP__coll__graph.map
and there is really no such file.

**Comment by phaag** [comment]
That's a doxygen build problem and not nfdump. That file is generated by doxygen.

**Comment by romeor** [comment]
So I'm stuck?

**Comment by romeor** [comment]
ok. I can just ignore that error. I've compiled the new nfdump but still i see same lines as I mentioned in my first post. The only thing has changed is Even and xEvent. But still lots on :0 -> :0. Or is it a question to JunOS now, what do they send and why?

**Comment by phaag** [comment]
What gets decoded correctly are the events. As of missing fields - JunOS does not send them.
See https://www.juniper.net/documentation/en_US/junos/topics/concept/services-logging-flowmonitoring-format-nat-events.html for a description of the templates and what they contain.
Except natOriginatingAddressRealm(229) which is not supported by nfdump, all other element IDs are decoded correctly, if they are sent.

**Comment by romeor** [comment]
ok, so it seems, like I have to ticket them. Could you please list the things I should include in the ticket to make nfdump data look "normal" with all populated fields

**Comment by phaag** [comment]
Please define what is "normal". Juniper may have a different philosophy than CISCO ASA/NAT.
AS of looking "normal" you may apply any user defined format -o fmt:... in order to look fine, without the :0 data. For historic reason, it was a demand from the user base, to implement CISCO ASA/NAT - with lots of more and less painful implementation steps. 
If you open a ticket with Juniper, you may argue with what information you need to have in order to make use of that data.

**Comment by romeor** [comment]
Under normal I mean that I really want to see in flow data the NAT magic: RFC-IP:PORT - DST-IP:PORT -> SRCNAT-IP:PORT - DST-IP:PORT. So according to the juniper documentation you mentioned, they are not sending these fields. But which ones? :) Juniper sends some lines just like what I want, but it seems like only 5% of that :0 -> :0 garbage.  Ie. Mikrotik sends everything right:   172.16.0.25:59712 ->     40.67.252.61:443     193.40.142.254:59712 ->     40.67.252.61:443
same way is expected from juniper.

**Comment by romeor** [comment]
So any idea I could ask juniper about? Which fields they should add?

**Comment by phaag** [comment]
I close the ticket. Feel free to open it again, if you have issues, which you thing are nfdump related.

**Comment by romeor** [comment]
Hello,
I've now set up a testing VM to address this issue again and creating the ticket for Juniper. Could you please assist me with that? I'd like to know, what excaly fields juniper does not send? We are still missing the full port translation information. We have more than 50k clients and it could not be true, that none of them are using web for browsing. We still got a lot of x.x.x.x:0 to x.x.x.x:0 translations. What is missing?

**Comment by phaag** [comment]
In my answer of on Oct 29, 2019 I explained the issue, why you see these 0.0.0.0. You need to explain Juniper, what you need.

**Comment by romeor** [comment]
Hello,

I've sent the information to juniper and raised a ticket. The've answered this:

> From the captures shared, we are observing that Juniper is sending out the right flow template information. Here is a snip from the pcap that you attached to the case. The information shared by Juniper is expected and not corrupted. Please let us know if you have configured the server to interpret the information received as the above is the flow template order. Let me know if you are looking for clarification from my end.
![jflow](https://user-images.githubusercontent.com/5564169/74661412-97b41480-51a0-11ea-9385-3d67aee25640.png)

**Comment by phaag** [comment]
Well - the answer of Juniper is generally not wrong. They send the information which is in the template - right. However, they do not (want??) to send more, even if there could be more. CISCO sends more information for NAT events. So it is in the eye of the beholder, to consider how much information they want to send for NAT. CISCO does more, Juniper less, which is therefore less useful.

**Comment by romeor** [comment]
Oh, ok, thanks. Is there any chance that Juniper's jflow technology is just not compatible with nfdump?

**Comment by romeor** [comment]
we've been analyzed it a bit further: seems like the box sends enough informaion.

> So, the problem you mentioned here is the Dst IP Addr:Port and X-Dst IP Addr:Port are not sent by Juniper. Also the Src port and X-Src port are showing up as 0.
> From the packet capture, we see Juniper box is sending out the requested information in Frame 4519.
![juniper2](https://user-images.githubusercontent.com/5564169/74829393-9d813580-5319-11ea-8729-d0bde982b153.jpg)

**Comment by romeor** [comment]
Hi!

any news on this one? any plans to extend the nfdump functionality when compiled with --enable-jnat? At this moment it seems that juniper box sends enough information, seems like information should be linked in some other way (not cisco way)?

ps
I'm sorry, am not able to re-open this ticket for some reason, there is no such button.

**Comment by phaag** [comment]
Re-opened

**Comment by phaag** [comment]
Please send me the pcap to look at this issue. Up to now, I just have an nfcapd file

**Comment by romeor** [comment]
sent tcpdump capture to phaag@users.sourceforge.net

**Comment by phaag** [comment]
The capure you sent me is decoded correctly by nfdump. As I already explained you in my post from Oct 29, 2019, JunOS does ***not*** send the elements which are zeroed in the output. 

Going through your capture you will see the following - information is take from debug output:
Your device announces 8 different exporters:
```
Process_v9: New exporter: SysID: 1, Domain: 11, IP: 146.255.176.9
Process_v9: New exporter: SysID: 2, Domain: 13, IP: 146.255.176.9
Process_v9: New exporter: SysID: 3, Domain: 8, IP: 146.255.176.9
Process_v9: New exporter: SysID: 4, Domain: 12, IP: 146.255.176.9
Process_v9: New exporter: SysID: 5, Domain: 14, IP: 146.255.176.9
Process_v9: New exporter: SysID: 6, Domain: 15, IP: 146.255.176.9
Process_v9: New exporter: SysID: 7, Domain: 9, IP: 146.255.176.9
Process_v9: New exporter: SysID: 8, Domain: 10, IP: 146.255.176.9
```

Each exporter announces it's specific tables - as an example exporte 8 announces table 278

```
[8] Process next packet: 56 records: 1, buffer: 44 
SourceID: 134217728, Sysuptime: 210201186.1581420223
Sequence: 6395398
[8] Next flowset: 0, length: 44 buffersize: 44 addr: 20

[8] Template ID: 278
template size: 40 buffersize: 40
found extension 37 for type: 323(ASA event time), at index: 78, input length: 8 output length: 8 Extension: 37, Offset: 0
Enable extension: 37: NSEL Common block
found extension 0 for type: 8(V4 src addr), at index: 12, input length: 4 output length: 4 Extension: 0, Offset: 8
found extension 39 for type: 225(ASA V4 xsrc addr), at index: 88, input length: 4 output length: 4 Extension: 39, Offset: 12
Enable extension: 39: NSEL xlate IPv4 addr
found extension 48 for type: 361(NAT port block start), at index: 111, input length: 2 output length: 2 Extension: 48, Offset: 16
Enable extension: 48: NAT Port Block Allocation
found extension 48 for type: 362(NAT port block end), at index: 112, input length: 2 output length: 2 Extension: 48, Offset: 18
found extension 48 for type: 363(NAT port step size), at index: 113, input length: 2 output length: 2 Extension: 48, Offset: 20
found extension 48 for type: 364(NAT port block size), at index: 114, input length: 2 output length: 2 Extension: 48, Offset: 22
found extension 37 for type: 323(ASA event time), at index: 78, input length: 8 output length: 8 Extension: 37, Offset: 24
found extension 46 for type: 230(NAT event), at index: 108, input length: 1 output length: 1 Extension: 46, Offset: 32
Enable extension: 46: NEL Common block
Add sending router IP address (ipv4) => Extension: 23
Force add router ID (engine type/ID), Extension: 25
Force add packet received time, Extension: 27
Parsed 9 v9 tags, total 7 extensions
Enabled extension: 23: IPv4 router IP addr
Enabled extension: 25: router ID
Enabled extension: 27: time packet received
Enabled extension: 37: NSEL Common block
Enabled extension: 39: NSEL xlate IPv4 addr
Enabled extension: 46: NEL Common block
Enabled extension: 48: NAT Port Block Allocation
[8/3] Get translation table 278: not found
[8] Add template 278

```

You have tables 256 up to 279 paired with the corresponding exporter.

The data is decoded according the template sent:

```
[8] Process next packet: 90 records: 9, buffer: 294 
SourceID: 134217728, Sysuptime: 1237051679.1581420224
Sequence: 6395400
[8] Next flowset: 278, length: 204 buffersize: 294 addr: 20
[8] ID 278 Data flowset
[8] Process data flowset size: 200
[8] Exporter is 0x140499080971632
[8] Exporter has sampler: no
[8] No Sampling record found
Buffer Size 808
[8] Process data record: 1 addr: 4, in record size: 33, buffer size_left: 200
[8] Process data record: MapID: 10
Found Time Event MSEC: 1581420219000

Flow Record: 
  Flags        =              0x46 EVENT, Unsampled
  label        =            <none>
  export sysid =                 3
  size         =               120
  first        =        1581420219 [2020-02-11 12:23:39]
  last         =        1581420219 [2020-02-11 12:23:39]
  msec_first   =                 0
  msec_last    =                 0
  src addr     =      10.27.179.85
  dst addr     =           0.0.0.0
  src port     =                 0
  dst port     =                 0
  fwd status   =                 0
  tcp flags    =              0x00 ........
  proto        =                 0 0
  (src)tos     =                 0
  (in)packets  =                 0
  (in)bytes    =                 0
  ip router    =     146.255.176.9
  engine type  =                 0
  engine ID    =                 8
  received at  =     1583352076349 [2020-03-04 21:01:16.349]
  connect ID   =                 0
  fw event     =                14: NAT PORT ALLOC
  fw ext event =                 0: Ignore
  secgroup tag =                 0
  Event time   =     1581420219000 [2020-02-11 12:23:39.000]
  src xlt ip   =    146.255.183.29
  dst xlt ip   =           0.0.0.0
  nat event    =                14: NAT PORT ALLOC
  ingress VRF  =                 0
  egress VRF   =                 0
  pblock start =             14824
  pblock end   =             14923
  pblock step  =                 1
  pblock size  =               100

```

Everything is decoded correctly. The template only announces "V4 src addr" and no V4 "dst addr" therefore dst addr is 0.0.0.0

The same is true for all other templates and records. You need to check the correct template along with the corresponding data record. 

The wireshark screenshot you sent shows template ID 256, which is also present in your capture:
Exporter 14 sends template 256:

```
[14] Process next packet: 628 records: 1, buffer: 56 
SourceID: 234881024, Sysuptime: 52217.1581420234
Sequence: 3051991
[14] Next flowset: 0, length: 56 buffersize: 56 addr: 20

[14] Template ID: 256
template size: 52 buffersize: 52
found extenProcess_v9: [14] Add template 256
sion 37 for type: 323(ASA event time), at index: 78, input length: 8 output length: 8 Extension: 37, Offset: 0
Enable extension: 37: NSEL Common block
found extension 0 for type: 8(V4 src addr), at index: 12, input length: 4 output length: 4 Extension: 0, Offset: 8
found extension 39 for type: 225(ASA V4 xsrc addr), at index: 88, input length: 4 output length: 4 Extension: 39, Offset: 12
Enable extension: 39: NSEL xlate IPv4 addr
found extension 0 for type: 4(proto), at index: 8, input length: 1 output length: 1 Extension: 0, Offset: 16
found extension 0 for type: 7(src port), at index: 11, input length: 2 output length: 2 Extension: 0, Offset: 17
found extension 38 for type: 227(ASA xsrc port), at index: 92, input length: 2 output length: 2 Extension: 38, Offset: 19
Enable extension: 38: NSEL xlate ports
found extension 0 for type: 12(V4 dst addr), at index: 17, input length: 4 output length: 4 Extension: 0, Offset: 21
found extension 39 for type: 226(ASA V4 xdst addr), at index: 89, input length: 4 output length: 4 Extension: 39, Offset: 25
found extension 0 for type: 11(dst port), at index: 16, input length: 2 output length: 2 Extension: 0, Offset: 29
found extension 38 for type: 228(ASA xdst port), at index: 93, input length: 2 output length: 2 Extension: 38, Offset: 31
Skip unknown element type: 229, Length: 1
found extension 46 for type: 230(NAT event), at index: 108, input length: 1 output length: 1 Extension: 46, Offset: 34
Enable extension: 46: NEL Common block
Add sending router IP address (ipv4) => Extension: 23
Force add router ID (engine type/ID), Extension: 25
Force add packet received time, Extension: 27
Parsed 12 v9 tags, total 7 extensions
Enabled extension: 23: IPv4 router IP addr
Enabled extension: 25: router ID
Enabled extension: 27: time packet received
Enabled extension: 37: NSEL Common block
Enabled extension: 38: NSEL xlate ports
Enabled extension: 39: NSEL xlate IPv4 addr
Enabled extension: 46: NEL Common block
[14/5] Get translation table 256: not found
[14] Add template 256

```

A corresponding record can be found in packet 644:

```
[14] Next flowset: 256, length: 40 buffersize: 329 addr: 288
[14] ID 256 Data flowset
[14] Process data flowset size: 36
[14] Exporter is 0x140499080971888
[14] Exporter has sampler: no
[14] No Sampling record found
Buffer Size 986000
[14] Process data record: 10 addr: 4, in record size: 35, buffer size_left: 36
[14] Process data record: MapID: 84
Found Time Event MSEC: 1581420232570

Flow Record: 
  Flags        =              0x46 EVENT, Unsampled
  label        =            <none>
  export sysid =                 5
  size         =               116
  first        =        1581420232 [2020-02-11 12:23:52]
  last         =        1581420232 [2020-02-11 12:23:52]
  msec_first   =               570
  msec_last    =               570
  src addr     =        10.35.35.5
  dst addr     =     212.47.220.55
  src port     =             51512
  dst port     =             60137
  fwd status   =                 0
  tcp flags    =              0x00 ........
  proto        =                 6 TCP
  (src)tos     =                 0
  (in)packets  =                 0
  (in)bytes    =                 0
  ip router    =     146.255.176.9
  engine type  =                 0
  engine ID    =                14
  received at  =     1583352076516 [2020-03-04 21:01:16.516]
  connect ID   =                 0
  fw event     =                 1: CREATE
  fw ext event =                 0: Ignore
  secgroup tag =                 0
  Event time   =     1581420232570 [2020-02-11 12:23:52.570]
  src xlt port =             20769
  dst xlt port =             60137
  src xlt ip   =     87.119.178.77
  dst xlt ip   =     212.47.220.55
  nat event    =                 1: CREATE
  ingress VRF  =                 0
  egress VRF   =                 0

```

Everything is decoded correctly.

You have to interpret the records according to the event. JunOS uses different templates for different event. You may need to consult the JunOS documentation in order to understand their philosophy what templates/data are sent for which events. You may start with  https://www.juniper.net/documentation/en_US/junos/topics/concept/services-logging-flowmonitoring-format-nat-events.html 

Again - nfdump decodes everything correctly and needs no changes. I hope you can now reproduce the reason for 0.0.0.0 in the records.

**Comment by romeor** [comment]
Okay, I guess, you are correct about jflow / nat events. But in the screenshot i've sent you - there is netflow data decoded with full information. Even if I de-configure the jflow / nat event config part - I still do not see the data seen in netflow frame. I mean Junos does send it, but nfdump do not see it. How could this be? Do you mean that I have to play with templates on the juniper box side for nfdump?

**Comment by phaag** [comment]
You still did not yet understand it - the screenshot you sent is template 256 which describes obviously create events and these are all correctly decoded. Look yourself into the raw data - analyse nfdump debug output yourself to see how it works
[debug.out.zip](https://github.com/phaag/nfdump/files/4301808/debug.out.zip)
You may also study, how netflow v9 in details works in order to read correctly the output.
 
nfdump decodes everything correctly, if sent by the exporter!

**Comment by romeor** [comment]
You are absolutely righ about me still not undarstanding it fully. I had only some experience with juniper srx and it was really much more easier to get v9 netflow data from those boxes. The mx series is different and a bit messy.

If I understand it right - when I configure the box to send jflow data and configure nfdump with --enable-jnat, nfdump looks for nat events only as you mentioned and it seems that it is expected behaviour when I see those 0-s. As this key during compile allows only for nat event monitoring.  And nat event is not supposed to carry the information I want - this is clear for me now. Thank you for links and explanation provided.

But, as it comes from tcpdump capture, it seems that when box is configured to send jflow data with v9 templates, it also sends the netflow data with v9 template - and it seems like it is the thing needed to be developed a bit different way. Is it possible for you to make some development on the nfdump side to make it work a bit other way? We do see all the required fields, when box sends jflow data with v9 templates anyways, right (the screenshot provided by me)? May be you would create special case when compiled with --enable-jflow to read the required data and display it like in the cisco nfsel case? This would be great "hack" to get v9 netflow data when box is configured to send jflow (nat events) data and would make a lot of people life easier, as jflow configuration is as simple as 1-2-3 compared with version9 netflow data on juniper mx boxes.

**Comment by phaag** [comment]
I am not sure if you read my remarks! Your screenshot is from template 256. It has nothing to do with your other data.
No - I will not create any "hack" - as it can not be done as you want.
Again - please study all documentation first and try to understand how template based netflow v9 works. 
As there is nothing to do, this issue will be closed

**Comment by romeor** [comment]
seems like there is some misunderstanding from your side also on this issue. tcpdump capture shows that we have enough data, but nfdump does not display it correctly no matter what I do. Even when I defind my own -o fmt format, it still shows zeros. mkay, thanks for help.

**Comment by romeor** [comment]
Hello,

just in case if someone else will ever face this issue. This is due to PBA (port-block allocation) configuration. When one is using the PBA in their config, there is other template used for NAT flow data according to RFC 8158. Here is a short overview.

<img width="776" alt="pba-rfc" src="https://user-images.githubusercontent.com/5564169/77891902-5f612500-727a-11ea-877a-6b4648f0d341.png">

So sorry for the wasted time this is really not an nfdump issue nor juniper issue. This is due to PBA configuration on the device and is expected to be so.
