### ISSUE TITLE
Cisco ISR Security Group Tag

### ISSUE THREAD

**Issue by danielgoolsby** [phaag/nfdump#192]
We are trying to collect Zone Based Firewall logs from some Cisco routers.  There is a field that I'm not sure how to enable or if it is able to parse with nfcapd.

I'm capturing with the -T nsel flag but I didn't see any of the extentions that might deal with the Security Group Tag that is added to the stream.

Is there a way to deal with this type of data?

I attached what the template id looks like, and a sample event- but I was not sure if there was a way/flag to extact what looks like dynamically added fields to the NSEL events.

![tid256](https://user-images.githubusercontent.com/29928395/68216052-42b41000-ffae-11e9-9526-66d52d5eda63.png)
![sam256](https://user-images.githubusercontent.com/29928395/68216053-434ca680-ffae-11e9-82e8-821428596412.png)

**Comment by spenceation** [comment]
We are also having similar issues. There is documentation on the field types within the following guide:

https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/sec_data_zbf/configuration/15-mt/sec-data-zbf-15-mt-book/sec-data-zbf-log.pdf

The field would be FW_CTS_SRC_SGT (34000).

**Comment by phaag** [comment]
Implemented in current repo - pls test.
