### ISSUE TITLE
Options -B and -w

### ISSUE THREAD

**Issue by josecamachop** [phaag/nfdump#195]
Hi,

I could not find a similar issue so here it goes. I have seen that -B cannot be used simultaneously with -A and I cannot understand the reason why. Also, when I try to use -B and -w it does not work.

Thanks

**Comment by phaag** [comment]
Hi,
There was in certain cases indeed a problem. I cleaned up the code and fixed the export function.

As of -A and -B: -A lets you choose, which elements in a flow record you want to aggregate. Option -B also aggregates flows bidirectionally. This means you can not mix them as -B overwrite -A.
Hope this helps.

**Comment by phaag** [comment]
I assume, the patch fixed your problem. I close the ticket. Otherwise feel free to reopen it.
