### ISSUE TITLE
scanner.l:298: bad test ?

### ISSUE THREAD

**Issue by dcb314** [phaag/nfdump#197]
scanner.l:298:18: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

Source code is

   if ( *c != '.' || *c != ':' || !isxdigit(*c) )

maybe better code

   if ( *c != '.' && *c != ':' && !isxdigit(*c) )

**Comment by phaag** [comment]
Thanks for the hint. This was old code, no longer used and has been now removed.
