### ISSUE TITLE
Instructions to convert old files

### ISSUE THREAD

**Issue by philhagen** [phaag/nfdump#198]
With the release of 1.6.18, I understand old files are no longer readable.  The README states "If you have nfdump-1.5.x please convert them before upgrading" but I can't find instructions or figure out how to perform this conversion.

I've tried using a v1.6.17 `nfdump` binary with both the `-r` and `-w` flags, but the resulting file cannot be read by version 1.6.18.  I've also tried `nfreplay` (also 1.6.17) but was unable to replay the old files, instead getting numerous "Skip unknown record type 1" messages.

Any guidance would be greatly appreciated.

**Comment by phaag** [comment]
Actually -r -w  does work. Make sure you have nfdump-1.6.17 compiled with --enable-compat15 to read the old records. Then run ./nfdump -r <file15> -z -w <file16>
Then nfdump 1.6.18 does read the converted data. You can verify, that's converted:

```
nfdump -v <file15>
File    : flows15.nf
Version : 1 - not compressed
Blocks  : 1
 Type 1 : 1
 Type 2 : 0
 Type 3 : 0
Records : 22

nfdump -v <file16>
File    : flows16.nf
Version : 1 - lzo compressed
Blocks  : 1
 Type 1 : 0
 Type 2 : 1
 Type 3 : 0
Records : 23

```

Note the change from type 1 to type 2

Hope, this helps.

**Comment by phaag** [comment]
Actually I found, what could have troubled you. If you have very oldfiles you would need 2 steps in oder to convert:
1. Install nfdump 1.6.1
2. Convert 1.5.x files with nfdump 1.6.1 ./nfdump-1.6.1 -r <file15> -z -w <file16>
3. Convert 1.6.1 files with nfdump 1.6.7: /nfdump-1.6.7 -r <file15> -z -w <file16>

This should do the trick.

**Comment by philhagen** [comment]
Thanks - will give this a try as soon as I'm able

**Comment by philhagen** [comment]
It seems like I may be encountering a different error, then.  When compiling either tag `v1.6.18` or from HEAD on master, The following occurs:

```
nfdump -R .
Date first seen          Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
Verify map id 0: map has a zero element
Corrupt extension map in nfx.c line 191

Corrupt data file. Unable to decode at nfdump.c line 588
```

If this should be a new issue, I can open one.  I can also provide a file that causes this to occur.

**Comment by phaag** [comment]
This is basically what you reported in issue #199. This is not a conversion issue of nfdump-1.5.x

`Verify map id 0: ERROR: Expected 7 elements in map, but found 2!`

This means your flow file is damaged somehow and can no longer be properly decoded.

**Comment by philhagen** [comment]
Ah ok - thanks.  This error appears with each of several hundreds of thousands of files I have - preventing an upgrade to 1.6.18, using several different versions of nfcapd (some via binary rpm installation, some via source compilation, etc).
Is there something that can be manually fixed via direct file manipulation?

https://sourceforge.net/p/nfdump/mailman/message/31085275/ suggests it is a benign error and should be self-corrected.

**Comment by phaag** [comment]
Please send me a file off list

**Comment by phaag** [comment]
Issue closed.
