### ISSUE TITLE
Not possible to see next/prev AS in line or custom output formats

### ISSUE THREAD

**Issue by landy2005** [phaag/nfdump#2]
This is collected by nfcapd from Cisco ASR (ios-xr 5.1.3) with netflow v9.
```
nfcapd -w -D -p 9992 -u www -g www -B 400000 -S 1 -P /usr/local/var/nfsen/run/p9992.pid -T all -I sdn-core2 -l /usr/local/var/nfsen/profiles-data/live/sdn-core2
```

RAW:
```
Flow Record:
  Flags        =              0x06 FLOW, Unsampled
  export sysid =                 1
  size         =                96
  first        =        1445692480 [2015-10-24 16:14:40]
  last         =        1445692480 [2015-10-24 16:14:40]
  msec_first   =               424
  msec_last    =               424
  src addr     =       151.80.4.33
  dst addr     =       185.44.13.7
  src port     =              9322
  dst port     =             54303
  fwd status   =               195
  tcp flags    =              0x04 ...R..
  proto        =                 6 TCP
  (src)tos     =                 0
  (in)packets  =                 2
  (in)bytes    =                80
  input        =                10
  output       =                 0
  src mask     =                16 151.80.0.0/16
  dst mask     =                32 185.44.13.7/32
  dst tos      =                 0
  direction    =                 0
  bgp next hop =           0.0.0.0
  ip router    =       10.12.0.102
  engine type  =                 0
  engine ID    =                 0
  next as      =                 0
  prev as      =              9002
  received at  =     1445692500393 [2015-10-24 16:15:00.393]
```

But when "%sas" or "%das" used, they always 0:
```
nfdump -o "fmt:%ts %td %pr %sap %sas -> %das %dap %flg %tos %pkt %byt %fl" -r nfcapd.201510241615

2015-10-24 16:19:29.520     2.024 TCP   2a02:20..00::7:2.179        0 ->      0 2a02:20..00::7:1.46309 .AP... 192        2      139     1
2015-10-24 16:19:29.721     1.624 TCP   2a02:20..00::7:1.46309      0 ->      0 2a02:20..00::7:2.179   .AP... 192        2      139     1
2015-10-24 16:19:31.122     7.802 TCP   2a02:20..00::6:1.45426      0 ->      0 2a02:20..00::6:2.179   .AP... 192        2      139     1
2015-10-24 16:19:31.322     7.401 TCP   2a02:20..00::6:2.179        0 ->      0 2a02:20..00::6:1.45426 .AP... 192        2      139     1
2015-10-24 16:19:38.222     0.000 TCP      31.177.85.241:179        0 ->      0    185.44.12.255:63928 .AP... 192        1       59     1
2015-10-24 16:19:38.352     0.000 TCP      185.44.12.255:63928      0 ->      0    31.177.85.241:179   .A.... 192        1       40     1
2015-10-24 16:19:39.764     0.000 TCP        151.80.4.33:9322       0 ->      0      185.44.13.7:22540 ...R..   0        2       80     1
2015-10-24 16:19:42.614     0.000 TCP      31.177.85.166:179        0 ->      0    31.177.85.167:54077 .AP... 192        1       59     1
2015-10-24 16:19:42.814     0.000 TCP      31.177.85.167:54077      0 ->      0    31.177.85.166:179   .A.... 192        1       40     1
```

**Comment by landy2005** [comment]
```
nfdump: Version: 1.6.13
```

**Comment by phaag** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,
Please note: sas, das ( source/destination AS) is not the same as next/prev AS
You have no source/destination AS in your record. Did you enable the appropriate
extension ( -T ) for src/dst AS.

Cheers

	- Peter

On 24.10.15 17:40, Mike Stupalov wrote:
> This is collected by nfdump from Cisco ASR (ios-xr 5.1.3) with netflow v9.
> 
> RAW: ``` Flow Record: Flags        =              0x06 FLOW, Unsampled export sysid =                 1 size
> =                96 first        =        1445692480 [2015-10-24 16:14:40] last         =        1445692480
> [2015-10-24 16:14:40] msec_first   =               424 msec_last    =               424 src addr     =
> 151.80.4.33 dst addr     =       185.44.13.7 src port     =              9322 dst port     =             54303 fwd
> status   =               195 tcp flags    =              0x04 ...R.. proto        =                 6 TCP (src)tos
> =                 0 (in)packets  =                 2 (in)bytes    =                80 input        =
> 10 output       =                 0 src mask     =                16 151.80.0.0/16 dst mask     =                32
> 185.44.13.7/32 dst tos      =                 0 direction    =                 0 bgp next hop =           0.0.0.0 
> ip router    =       10.12.0.102 engine type  =                 0 engine ID    =                 0 next as      =
> 0 prev as      =              9002 received at  =     1445692500393 [2015-10-24 16:15:00.393] ```
> 
> But when "%sas" or "%das" used, they always 0: ``` nfdump -o "fmt:%ts %td %pr %sap %sas -> %das %dap %flg %tos %pkt
> %byt %fl" -r nfcapd.201510241615
> 
> 2015-10-24 16:19:29.520     2.024 TCP   2a02:20..00::7:2.179        0 ->      0 2a02:20..00::7:1.46309 .AP... 192
> 2      139     1 2015-10-24 16:19:29.721     1.624 TCP   2a02:20..00::7:1.46309      0 ->      0
> 2a02:20..00::7:2.179   .AP... 192        2      139     1 2015-10-24 16:19:31.122     7.802 TCP
> 2a02:20..00::6:1.45426      0 ->      0 2a02:20..00::6:2.179   .AP... 192        2      139     1 2015-10-24
> 16:19:31.322     7.401 TCP   2a02:20..00::6:2.179        0 ->      0 2a02:20..00::6:1.45426 .AP... 192        2
> 139     1 2015-10-24 16:19:38.222     0.000 TCP      31.177.85.241:179        0 ->      0    185.44.12.255:63928
> .AP... 192        1       59     1 2015-10-24 16:19:38.352     0.000 TCP      185.44.12.255:63928      0 ->      0
> 31.177.85.241:179   .A.... 192        1       40     1 2015-10-24 16:19:39.764     0.000 TCP
> 151.80.4.33:9322       0 ->      0      185.44.13.7:22540 ...R..   0        2       80     1 2015-10-24
> 16:19:42.614     0.000 TCP      31.177.85.166:179        0 ->      0    31.177.85.167:54077 .AP... 192        1
> 59     1 2015-10-24 16:19:42.814     0.000 TCP      31.177.85.167:54077      0 ->      0    31.177.85.166:179
> .A.... 192        1       40     1 ```
> 
> --- Reply to this email directly or view it on GitHub: https://github.com/phaag/nfdump/issues/2
> 

- -- 
- --
Peter Haag
-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - http://gpgtools.org

iEYEARECAAYFAlY0p14ACgkQZFR7Ae3oDfZy8QCffZB5CdMnPfBntDA4z9zvwzPd
62kAn0zlWUfugVmlqFIzKFe/MHHX47VS
=SSiS
-----END PGP SIGNATURE-----

**Comment by landy2005** [comment]
But yes, I know that this is other records.
IOS XR (Cisco ASR9k), not support source/destination AS in netflow reports (I not know why).

But my question: pls **add keys like '%nas', '%pas'** for possible to view this records in "line" views.

**Comment by phaag** [comment]
The tokens %nas and %pas already exist. Maybe more format options than line long etc. will come.
