### ISSUE TITLE
top list by asn or network

### ISSUE THREAD

**Issue by prozaklob** [phaag/nfdump#200]
hi!
how i can grep top resurces by ASN or network?

now on manual i see only srcip/dstip

ASN not work ( i dont know how logged asn )

` -s dstnet/bytes  -n 50`

**Comment by phaag** [comment]
-s as/bytes
-s srcas/bytes -s dstas/bytes
see nfdump(1) man page

**Comment by prozaklob** [comment]
thx for reply,bt my nfdump not detect AS number.

**Comment by phaag** [comment]
At least nfdump has th option to do it, I guess your data does not contain as information

**Comment by prozaklob** [comment]
Version: NSEL-NEL1.6.13
i grep flow from mikrotik

**Comment by phaag** [comment]
So mikrotik does not send you the information, or it may be 0. You only have AS information if you have bgp routing on your device

**Comment by prozaklob** [comment]
> So mikrotik does not send you the information, or it may be 0. You only have AS information if you have bgp routing on your device

yap. Mikrotik no have bgp info in flow :(
