### ISSUE TITLE
libnfdump-1.6.18.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kisienya** [phaag/nfdump#202]
I am installing nfdump on Ubuntu 16.04 as follows
sudo apt-get install flex rrdtool librrd-dev libpcap-dev libtool m4 automake autogen build-essential  libjson-c-dev pkg-config libbz2-dev bison doxygen graphviz
ln -s /usr/include/pcap/bpf.h /usr/include/net/bpf.h
wget https://github.com/phaag/nfdump/archive/v1.6.18.tar.gz
tar -zxvf v1.6.18.tar.gz 
cd nfdump-1.6.18/
./autogen.sh 
./configure --help
./configure --enable-nsel --enable-nfprofile --enable-sflow --enable-readpcap --enable-nfpcapd
make
make install

All goes well with no errors but after installing I get the following error when I run nfdump
nfdump -V

nfdump: error while loading shared libraries: libnfdump-1.6.18.so: cannot open shared object file: No such file or directory

**Comment by Vingaard** [comment]
Hi @kisienya 
I had the very same problem - that was fixed via running the following command;
ldconfig

**Comment by phaag** [comment]
Yes - ldconfig should do the trick.
