### ISSUE TITLE
FreeBSD 12.x 

### ISSUE THREAD

**Issue by Mr-Method** [phaag/nfdump#203]
Hi everyone!
i need to install nfdump with the following arguments on freebsd 12.0.
However, I get an error during make
`libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/usr/local//include -ggdb -g -O3 -std=gnu11 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -DDEVEL -DNSEL -DJUNOS -DNSEL -DFIXTIMEBUG -MT util.lo -MD -MP -MF .deps/util.Tpo -c util.c  -fPIC -DPIC -o .libs/util.o

util.c:574:13: error: use of undeclared identifier 'AF_INET'
                inet_ntop(AF_INET, &ipv4, s, sSize);
                          ^

util.c:595:19: error: use of undeclared identifier 'AF_INET6'
        inet_ntop(AF_INET6, ip, s, sSize);
                  ^

2 errors generated.`

After editing the ./bin/util.c file as below patch
`--- /tmp/nfdump/bin/util.c	Thu Jan 23 11:36:28 2020

+++ /tmp/nfdump/bin/util.c	Thu Jan 23 11:37:56 2020

@@ -44,0 +45 @@

+#include <sys/socket.h>
`
make command was successful!
please commit this!

` # uname -a
FreeBSD 12.0-RELEASE-p10 FreeBSD 12.0-RELEASE-p10 GENERIC  amd64`
[gmake.1.log](https://github.com/phaag/nfdump/files/4102447/gmake.1.log) error log
[gmake.0.log](https://github.com/phaag/nfdump/files/4102448/gmake.0.log) make log
[nfdump.install.txt](https://github.com/phaag/nfdump/files/4102449/nfdump.install.txt) my  instructions
[util.c.patch.txt](https://github.com/phaag/nfdump/files/4102458/util.c.patch.txt) patch

**Comment by phaag** [comment]
Thx. Done.

**Comment by Mr-Method** [comment]
now i catching next error many times
`root@dbn:/tmp/nfdump # nfdump -r /var/flows/9.1.1.228/nfcapd.202005250003
Date first seen          Event  XEvent Proto      Src IP Addr:Port          Dst IP Addr:Port     X-Src IP Addr:Port        X-Dst IP Addr:Port   In Byte Out Byte
Process: '/var/flows/9.1.1.228/nfcapd.202005250003'
Corrupt data file. Inconsistent block size in nfdump.c line 472
`

or using perl script with the same file:

`PANIC! - Verify map id 0: ERROR: map size 0 too small!`

**Comment by phaag** [comment]
This error is reported if your flow data file is inconsistent  regarding the number of bytes read, and the summed up record size. Therefore your flow file is corrupted somehow.
