### ISSUE TITLE
problem in displaying MAC adress

### ISSUE THREAD

**Issue by Vingaard** [phaag/nfdump#204]
Hi there, I am currently facing a problem with displaying MAC address from previous captured  PCAP.

OS; Ubuntu 18 - nfdump build from source with readpcap & -nfpcapd enabled.
Convert the PCAP to netflow via nfpcapd -r 
However the MAC is set to 00:00:00:00:00:00 .. aka not extracting the real MAC values from the PCAP :-( 

nfdump -A insrcmac,outsrcmac,dstip,indstmac,outdstmac -r nfcapd.201510202205
Date first seen          Duration    In src MAC Addr  Out src MAC Addr      Dst IP Addr   In dst MAC Addr  Out dst MAC Addr    
2015-10-20 22:05:01.099   296.959  00:00:00:00:00:00 00:00:00:00:00:00     192.168.88.1 00:00:00:00:00:00 00:00:00:00:00:00  
...
Summary: total flows: 366, total bytes: 264716, total packets: 4076, avg bps: 3533, avg pps: 6, avg bpp: 64
For reference, the pcap in question is 
https://download.netresec.com/pcap/4sics-2015/4SICS-GeekLounge-151020.pcap

Many thanks for any idea or suggestion in above problem.

**Comment by phaag** [comment]
This version of nfpcapd does not support collecting MAC addresses. It's on the ToDo list for future releases.

**Comment by Vingaard** [comment]
@phaag - many thanks for your fast feedback and for providing NFdump.
