### ISSUE TITLE
Option Templates Supported?

### ISSUE THREAD

**Issue by jobongo** [phaag/nfdump#206]
I am trying to get information from Cisco High Speed Logging (HSL) events using the option templates and data fields. It doesn't seem the code is there for processing the option fields other than the sampling option but I was wondering if that is indeed the case or am I overlooking something in the code? I have attached a screenshot of a Wireshark Capture to show the fields and templates.

I began writing/modifying the functions to process this but figured I would ask before I got too far along. Thanks.

![Capture](https://user-images.githubusercontent.com/3405674/75126764-04d41800-5681-11ea-967b-ffc2c7117327.PNG)
![Capture2](https://user-images.githubusercontent.com/3405674/75126766-07367200-5681-11ea-99c7-33709e7409f4.PNG)
![Capture3](https://user-images.githubusercontent.com/3405674/75126768-08679f00-5681-11ea-8f66-1cddc00e8859.PNG)

**Comment by phaag** [comment]
Option templates are supported only as needed - so far for sampling. Any other option templates need to be integrated on a case bases, if there is a broad interest.

**Comment by phaag** [comment]
I close the ticket, as I got no further comment. If you have a specific need for an option template, please reopen the ticket and explain your needs.
Thanks
