### ISSUE TITLE
JunOS netflow data continued

### ISSUE THREAD

**Issue by romeor** [phaag/nfdump#209]
Sorry about asking the same thing in new thread, but am not able to re-open the last thred you've closed. Please, could you give me some information regarding this issue? We here on our side have to decide which tools and which way we will be using. I totally understand, that it is freeware opensource project without any obligations, but few simple words would be fine.

we've been analyzed it a bit further: seems like the box sends enough informaion.

> So, the problem you mentioned here is the Dst IP Addr:Port and X-Dst IP Addr:Port are not sent by Juniper. Also the Src port and X-Src port are showing up as 0.
> From the packet capture, we see Juniper box is sending out the requested information in Frame 4519.
![juniper2](https://user-images.githubusercontent.com/5564169/74829393-9d813580-5319-11ea-8729-d0bde982b153.jpg)

_Originally posted by @romeor in https://github.com/phaag/nfdump/issues/190#issuecomment-588167984_

**Comment by phaag** [comment]
Closed double ticket to #190
