### ISSUE TITLE
./configure --enable-shared=no doesn't work

### ISSUE THREAD

**Issue by az143** [phaag/nfdump#21]
it's no longer possible to build nfdump without shared library, despite configure exposing --enable-shared. if you use --enable-shared=no, then the build fails:

Entering directory '...../bin'
/bin/bash ../libtool  --tag=CC   --mode=link gcc -ggdb  -g -O2 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -release 1.6.14 -shared   -o libnfdump.la -rpath /usr/local/lib nf_common.lo util.lo minilzo.lo nffile.lo nfx.lo nfxstat.lo flist.lo fts_compat.lo grammar.lo scanner.lo nftree.lo ipconv.lo exporter.lo  -lresolv  -lbz2
libtool: link: can not build a shared library

**Comment by az143** [comment]
i've fixed this in our fork: simply remove the "-shared" in bin/Makefile.am's  libnfdump_la_LDFLAGS and run autoreconf. after that --enable-shared=no and yes are honored correctly.

**Comment by phaag** [comment]
Fixed! - Thanks
