### ISSUE TITLE
flow_sample_element length error

### ISSUE THREAD

**Issue by hedibertosilva** [phaag/nfdump#210]
Hi,

I've some problems with sfcapd collector on device "S6720 V200**R011**". 

SFLOW: flow_sample_element length error (expected 20, found 24)
SFLOW: caught exception: 1

I also test with sflow/sflowtool (hub.docker.com/r/sflow/sflowtool):

flow_sample_element length error (expected 20, found 24)
caught exception: 3

I suppose that current firewall version added new fields to the flow export element that went out global patterns (InMon sFlow).

I've been successful with same sfcapd to another device "S6720 V200**R010**".

Can you help me?

**Comment by phaag** [comment]
Hmm .. if sflowtool also throughs an exception is is most likely an incompatibility with your device.
You may contact your device vendor/manufacture for more information.
