### ISSUE TITLE
nfdump -c [number] option prevents flow displays

### ISSUE THREAD

**Issue by indyprime** [phaag/nfdump#217]
Hi! I found that using the nfdump -c [number] option to limit flows to the specified number seems to prevent *any* flows from being displayed. I first found it in nfdump version 1.6.19, but I just built and tested version 1.6.20 from github, and the issue still exists.

For example,
nfdump -M [path to flows]  -T  -R 2020/04/16/nfcapd.202004161255:2020/04/16/nfcapd.202004161630 -6 -O tstart "proto icmp or proto icmp6" shows 586 flows, showing that there are flows in that time period.

However, the same command with -c added shows none.
/nfdump -M [path to flows]  -T  -R 2020/04/16/nfcapd.202004161255:2020/04/16/nfcapd.202004161630 -6 -O tstart -c 150 "proto icmp or proto icmp6"

Will you please look into this? Thank you!

-Indy

**Comment by phaag** [comment]
By using -c you limit your flow analysis within the first 'n' flows. if your icmp/icmp6 flows appear later in the stream than your first 150 records, then you get a zero output. This behaviour is expected. If you read the usage message:
 "-c Limit number of records to read from source(es)"
