### ISSUE TITLE
Running nfcapd in Docker Container

### ISSUE THREAD

**Issue by aumisb** [phaag/nfdump#218]
I am running `nfcapd` in a Docker container (with debian:buster-slim as my base image). My setup is as follows:
pfSense box (192.168.1.1) with softflowd and my server (192.168.1.10) with the `nfcapd` docker container; my softflowd instance is configured to send datagrams to 192.168.1.10:8010.

For `nfcapd` to receive netflow datagrams from my pfSense box, I had to use "host" networking for the Docker container. The different Docker networking options are available [here](https://docs.docker.com/network/). In short, host networking means the network configuration inside the container matches the configuration outside the container (i.e., the server).

Typically, I've used "bridge" networking for Docker containers, which utilizes port forwarding to route data from the host to the container as a container has its own network namespace with its own IPs. For example, the container may have an IP of 172.17.0.2 while my server's IP is 198.168.1.10.
I was expecting `nfcapd`to work with "bridge" networking after setting its bind address to "0.0.0.0", but it was unable to receive anything. I assume "0.0.0.0" means listen on *all interfaces*.  I have also tried the default option of binding to any available interface.

Any ideas why "bridge" networking is not working.
I am happy to share my Dockerimage file.

**Comment by phaag** [comment]
I am sorry, I am not a docker expert. Maybe you can ask for help in any of the available docker Q&A  forums.
