### ISSUE TITLE
nfreplay corrupt some flows

### ISSUE THREAD

**Issue by ninnux** [phaag/nfdump#220]
I'm trying to use nfreplay to filter and bounce flows to another nfcapd daemon.
I tried both v1.6.20 and v1.6.18 with similar results.
Some flows are corrupted, very large numbers on ifindexes, false IPs, timestamp set to 1/1/1970, and many other strange things.
source nfcapd files have correct fields, after nfreply flows are corrupted.
I used this command:
nfreplay -v 9 -r /data/live/$ROUTER/$YEAR/$MONTH/$DAY/nfcapd.$NFTIME -H $HOST -p $PORT "$FILTER"
Can you help me?

**Comment by phaag** [comment]
Can you pls send me one such nfcap file?

**Comment by ninnux** [comment]
Yes, for sure. I'm sorry for the delay. I just see your reply.

**Comment by phaag** [comment]
Just one of the nfcapd files, when replayed get corrupted - so the original one

**Comment by phaag** [comment]
Any update on that?

**Comment by phaag** [comment]
No update received.
