### ISSUE TITLE
nfdump-1.6.20 build issues

### ISSUE THREAD

**Issue by Reyz-R** [phaag/nfdump#225]
There were no problems with "./configure --enable-nsel --enable-nel --enable-nfprofile --enable-nftrack --enable-fixtimebug".
The problem appeared  with "make" .

[root@ddos-Rostov nfdump]# make
make  all-recursive
make[1]: Entering directory `/usr/src/nfdump'
Making all in .
make[2]: Entering directory `/usr/src/nfdump'
make[2]: Leaving directory `/usr/src/nfdump'
Making all in bin
make[2]: Entering directory `/usr/src/nfdump/bin'
/bin/sh ../ylwrap grammar.y y.tab.c grammar.c y.tab.h grammar.h y.output grammar.output -- bison -y  -d
conflicts: 1 shift/reduce
updating grammar.h
make  all-am
make[3]: Entering directory `/usr/src/nfdump/bin'
depbase=`echo output_util.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -ggdb  -g -O3 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -DNSEL -DNSEL -DFIXTIMEBUG -MT output_util.lo -MD -MP -MF $depbase.Tpo -c -o output_util.lo output_util.c &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -ggdb -g -O3 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -DNSEL -DNSEL -DFIXTIMEBUG -MT output_util.lo -MD -MP -MF .deps/output_util.Tpo -c output_util.c  -fPIC -DPIC -o .libs/output_util.o
output_util.c: In function ‘ProtoNum’:
output_util.c:207: error: ‘for’ loop initial declarations are only allowed in C99 mode
output_util.c:207: note: use option -std=c99 or -std=gnu99 to compile your code
make[3]: *** [output_util.lo] Error 1
make[3]: Leaving directory `/usr/src/nfdump/bin'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/usr/src/nfdump/bin'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/nfdump'
make: *** [all] Error 2
[root@ddos-Rostov nfdump]# make[3]: *** [output_util.lo] Error 1

[nfdump.txt](https://github.com/phaag/nfdump/files/4656956/nfdump.txt)

With best regards,
Andrei Z.

**Comment by phaag** [comment]
Hmm .. looking at your nfdump.txt file, I see
./configure: line 3558: AX_CHECK_C11: command not found
This is included in the m4 directory of the nfdump-1.6.20 bundle. Did you just copy over some file of nfdump-1.6.20 into an existing, older nfdump directory?
Please download a frech copy and work from that.
Note:
Pls do not enable --enable-fixtimebug if you really now, you need it!!
