### ISSUE TITLE
Cisco C9336C-FX2 tcp/udp off the scale numbers

### ISSUE THREAD

**Issue by atbohmer** [phaag/nfdump#227]
Hello,

Seems I did configure something not correct or ndump is misinterpreting some netflow v9 data.
Packets counters data in nfdump for tcp/udp is way too much (even in Tb), see this single timeslot:

Flows                                                      | Packets                                                                     | trafic
  | all: | tcp: | udp: | icmp: | other: | all: | tcp: | udp: | icmp: | other: | all: | tcp: | udp: | icmp: | other:
  | cisco | 7.4 k/s | 6.8 k/s | 494.0  /s | 43.7  /s | 0.3  /s | 576.8 G/s | 452.6 G/s | 122.8 G/s | 1.4 G/s | 150.9 M/s | 81.5 Tb/s | 73.2 Tb/s | 7.7 Tb/s | 577.2 Gb/s | 6.8 Gb/s

On the switch monitored interface:
 Load-Interval #2: 5 minute (300 seconds)
    300 seconds input rate 1886363520 bits/sec, 293493 packets/sec
    300 seconds output rate 1643942488 bits/sec, 292809 packets/sec
    input rate 1.89 Gbps, 293.49 Kpps; output rate 1.64 Gbps, 292.81 Kpps

Any ideas how to debug this?

Best regards,
Andre

Cisco netflow config:
version 9.3(2) Bios:version 05.39 
feature netflow

flow timeout 60
flow exporter e1
  description Flow exporter Hyperion border traffic
  destination x.x.x.x use-vrf management
  transport udp 1111
  source mgmt0
  version 9
flow record r1
  description ipv4 traffic flow record
  match ipv4 source address
  match ipv4 destination address
  match ip protocol
  match transport source-port
  match transport destination-port
  collect transport tcp flags
  collect counter bytes
  collect counter bytes long
  collect counter packets
  collect counter packets long
  collect timestamp sys-uptime first
  collect timestamp sys-uptime last
  collect ip version
flow record r2
  description  ipv6 netflow sampler
  match ip protocol
  match transport source-port
  match transport destination-port
  match ipv6 source address
  match ipv6 destination address
  collect transport tcp flags
  collect counter bytes
  collect counter bytes long
  collect counter packets
  collect counter packets long
  collect timestamp sys-uptime first
  collect timestamp sys-uptime last
  collect ip version
flow monitor m1
  description  ipv4 flow monitor
  record r1
  exporter e1
flow monitor m2
  description ipv6 flow monitor
  record r2
  exporter e1

interface Ethernet1/1
  ip flow monitor m1 input  
  ipv6 flow monitor m2 input

**Comment by atbohmer** [comment]
Seems both collect counter packets long and collect counter bytes long play a role in this, after removing those from the flow record all seems to match reality now.

**Comment by phaag** [comment]
Would you mind to send me off list a couple of pcaps sent to nfcapd with the different configuration options? ( with/without the long packets/bytes option). That would help me to debug.
Thanks

**Comment by atbohmer** [comment]
Great, how can I contact you off list?

**Comment by phaag** [comment]
Lookk in the AUTHORS file for the email

**Comment by phaag** [comment]
After investigating your data, the exporter announces twice packets and bytes counters - one time 4 bytes and one time 8 bytes. Maybe try to remove the lines

collect counter bytes
collect counter packets

Maybe this stops double announcements. nfdump does not support double announcements for
the same tag with different size.

**Comment by phaag** [comment]
According to the data you sent, your exporter announces the counter twice - once 32bis and once 64bit. nfcapd uses the latter in the announcement which is the 64bit counter. However, the number exported in the 64bit counter is wrong, the one in the 32bit counter is correct. To fix this, speak to your vendor or remove the 'collect counter bytes long' option.
