### ISSUE TITLE
Machine architecture independent nfcapd file format

### ISSUE THREAD

**Issue by rameshcomputer** [phaag/nfdump#228]
I read that 'For speed reasons the binary format is machine architecture dependent, and as such can not be exchanged between little and big endian systems.'

Q: What it would take to enhance nfcapd to store files in architecture independent format? Is there a way to tell nfcapd store files in little endian format on big endian machine or vice a versa?  Thank you.

**Comment by phaag** [comment]
Well - it would mean to modify all netflow protocols v1/v5/v9/ipfix writer as well as the common format reader to make them architecture aware. This is an effort, I currently don't see a reason for. 
It also might have a performance impact for actually no really benefit.

**Comment by phaag** [comment]
I close the ticket for now. In case of more input, please open the ticket again
