### ISSUE TITLE
nfdump NSEL-NEL1.6.20 time window label in report is not correct

### ISSUE THREAD

**Issue by pnpestov** [phaag/nfdump#229]
Good day! Time window label in report is not correct, but data all right.
Example: 
nfdump -R /var/netflow/ -t **2020/06/19.05:45-2020/06/19.06:45** -s srcip 'dst ip X.17.0.87 and src net X.17.0.0/24'
Top 10 Src IP Addr ordered by flows:
Date first seen          Duration Proto       Src IP Addr    Flows(%)     Packets(%)       Bytes(%)         pps      bps   bpp
2020-06-19 05:45:05.828  3592.044 any         X.17.0.10      516(100.0)    40721(100.0)    8.6 M(100.0)       11    19088   210

Summary: total flows: 516, total bytes: 8.6 M, total packets: 40721, avg bps: 19088, avg pps: 11, avg bpp: 210
Time window: **2020-06-19 05:15:13 - 2020-06-19 07:19:53**
Total flows processed: 130926, Blocks skipped: 0, Bytes read: 8381468
Sys: 0.041s flows/second: 3163380.7  Wall: 0.038s flows/second: 3432864.0

**Comment by phaag** [comment]
The time Window reports the time window from all processed flows, like **Total flows processed** etc. 
Maybe it would be more clear to have an additional line and reporting both windows.

**Comment by pnpestov** [comment]
Thanks for the quick response. I had such an assumption, but decided to clarify.
