### ISSUE TITLE
option "format output" not working?

### ISSUE THREAD

**Issue by ingvarrwvw** [phaag/nfdump#232]
nfdump -R nfcapd.202007061040 -c 10 -o "fmt:%ts %td %pr %sap -> %dap %flg %tos %pkt %byt %fl" > log

cat log:

s d logr logap -> /mnt/nfcapd/2020/07/06ap loglg os logkt logyt logl

Summary: total flows: 1, total bytes: 11122, total packets: 30, avg bps: 185366, avg pps: 62, avg bpp: 370
Time window: 2020-07-06 10:10:36 - 2020-07-06 10:45:31
Total flows processed: 11396, Blocks skipped: 0, Bytes read: 1048500
Sys: 0.005s flows/second: 1903457.5  Wall: 0.003s flows/second: 3592686.0

Pre-defined set work ok:

nfdump -R nfcapd.202007061040 -c 1 -o extended:

Date first seen          Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Flags Tos  Packets    Bytes      pps      bps    Bpp Flows
2020-07-06 10:40:20.206     0.000 UDP       185.153.44.8:61567 ->  129.211.176.242:53    ......   0        1       68        0        0     68     1
Summary: total flows: 1, total bytes: 11122, total packets: 30, avg bps: 185366, avg pps: 62, avg bpp: 370
Time window: 2020-07-06 10:10:36 - 2020-07-06 10:45:31
Total flows processed: 11396, Blocks skipped: 0, Bytes read: 1048500
Sys: 0.005s flows/second: 2232321.3  Wall: 0.003s flows/second: 3663130.8

**Comment by phaag** [comment]
Sory - I can not reproduce this. Output formating was not changed. It makes not difference if you use the predefined format or if you give one on cmd line. 

If you have more input please reopen the ticket.
