### ISSUE TITLE
[feature request] Reverse statistic - e.g. Bottom <n> records

### ISSUE THREAD

**Issue by philhagen** [phaag/nfdump#235]
Currently, the `-s stat/orderby` output lists the *top* records.  It would be useful to negate these sometimes to find the *bottom* records for long-tail analysis.

I'm not sure if this would be best accomplished with an additional flag to invert the statistic sorting, or by some syntax such as `-s stat/-orderby`, but either way the feature would be immensely helpful.

**Comment by phaag** [comment]
It's an idea I already had some time back, but never really implemented. So let's do it now.

**Comment by phaag** [comment]
Option added in master repo. Applies with `-s stat/orderby `or `-O orderby`. Add optional `:a` for ascending or `:d` for descending to `orderby` in order to change the print order. If specified, it overwrites the default print order.

**Comment by philhagen** [comment]
excellent - thank you!  one of my students asked about this feature during class and was excited to see the feature added so quickly. cheers!
