### ISSUE TITLE
direction filter for nfdump

### ISSUE THREAD

**Issue by jwestfall69** [phaag/nfdump#236]
I'm wanting to be able to filter out netflow records with nfdump based on the netflow v9 direction field.  The grammar gives the impression 'dir 0|1' or 'dir ingress|egress' should be possible for filtering, but any combination I try gives me a syntax error.

```
$ nfdump -r nfcapd.202007271800 "dir 1"
Line 1: syntax error at 'dir'
```
Is there some way to do this I'm not seeing?

**Comment by jwestfall69** [comment]
I was able to eventually figure this out after poking at the code some more. The filter is wanting 'flowdir', even though all the code references it as just 'dir'

**Comment by phaag** [comment]
Got the point. I added 'dir' as an equivalent filter token to ;flowdir'
