### ISSUE TITLE
Consistently getting "bad magic: 0xC3D4" error when opening PCAP file

### ISSUE THREAD

**Issue by PedroM25** [phaag/nfdump#238]
Hello,
When I try to open any pcap file captured with Wireshark 3.2.3 (Git v3.2.3 packaged as 3.2.3-1) in nfdump v1.6.21 I always get the error "bad magic: 0xC3D4".
Due to privacy reasons I can not share the pcap file that gives me this error. But I don't think that is even relevant since every pcap file I tried, which was captured with Wireshark, always leads to "bad magic: 0xC3D4".

OS info:

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by bbayles** [comment]
You've likely got a `pcapng` file rather than a `pcap` file. See [here](https://stackoverflow.com/a/32533016/353839) for how to convert, then try `nfdump` again?

**Comment by PedroM25** [comment]
In order to test that out, I did another capture with Wireshark and saved it as  both "pcap" and "pcapng".
`sudo nfdump -r test.pcap -w test.nfd` results in `Open file 'test.pcap': bad magic: 0xC3D4`
`sudo nfdump -r test.pcapng -w test.nfd` results in `Open file 'test.pcapng': bad magic: 0xD0A`

**Comment by bbayles** [comment]
Ah, maybe it's endian-ness? From [here](https://web.archive.org/web/20200414231200/https://wiki.wireshark.org/Development/LibpcapFileFormat):
> magic_number: used to detect the file format itself and the byte ordering.
> The writing application writes 0xa1b2c3d4 with it's native byte ordering format into this field.
> The reading application will read either 0xa1b2c3d4 (identical) or 0xd4c3b2a1 (swapped).
> If the reading application reads the swapped 0xd4c3b2a1 value, it knows that all the following fields will have to be swapped too.
> For nanosecond-resolution files, the writing application writes 0xa1b23c4d, with the two nibbles of the two lower-order bytes swapped, and the reading application will read either 0xa1b23c4d (identical) or 0x4d3cb2a1 (swapped). 

Is the capturing machine's architecture different from the reading machine's? Perhaps you could do a capture of "nothing" (or a single packet) and post it - surely privacy could be maintained in this way.

**Comment by phaag** [comment]
Hi @PedroM25 ,
You try to open a pcap file with nfdump. This does not work! nfdump works only with nfdump format files, which are flow files. These are created by one of the nfdump collectors.
Please make yourself familiar with netflow in general and read also the short README here @github.
For a more detailed description see also https://www.first.org/resources/papers/conference2006/haag-peter-papers.pdf Chapter 1

**Comment by phaag** [comment]
If you want to convert a pcap into a nfdump format flow file, please use first nfpcap and then process the flow files.

**Comment by PedroM25** [comment]
You are totally right, this was my mistake but hopefuly this issue helps others in the future with the same "problem".
Thank you for the quick answer :)
