### ISSUE TITLE
nfcapd should not lost existing file when rotate

### ISSUE THREAD

**Issue by asy972** [phaag/nfdump#239]
Hello.

version 1.6.21

nfcapd should append existing file when rotate or current timestamp should be used in name of file at restart may be.
```
nfcapd.202008121200         │9379785│Aug 12 12:10
nfcapd.202008121210         │ 853367│Aug 12 12:20
nfcapd.202008121220         │9719795│Aug 12 12:30
```
nfcapd restarted about 12:18 and 2 minutes later nfcapd.current replaced existing nfcapd.202008121210.

**Comment by phaag** [comment]
I put this on the todo for 1.7.
