### ISSUE TITLE
Segmentation fault with 1.6.21

### ISSUE THREAD

**Issue by vklimovs** [phaag/nfdump#241]
nfcapd 1.6.21 fails with Segmentation fault error when writing out files (see strace log attached). The issue does not reproduce with 1.6.20 and appears to be fixed with https://github.com/phaag/nfdump/commit/f5ae2b821c22ebe0c96f3516d4e90f4255633828. I am filing this for posterity for those who might search for "Segmentation fault. 

`pulley ~ # strace /usr/bin/nfcapd -I cog -l /var/tmp/nfcapd/cog -e -p 60062 -R 192.168.2.2 60062
execve("/usr/bin/nfcapd", ["/usr/bin/nfcapd", "-I", "cog", "-l", "/var/tmp/nfcapd/cog", "-e", "-p", "60062", "-R", "192.168.2.2", "60062"], 0x7ffd450b9740 /* 27 vars */) = 0
brk(NULL)                               = 0x555afd0c1000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=39652, ...}) = 0
mmap(NULL, 39652, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f12a40be000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib64/libnfdump-1.6.21.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\213\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=228896, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f12a40bc000
mmap(NULL, 425560, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f12a4054000
mmap(0x7f12a405c000, 143360, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8000) = 0x7f12a405c000
mmap(0x7f12a407f000, 45056, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2b000) = 0x7f12a407f000
mmap(0x7f12a408a000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x35000) = 0x7f12a408a000
mmap(0x7f12a408d000, 192088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f12a408d000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`>\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1814752, ...}) = 0
mmap(NULL, 1827880, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f12a3e95000
mprotect(0x7f12a3eb7000, 1650688, PROT_NONE) = 0
mmap(0x7f12a3eb7000, 1343488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f12a3eb7000
mmap(0x7f12a3fff000, 303104, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16a000) = 0x7f12a3fff000
mmap(0x7f12a404a000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b4000) = 0x7f12a404a000
mmap(0x7f12a4050000, 13352, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f12a4050000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libbz2.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\"\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=74480, ...}) = 0
mmap(NULL, 76840, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f12a3e82000
mmap(0x7f12a3e84000, 53248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f12a3e84000
mmap(0x7f12a3e91000, 8192, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xf000) = 0x7f12a3e91000
mmap(0x7f12a3e93000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0x7f12a3e93000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f12a3e7f000
arch_prctl(ARCH_SET_FS, 0x7f12a3e7f740) = 0
mprotect(0x7f12a404a000, 16384, PROT_READ) = 0
mprotect(0x7f12a3e93000, 4096, PROT_READ) = 0
mprotect(0x7f12a408a000, 8192, PROT_READ) = 0
mprotect(0x555afb4b1000, 8192, PROT_READ) = 0
mprotect(0x7f12a40f2000, 4096, PROT_READ) = 0
munmap(0x7f12a40be000, 39652)           = 0
brk(NULL)                               = 0x555afd0c1000
brk(0x555afd0e2000)                     = 0x555afd0e2000
lstat("/var", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/var/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
lstat("/var/tmp/nfcapd", {st_mode=S_IFDIR|0700, st_size=60, ...}) = 0
lstat("/var/tmp/nfcapd/cog", {st_mode=S_IFDIR|0750, st_size=80, ...}) = 0
stat("/var/tmp/nfcapd/cog", {st_mode=S_IFDIR|0750, st_size=80, ...}) = 0
stat("/var/tmp/nfcapd/cog", {st_mode=S_IFDIR|0750, st_size=80, ...}) = 0
getpid()                                = 25963
mmap(NULL, 266240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f12a3e3e000
write(2, "Add extension: 2 byte input/outp"..., 51Add extension: 2 byte input/output interface index
) = 51
write(2, "Add extension: 4 byte input/outp"..., 51Add extension: 4 byte input/output interface index
) = 51
write(2, "Add extension: 2 byte src/dst AS"..., 40Add extension: 2 byte src/dst AS number
) = 40
write(2, "Add extension: 4 byte src/dst AS"..., 40Add extension: 4 byte src/dst AS number
) = 40
munmap(0x7f12a3e3e000, 266240)          = 0
socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) = 3
bind(3, {sa_family=AF_INET, sin_port=htons(60062), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
write(2, "Bound to IPv4 host/IP: any, Port"..., 40Bound to IPv4 host/IP: any, Port: 60062
) = 40
listen(3, 128)                          = -1 EOPNOTSUPP (Operation not supported)
socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) = 4
connect(4, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 0
close(4)                                = 0
socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) = 4
write(2, "Replay flows to host: 192.168.2."..., 45Replay flows to host: 192.168.2.2 port: 9995
) = 45
mmap(NULL, 4176, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f12a40c6000
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f12a3e7fa10) = 25964
Launcher: Startup. auto-expire enabled
write(2, "Launcher[25964] forked\n", 23Launcher[25964] forked
) = 23
getpid()                                = 25963
lstat("/var", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/var/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
lstat("/var/tmp/nfcapd", {st_mode=S_IFDIR|0700, st_size=60, ...}) = 0
lstat("/var/tmp/nfcapd/cog", {st_mode=S_IFDIR|0750, st_size=80, ...}) = 0
shmget(0x3a18e2bf, 64, 0600)            = 2
shmat(2, NULL, 0)                       = 0x7f12a40f1000
kill(14293, 0)                          = -1 ESRCH (No such process)
lstat("/var", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/var/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
lstat("/var/tmp/nfcapd", {st_mode=S_IFDIR|0700, st_size=60, ...}) = 0
lstat("/var/tmp/nfcapd/cog", {st_mode=S_IFDIR|0750, st_size=80, ...}) = 0
semget(0x6598c5ed, 1, IPC_CREAT|0600)   = 4
semctl(4, 0, SETVAL, 0x1)               = 0
rt_sigaction(SIGTERM, {sa_handler=0x555afb4957f0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f12a3ecde40}, NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x555afb4957f0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f12a3ecde40}, NULL, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=0x555afb4957f0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f12a3ecde40}, NULL, 8) = 0
rt_sigaction(SIGALRM, {sa_handler=0x555afb4957f0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f12a3ecde40}, NULL, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=0x555afb4957f0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f12a3ecde40}, NULL, 8) = 0
write(2, "Startup.\n", 9Startup.
)               = 9
mmap(NULL, 528384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f12a3dfe000
mmap(NULL, 397312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f12a3d9d000
write(2, "Init IPFIX: Max number of IPFIX "..., 41Init IPFIX: Max number of IPFIX tags: 68
) = 41
openat(AT_FDCWD, "/var/tmp/nfcapd/cog/nfcapd.current.25963", O_RDWR|O_CREAT|O_TRUNC, 0644) = 5
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f12a339c000
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f12a299b000
write(5, "\f\245\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 140) = 140
write(5, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 136) = 136
alarm(286)                              = 0
recvfrom(3, "\0\n\5w_B\327\271\0\0\1[\0\0\0\0\1\7\0\204\300\250\3\2\300\250\2\16\0\0\0\0"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [128->16]) = 1399
sendto(4, "\0\n\5w_B\327\271\0\0\1[\0\0\0\0\1\7\0\204\300\250\3\2\300\250\2\16\0\0\0\0"..., 1399, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 1399
write(2, "Process_ipfix: New exporter: Sys"..., 79Process_ipfix: New exporter: SysID: 1, Observation domain 0 from: 192.168.3.2

) = 79
recvfrom(3, "\0\n\4N_B\327\313\0\0\1p\0\0\0\0\1\3\0l\177\0\0\1\177\0\0\1\0\0\0\0"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [16]) = 1102
sendto(4, "\0\n\4N_B\327\313\0\0\1p\0\0\0\0\1\3\0l\177\0\0\1\177\0\0\1\0\0\0\0"..., 1102, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 1102
write(2, "Process_ipfix: [0] Add template "..., 36Process_ipfix: [0] Add template 265
) = 36
recvfrom(3, "\0\n\5,_B\330\7\0\0\1\201\0\0\0\0\1\7\0\304\300\250\0\1\300\250\3\2\0\0\0\0"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [16]) = 1324
sendto(4, "\0\n\5,_B\330\7\0\0\1\201\0\0\0\0\1\7\0\304\300\250\0\1\300\250\3\2\0\0\0\0"..., 1324, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 1324
recvfrom(3, "\0\n\5m_B\3305\0\0\1\225\0\0\0\0\1\7\0\204\300\250\3\2\300\250\1j\0\0\0\0"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [16]) = 1389
sendto(4, "\0\n\5m_B\3305\0\0\1\225\0\0\0\0\1\7\0\204\300\250\3\2\300\250\1j\0\0\0\0"..., 1389, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 1389
recvfrom(3, "\0\n\1\10_B\330C\0\0\1\253\0\0\0\0\1\7\0D\300\250\3\2\300\250\1j\0\0\0\0"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [16]) = 264
sendto(4, "\0\n\1\10_B\330C\0\0\1\253\0\0\0\0\1\7\0D\300\250\3\2\300\250\1j\0\0\0\0"..., 264, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 264
recvfrom(3, "\0\n\5\210_B\330\177\0\0\1\257\0\0\0\0\1\7\0\204\300\250\3\2\300\250\1j\0\0\0\0"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [16]) = 1416
sendto(4, "\0\n\5\210_B\330\177\0\0\1\257\0\0\0\0\1\7\0\204\300\250\3\2\300\250\1j\0\0\0\0"..., 1416, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 1416
recvfrom(3, "\0\n\2^_B\330\257\0\0\1\305\0\0\0\0\1\7\1@\300\250\3\2\300\250\1j\0\0\0\0"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [16]) = 606
sendto(4, "\0\n\2^_B\330\257\0\0\1\305\0\0\0\0\1\7\1@\300\250\3\2\300\250\1j\0\0\0\0"..., 606, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 606
recvfrom(3, "\0\n\2\20_B\330\273\0\0\1\316\0\0\0\0\1\7\0\204\300\250\0\1\300\250\3\2\0\0\0\0"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [16]) = 528
sendto(4, "\0\n\2\20_B\330\273\0\0\1\316\0\0\0\0\1\7\0\204\300\250\0\1\300\250\3\2\0\0\0\0"..., 528, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 528
recvfrom(3, "\0\n\08_B\330\273\0\0\1\325\0\0\0\0\1\n\0(\0\0\0\0\0\0\0\0\0\0\0\32"..., 65535, 0, {sa_family=AF_INET, sin_port=htons(39604), sin_addr=inet_addr("192.168.3.2")}, [16]) = 56
sendto(4, "\0\n\08_B\330\273\0\0\1\325\0\0\0\0\1\n\0(\0\0\0\0\0\0\0\0\0\0\0\32"..., 56, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = 56
recvfrom(3, 0x555afd0c2790, 65535, 0, 0x7ffc0e781200, [16]) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
sendto(4, "\0\n\08_B\330\273\0\0\1\325\0\0\0\0\1\n\0(\0\0\0\0\0\0\0\0\0\0\0\32"..., 18446744073709551615, 0, {sa_family=AF_INET, sin_port=htons(9995), sin_addr=inet_addr("192.168.2.2")}, 16) = -1 EMSGSIZE (Message too long)
write(2, "ERROR: sendto(): Message too lon"..., 34ERROR: sendto(): Message too long
) = 34
alarm(0)                                = 0
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=2836, ...}) = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=2836, ...}) = 0
read(6, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 2836
lseek(6, -1802, SEEK_CUR)               = 1034
read(6, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 1802
close(6)                                = 0
write(5, "\5\0\0\0\340\0\0\0\2\0\0\0\7\0 \0\n\0\0\0\0\0\0\0\0\0\0\0\2\3\250\300"..., 236) = 236
write(5, "\1\0\0\0 \0\0\0\2\0\0\0\10\0 \0\1\0\0\0\1\0\0\0\3\0\0\0\232\264\0\0"..., 44) = 44
lseek(5, 0, SEEK_SET)                   = 0
write(5, "\f\245\1\0\0\0\0\0\2\0\0\0cog\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 140) = 140
write(5, "\3\0\0\0\0\0\0\0p\233\0\0\0\0\0\0|\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 136) = 136
close(5)                                = 0
rename("/var/tmp/nfcapd/cog/nfcapd.current.25963", "/var/tmp/nfcapd/cog/nfcapd.202008231355") = 0
stat("/var/tmp/nfcapd/cog/nfcapd.202008231355", {st_mode=S_IFREG|0644, st_size=556, ...}) = 0
semtimedop(4, [{0, -1, 0}], 1, NULL)    = 0
semtimedop(4, [{0, 1, 0}], 1, NULL)     = 0
write(2, "Ident: 'cog' Flows: 3, Packets: "..., 86Ident: 'cog' Flows: 3, Packets: 380, Bytes: 39792, Sequence Errors: 7, Bad Packets: 0
) = 86
openat(AT_FDCWD, "/var/tmp/nfcapd/cog/nfcapd.current.25963", O_RDWR|O_CREAT|O_TRUNC, 0644) = 5
write(5, "\f\245\1\0\0\0\0\0\0\0\0\0cog\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 140) = 140
write(5, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 136) = 136
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x11} ---
+++ killed by SIGSEGV +++
Segmentation fault`

**Comment by phaag** [comment]
Thx. Indeed in certain condition, this could have resulted in a seg fault. It's fixed in the patch you mentioned.
