### ISSUE TITLE
Do we have a way to identofy the Netflow Version Automatically, when we read using nfdump?

### ISSUE THREAD

**Issue by tarungoswami** [phaag/nfdump#242]
Is there a way I can read Netflow Version Automatically, when we read using nfdump? Its anyway available as part of detail sent by the router
![image](https://user-images.githubusercontent.com/50728472/91001234-0f855080-e5c3-11ea-9c25-d024c4d233f2.png)

**Comment by phaag** [comment]
Can you elaborate your needs here? When reading netflow with nfcapd it's automatically read, regardless the version. The version is not store in the nfdump file.

**Comment by tarungoswami** [comment]
Hello Peter,

Since I have multiple routers, some sending on v5, some on v9 and some on v10/IPFIX, I need to know on what versions the routers are sending the data.
So can you include the version number as part of the nfdump data?


Thanks & Regards
Tarun Kumar Goswami

**Comment by phaag** [comment]
Added in `a766080`

**Comment by tarungoswami** [comment]
Did not get you, can u pls elaborate, what do you mean when u say : “Added in a766080”

Thanks & Regards
Tarun Kumar Goswami

**Comment by phaag** [comment]
That's the patch number in the repo. The feature has beed added in the master repo

**Comment by tarungoswami** [comment]
Thanks for your quick turnaround. Can you please help me with how exactly will we get the netflow version via nfdump. I mean which command, options

**Comment by phaag** [comment]
You do not need anything. When collecting flow data it's added by default. Make sure to start the new collector. Check your flows with -o raw for example, you see the netflow version at the top. For other output formats and for filtering, see nfdump(1)
