### ISSUE TITLE
Multiple nfcapd files in CSV

### ISSUE THREAD

**Issue by newscriptkid** [phaag/nfdump#245]
Hi,

I am new with nfcapd, i configured HP switches with sflow and ubuntu machine with nfcapd. I can see loads of nfcapd files.

How can i convert all the nfcapd files into 1 CSV?

I tried 'nfdump -r nfcapd.2020*  > output.csv'

But it doesnt convert anything, when I do an individual file it converts fine.

Also is there a cheat sheet to follow to get outputs like top talkers using data from all files.

Lastly is there a way to get a graphical user interface so can use filtering commands via GUI?

Many Thanks

**Comment by phaag** [comment]
nfcapd/nfdump files are organised in directories. See nfcapd(1) -S option. To process a bunch of files in such a directory use `nfdump -R <dir>`. Furthermore see nfdump(1) for the output format and how to get csv files.
