### ISSUE TITLE
Selecting Multiple "nip" or "xip" Without "OR"

### ISSUE THREAD

**Issue by ab1168** [phaag/nfdump#246]
Hello,
I'm Trying to filter Rows By Source And Destination "IP" AND "NAT IP"  Using Nfdump. And There Is No Problem Until I Tried Filter Nat IPs (nip).
To select NAT IPs, The Filter Statement  I'm Using is Like:
`((dst nip 192.168.1.1) or (dst nip 192.168.2.1)) `
That is Working BUT its Very Slow and Costy in high Number Of Rows.

While Selecting Normal IPs Using "in" Operator Is Very Fast. 
`(dst ip in [192.168.1.1,192.168.2.1])`

Why There Is No Way To Filter "NAT IPs" Using "in" Operator ?? Or May Be There Is But I Dont Know.

Please Help Me If There Is Any Way To Filter "dst nip" in a Faster Way.
Thank you.

**Comment by phaag** [comment]
Because it has not been implemented so far. There was no need for that so far.

**Comment by phaag** [comment]
Implemented in current master repo.
