### ISSUE TITLE
ICMPv6 element parsing

### ISSUE THREAD

**Issue by brownej** [phaag/nfdump#250]
nfcapd will not decode ICMPv6 type and code fields from element entity 139. Junos uses this type code. I have confirmed this in version 1.6.13 and I don't see any issue or resolved bug. I have attached a copy of the Juniper data template for IPv6 ipfix export.

[junos-ipfix-template-v6.txt](https://github.com/phaag/nfdump/files/5308323/junos-ipfix-template-v6.txt)

**Comment by phaag** [comment]
nfdump-1.6.13 did not support element 139. Therefore I am not sure, what you mean.
I add element 139 for ICMP type/code IPv6

**Comment by brownej** [comment]
Thank you! I'll check out this commit and see how it works.
