### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Leax81** [phaag/nfdump#251]
Hi
During make nfdump v 1.6.21 i get this error:

make  all-am
make[3]: Entering directory `/root/ipt-netflow/nfdump/bin'
depbase=`echo output_util.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -ggdb  -g -O3 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -MT output_util.lo -MD -MP -MF $depbase.Tpo -c -o output_util.lo output_util.c &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -ggdb -g -O3 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -MT output_util.lo -MD -MP -MF .deps/output_util.Tpo -c output_util.c  -fPIC -DPIC -o .libs/output_util.o
output_util.c: In function ‘ProtoNum’:
output_util.c:207: error: ‘for’ loop initial declarations are only allowed in C99 mode
output_util.c:207: note: use option -std=c99 or -std=gnu99 to compile your code
make[3]: *** [output_util.lo] Error 1
make[3]: Leaving directory `/root/ipt-netflow/nfdump/bin'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/root/ipt-netflow/nfdump/bin'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/ipt-netflow/nfdump'
make: *** [all] Error 2

How can i fix it? Whot should i do? Thanks for help

**Comment by phaag** [comment]
you need to run configure, which checks for proper compiler option -std=c11 or -std=gnu11. Linux'es BSDs and OSX can proper handle this. Your make output does not include this compiler option.
