### ISSUE TITLE
Converting old netflow records to newer version

### ISSUE THREAD

**Issue by agllno** [phaag/nfdump#261]
Hi ,

I am new to netflow, for my analysis i obtained a very old data set from public domain, when I use the nfdump to read the file I get following error "Old common v0 records no longer supported - skipped" for every record captured.

I understand this is a compatibility issue, is there any way to make old record compatible with newer version, or which exact version I have to use to read these files.

Thanks in advance
Agnello

**Comment by phaag** [comment]
[nfdump-1.6.17-conv.zip](https://github.com/phaag/nfdump/files/5579789/nfdump-1.6.17-conv.zip)

Find appended a special crafted version of nfdump, based on nfdump-1.6.17.

Compile the appended version of 1.6.17 and convert all your files ( -r .. -w .. )
Thereafter you should be able to read the files with the latest nfdump version without any problems.

**Comment by agllno** [comment]
Thanks Peter,

It worked perfectly
