### ISSUE TITLE
timestamps on IPFIX from IOS-XR

### ISSUE THREAD

**Issue by praines** [phaag/nfdump#264]
All,

I am trying to resolve the 1970-01-01 timestamp issue with IOS-XR and zero duration flows. 

ubuntu@vw-vta-iperf-s-2-8-1:/dev/shm/logs/amsncs02-ie$ nfdump -a -o "fmt:%ts %td %pr %sap -> %dap %flg %tos %pkt 
Date first seen                    Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Flags Tos  Packets    Bytes Flows
1970-01-01  00:00:00.000     0.000    TCP     140.222.254.52:48580 ->       80.157.0.2:179   ...... 192        1       68     1
1970-01-01  00:00:00.000     0.000    TCP     2011:20..f::4a02.54739 -> 2600:40..:154:47.179   ...... 192        1      100     1

The intent is too include Element 160. Want to confirm with nfdump that is if we plan to put element 160 into a option template; not in data flow records, that will that address this?

**Comment by mikej96** [comment]
We are having this issue as well with IOS-XR.  I confirmed using wireshark that element 160 is not part present in the ipfix template that Cisco is sending. Is there a way to force it to send element 160?

**Comment by phaag** [comment]
I'd happily would include Element 160, if we have valid samples to verify. Therefore you need to talk to Cisco first.

**Comment by praines** [comment]
I am trying to confirm if Cisco put element 160 into a option template, not in data flow record will that resolve this for nfdump?

**Comment by phaag** [comment]
currently Element 160 is not implemented. As soon one knows when and how it is sent I can integrate that

**Comment by phaag** [comment]
Element 160 IPFIX_SystemInitTimeMiliseconds is integrated and should work.
