### ISSUE TITLE
sfcapd corrupts sflow version

### ISSUE THREAD

**Issue by ale91x** [phaag/nfdump#265]
The sfsapd daemon corrupts the sflow version, making it impossible to forward.

nfdump -E /tmp/sflow/nfcapd.202012151334
Exporters:
SysID: 1, IP:    192.168.1.219, version: 9999, ID:  1, Sequence failures: 0, packets: 113, flows: 113
        Sampler for Exporter SysID: 1,  Generic Sampler: mode: 0, interval: 8192

Mr P.Haag, I sent the files for analysis to the mail.

**Comment by phaag** [comment]
Current the sflow version is not properly stored, however this can be fixed. Forwarding sflow using the built-in forwarder in sflowd is not affected by this. nfreplay does not forward sflow anyway.

**Comment by ale91x** [comment]
Thanks Peter, are there plans to implement a sfreplay, similarly nfreplay?
This would be pretty cool for filtering and forwarding sflow.

**Comment by phaag** [comment]
I need to check how complicated it is.

**Comment by phaag** [comment]
sflow records are now properly marked with the version. So far there will be no sfreplay. However, sflow stored data may also be replayed with nfreplay.
