### ISSUE TITLE
IPFIX Corrupt data file. Inconsistent block size

### ISSUE THREAD

**Issue by megamaced** [phaag/nfdump#266]
Hi, I am capturing IPFIX data from several Sophos UTM like this:

```
/usr/bin/nfcapd \
 -n utm01,172.17.254.252,/var/nfdump/profiles-data/live/utm01 \
 -n utm02,172.17.253.250,/var/nfdump/profiles-data/live/utm02 \
 -w -e -E -p 4739 -T all -B 128000 -S 1 -z
```

When I try to query it using nfdump I get this error:

```
/usr/bin/nfdump -M '/var/nfdump/profiles-data/live/utm01' -R '2021/01/06/nfcapd.202101061415:2021/01/06/nfcapd.202101061420' -c '10' -o 'csv' 'host 8.8.8.8'
Corrupt data file. Inconsistent block size in nfdump.c line 478

ts,te,td,sa,da,sp,dp,pr,flg,fwd,stos,ipkt,ibyt,opkt,obyt,in,out,sas,das,smk,dmk,dtos,dir,nh,nhb,svln,dvln,ismc,odmc,idmc,osmc,mpls1,mpls2,mpls3,mpls4,mpls5,mpls6,mpls7,mpls8,mpls9,mpls10,cl,sl,al,ra,eng,exid,tr
```

Thanks

**Comment by phaag** [comment]
Hmm .. do you have inconsistent versions on nfcapd and nfdump? This is a data format error and has nothing to do with IPFIX.
Can you try to update to the latest master with all nf* tools?

**Comment by megamaced** [comment]
hi, I just used the packaged version from my distro:

```
zypper se --details --installed-only nfdump
Loading repository data...
Reading installed packages...

S  | Name   | Type    | Version          | Arch   | Repository
---+--------+---------+------------------+--------+----------------------------
i+ | nfdump | package | 1.6.20-lp152.1.3 | x86_64 | openSUSE Leap 15.2 (x86_64)
```

The nfdump opensuse rpm package provides nfdump and nfcapd

```
nfcapd -V
nfcapd: Version: 1.6.20

nfdump -V
nfdump: Version: NSEL-NEL1.6.20
```

**Comment by phaag** [comment]
There is no know issue regarding block size error with 1.6.20. I tested again your explicit case and I can not reproduce that error. Maybe you could try to compile the latest master and check again.

**Comment by phaag** [comment]
btw. by running without -D but -E you leave nfcapd in foreground. You should see captured flows in raw output format. This is only recommended while debugging, but has no influence of this error. 
You may send me an nfcapd flow file off list - so I could check it.
A few checks: 
you can also run ./nfdump -v <file> in order to fsck the consistence. Are all files corrupted or just some?
Did you cleanly teminate nfcapd?

**Comment by phaag** [comment]
Any news on that point? Otherwise I close this issue

**Comment by megamaced** [comment]
hi IIRC this was resolved by using the latest version cheers
