### ISSUE TITLE
Duration filter result with inconsitanat output

### ISSUE THREAD

**Issue by abs0248** [phaag/nfdump#269]
Hello all,
I tried to filter based on duration of a flow that it take 8000 second from start/stop and i can see that specific flow recorded correctly .the filter i tried is simple `duration > 8000` and the output (both with Aggregation and not aggregation) show inconstant result.i can see others flows that duration is less than 800 and other flows that the duration is greater than 8000 second too. the same behavior is also with other filter types like Bytes,Packets and flows.any idea what i am missing ?  i tried many arguments with no success.

**Comment by phaag** [comment]
The file duration specifies Miliseconds - not seconds. So duration > 8000 means everything > 8s

**Comment by abs0248** [comment]
Thanks for the response.i knew that the time is in ms and that was my typo . i find that the duration filter is working with IOS-XE and the problem is with NX-OS .it look like something is wrong with the NX-OS and the duration filter show not honored.
