### ISSUE TITLE
Cannot compile latest release on Ubuntu 16.04

### ISSUE THREAD

**Issue by zerocarbthirty** [phaag/nfdump#270]
Hello,

I am having trouble compiling the latest release on Ubuntu 16.04, while running ./configure it merely says:

checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
./configure: line 12662: syntax error near unexpected token `curl,'
./configure: line 12662: `      PKG_CHECK_MODULES(curl, libcurl,,'

user@ster:~/nfdump-1.6.22# apt list --installed | grep curl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

curl/xenial-updates,xenial-security,now 7.47.0-1ubuntu2.18 amd64 [installed]
libcurl3/xenial-updates,xenial-security,now 7.47.0-1ubuntu2.18 amd64 [installed]
libcurl3-gnutls/xenial-updates,xenial-security,now 7.47.0-1ubuntu2.18 amd64 [installed]
libcurl4-openssl-dev/xenial-updates,xenial-security,now 7.47.0-1ubuntu2.18 amd64 [installed]
libcurlpp-dev/xenial,now 0.7.3-6 amd64 [installed]
libcurlpp0/xenial,now 0.7.3-6 amd64 [installed,automatic]
python3-pycurl/xenial,now 7.43.0-1ubuntu1 amd64 [installed]

Any clue what package includes whatever PKG_CHECK is looking for?

**Comment by phaag** [comment]
What arguments did you supply to configure?
Make sure you have properly run 'sh bootstrap' in case of you move from another system
