### ISSUE TITLE
Reading the "current" nfcapd file doesn't do anything

### ISSUE THREAD

**Issue by luminous706** [phaag/nfdump#272]
Hello,

I'm trying to read the "nfcapd.current.$PID" file as follows:

`nfdump -r /data/nfcapd.current.21981`

But there is no output, but it seems that it gets rotated properly and when I read the files in the directory tree, the flows are there.

Can you explain why the "current" nfcapd file doesn't behave like the others?

Thank you!

**Comment by phaag** [comment]
The .current. file is the current nfcapd file, where incoming flow data gets stored. It is not meant to read this file directly, as you may get unexpected results. Data is buffered and written to disc in chunks. Therefore with little packets, you don't see anything.
