### ISSUE TITLE
Problem with bison on FreeBSD 13

### ISSUE THREAD

**Issue by borjam** [phaag/nfdump#276]
I've tried building 1.6.23 from source and there is some bison conflict.

`borjam@micro1:~/src/nfdump-1.6.22 % make
make  all-recursive
Making all in .
Making all in bin
/bin/sh ../ylwrap grammar.y y.tab.c grammar.c y.tab.h `echo grammar.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/  -e s/c++$/h++/ -e s/c$/h/` y.output grammar.output -- bison -o y.tab.c -d 
/home/borjam/src/nfdump-1.6.22/bin/grammar.y: warning: 1 shift/reduce conflict [

`

Deleting bison and using the builting byacc instead it seems to work.

Bison is version bison-3.7.5

**Comment by phaag** [comment]
This is a bison warning. It occurs also on other platforms and can be ignored. Newer bison are more picky..

**Comment by borjam** [comment]
> On 12 Mar 2021, at 08:38, Peter Haag ***@***.***> wrote:
> 
> 
> This is a bison warning. It occurs also on other platforms and can be ignored. Newer bison are more picky..

Odd, bison kinda crashed. It even left my terminal configured with odd coors.





Borja.

**Comment by borjam** [comment]
Not your fault, but commenting just in case. 

There is a bug in the new ncurses 9 library, it seems, that can be triggered when bison is installed with NLS support and colorization is enabled (which is by default).

So, if you are building stuff from ports make sure to disable NLS support for bison. Otherwise bison will crash on warnings. 

Alternatively, if you set YFLAGS to "--color=never" before running configure, it will disable colorization on bison hence avoiding the problem.

Isn't it beautiful? ;)
