### ISSUE TITLE
Running 'nfcapd -x' but using nfsen.conf

### ISSUE THREAD

**Issue by giveen** [phaag/nfdump#279]
We currently have our sensor capture using nfsen.conf file but I want to recompress a file after the end of an interval by using '-J 2'. It appears the 'nfcapd -x' lets you run a command at the end of an interval, but I can't figure out how to implement this while using a config file.

Is there anyway to do this within the config file? Or am I stuck doing it by hand?

**Comment by phaag** [comment]
actually you can use 'optarg':
'peer2'        => { 'port' => '9996', 'IP' => '172.16.17.19' , 'optarg' => ....},
But be aware, this confuses NfSen's bookkeeping and expiring does no long work correctly, if you expect NfSen to expire your files. Furthermore, it breaks profiles, as the profiler is run at the end of an interval. It may not see the correct file.

**Comment by giveen** [comment]
Thank you @phaag I ended up setting up a cron job that looked for the previous days files and then recompressed them
