### ISSUE TITLE
Common V0 records

### ISSUE THREAD

**Issue by josecamachop** [phaag/nfdump#280]
We have a long capture for network security at:

https://nesg.ugr.es/nesg-ugr16/

When we try to analyze this trace with the last version, it would not analyze the files and output the following message a million times:

"Old common v0 records no longer supported - skipped"

We could not find any docummentation about potential solutions to this problem, or an explanation. If this is the intended behaviour of the software, some docummentation will surely be helpful.

**Comment by phaag** [comment]
This refers to the issue #261 and a solution is given there.  https://github.com/phaag/nfdump/issues/261
The v0 record is an over 10years old legacy record. I am surprised, that still that old files exist. 
It's strongly advised  to convert these old file to the new format. 
But an FAQ is a good idea anyway.

**Comment by josecamachop** [comment]
Thanks a bunch. I am surprised too, since we did the collection in 2016, but I did not configure it so I don't know the details.

**Comment by phaag** [comment]
Maybe the collection was created with older versions. Anyway, I am glad, it helped.

**Comment by josecamachop** [comment]
It did. Thanks
