### ISSUE TITLE
Error in nfcapd manpage : Incorrect description for -E

### ISSUE THREAD

**Issue by borjam** [phaag/nfdump#281]
According to the nfcapd man page, -E causes flow data to be sent in raw nfdump format to stdout. 

Actualy nfcapd activates verbose mode and dumps flow data in ASCII.

Pity, I was intending to set up a filtered netflow forwarding using a simple pipe with nfcapd and nfreplay.

An option to do actually this would be great, by the way.

**Comment by phaag** [comment]
This refers to the 'raw' output format and not 'raw' record format. Therefore the description is actually correct.Raw netflow packet format to stdout does not make sense. To filter flows to be forwarded, apply a filter to nfreplay.
