### ISSUE TITLE
Fatal error running nfpcapd

### ISSUE THREAD

**Issue by tarunmangla** [phaag/nfdump#285]
I am running nfpcapd on a 23G pcap file. The program runs for a while but then gives the following error: `Free_Node() Fatal: Tried to free a Node not in use` and aborts.

It runs fine on small pcaps though. Is it a memory issue? I tried changing timeouts and cache node size.

**Comment by phaag** [comment]
I suspect, it's not a question of the size of the pcap, therefore timeout wont change the fact.
I fixed a potential bug in the current master branch. Could you try to run the master branch?

**Comment by tarunmangla** [comment]
It worked. Thanks!
