### ISSUE TITLE
nfdump stable latest version does not collect AS numbers

### ISSUE THREAD

**Issue by hendranata** [phaag/nfdump#286]
helo
i have installed in centos7:
nfdump-1.6.22
nfsen-1.3.8
FlowDoh_1.0.2

the problem once installing complete, live profile is working normal. but when i create a new profile with fiter: as 32934
it show empty..

any idea? sorry i am new in nfdump and nfsen.. 
i have adjust the timezone as well and do restart.

but seems the issue still remain persist

**Comment by hendranata** [comment]
sorry it seems the filter does not working with AS number..
do we need to install any plugin so that the nfdump can collect AS number..?

**Comment by phaag** [comment]
AS number need be sent from an exporter with BGP information. Otherwise your AS numbers are 0. It is not a question of nfdump or filters but the exporterting router.
