### ISSUE TITLE
Discrepancy in netflow volume compared to pcap

### ISSUE THREAD

**Issue by tarunmangla** [phaag/nfdump#287]
Hi, I am analyzing a pcap which is about 23 GB. I get csv with flow stats. However, the total volume (uplink+downlink) from the flow stats is only about half of the pcap size. Interestingly, the stats seem to be missing a lot of UDP traffic from the pcap.  Note that while parsing the pcap using nfpcapd, I get a lot of `UDP Payload length error` messages. Do you think it is an issue with my pcap or the parser? Thanks!

**Comment by phaag** [comment]
How did you collect the pcap? Did you apply a small snaplen?

**Comment by phaag** [comment]
If you apply a snaplen, what number of bytes would you expect - simply what's in the pcap, or what originally was on the wire?

**Comment by phaag** [comment]
Please note, that ARP requests and other non IP traffic is skipped. If you have lots of these length errors, it would help, if you could send me a pcap with a couple of 1000 packets in order to reproduce the error. You may send it to the email in the AUTHORS file.
