### ISSUE TITLE
sfcapd crash

### ISSUE THREAD

**Issue by rnalrd** [phaag/nfdump#29]
I have nfdump-1.6.14 and I'm capturing sflow v5 data from a DELL PowerConnect switch. Sfcapd crashes after few minutes after it has been started. Please see backtrace below.
Thanks

`GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/sfcapd...Reading symbols from /usr/lib/debug//usr/bin/sfcapd.debug...done.
done.
[New LWP 1685]

warning: Can't read pathname for load map: No error information.
Core was generated by '/usr/bin/sfcapd -w -e -z -I B044 -l /var/log/sfcapd -S 1 -T all -t 3600 -B 1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000078317da78ec in getData32 (sample=sample@entry=0x71028e90ed10) at sflow.c:1336

1336    sflow.c: No such file or directory.
(gdb) bt
#0  0x0000078317da78ec in getData32 (sample=sample@entry=0x71028e90ed10) at sflow.c:1336
#1  0x0000078317daa5b8 in readSFlowDatagram (fs=0x6167d5d6de60, sample=0x71028e90ed10) at sflow.c:2487
#2  Process_sflow (in_buff=<optimized out>, in_buff_cnt=<optimized out>, fs=0x6167d5d6de60) at sflow.c:2743
#3  0x0000078317da7168 in run (receive_packet=<optimized out>, report_seq=<optimized out>, do_xstat=<optimized out>, compress=1, time_extension=0x78317dafcda "%Y%m%d%H%M", use_subdirs=1, t_begin=<optimized out>, twin=3600, peer=...,

```
socket=3) at sfcapd.c:642
```
#4  main (argc=<optimized out>, argv=<optimized out>) at sfcapd.c:1092

(gdb) quit`

**Comment by phaag** [comment]
sflow code updated to commit 7322984 of https://github.com/sflow/sflowtool
Please check, if there are still problems

**Comment by phaag** [comment]
I hope the new sflow code solved the problem. I you still have core dumps feel free to reopen the ticket.
