### ISSUE TITLE
Convert PCAP file into Netflow (NFDUMP)

### ISSUE THREAD

**Issue by minhanh1234** [phaag/nfdump#291]
I am looking to convert existing PCAP file into a Netflow (NFDUMP) file.
I try to use nfpcapd but it doesn't seem like it is converting the pcap file to a netflow type of file.

"Convert pcaps to nflow by running"	
nfpcapd -r path_to_pcap_file; -l output_directory

Any advice?

**Comment by phaag** [comment]
This command does not work due to the ';' which separates two different shell commands. You need:

nfpcapd -r path.. -l output .. -y

Hope this helps.
