### ISSUE TITLE
Incorrect formatting of timestamp milliseconds in JSON output

### ISSUE THREAD

**Issue by simon-cert** [phaag/nfdump#294]
The millisecond part of the timestamp is formatted incorrectly in the JSON output. If the millisecond part is less than 100, it will result in an incorrect output as follows:

```
expected: 1970-01-01T12:34:56.007
actual:   1970-01-01T12:34:56.7
```

As far as I can tell, this issue exists in both the stable and 1.7 branches and affects the formatting of all three timestamps (first, last, received):

https://github.com/phaag/nfdump/blob/adefae06fcc06a7ccd9f44086c18f119443d47cb/bin/output_json.c#L102
https://github.com/phaag/nfdump/blob/19ddf1b694ef3dde9e6df6cb819af8fefaaee448/src/output_json.c#L78

Adding padding along the lines of `%03u` instead of `%u` should remediate the issue.

**Comment by phaag** [comment]
Many thanks for the reporting. Fixed in master repo.
