### ISSUE TITLE
Using -o json together with -q outputs broken json

### ISSUE THREAD

**Issue by liskaant** [phaag/nfdump#296]
When using quiet mode together with JSON output format the beginning `[` is not printed.

As far as I can tell it is caused by the `json_prolog` function not being called in quiet mode:
https://github.com/phaag/nfdump/blob/1f612770ac52cbd481b541e69fef6151dd17c51f/bin/output_json.c#L79-L83
https://github.com/phaag/nfdump/blob/1f612770ac52cbd481b541e69fef6151dd17c51f/bin/nfdump.c#L1129-L1131

The `recordCount` and `memset` lines not being called might also cause issues with unitialized variables.

**Comment by phaag** [comment]
Thanks for the report.
Fix in commit 5850f57.
