### ISSUE TITLE
Add managing of nfcapd rotate interval option (-t) via nfsen config

### ISSUE THREAD

**Issue by kobaandrii** [phaag/nfdump#297]
Good day!

We use nfdump+nfsen for collecting jflow dumps. And we'd like rotating nfcapd files more often then every 300s.
As I understand it's no way to specify rotate nfcapd files every minute via nfsen. This possibility was added in 2019. 
Nfsen version is 1.3.8, 2017.
Is it possible to add option to Nfsen for configuring nfcapd rotate interval?

Regards

**Comment by phaag** [comment]
By default NfSen uses 300s (5m) for each cycle. You can reduce this by setting  `$CYCLETIME  = 300;`  in NfSen.conf. You should not go lower than 60.
