### ISSUE TITLE
Nfdump IPFIX missing Nat Event Column (Question)

### ISSUE THREAD

**Issue by cbahcevan** [phaag/nfdump#298]
Hi,
 
I am trying to see nat event column on nfcapd files.  But every format command I used like nfdump -o raw,  long I could not see it. We know that the file format is pcap and there is a nat event column.
 
''a"    => { 'port' => '9998', 'IP' => '10.1.1.1', 'col' => '#0000ff', 'type' => 'netflow', 'optarg' => '-T all' },
 
I set the nfsen.conf to optargs -T all which includes all columns. Still I cannot see natevent column. How can i solve this issue?

**Comment by phaag** [comment]
Event records (NAT/NSEL) are not supported in IPFIX, only in netflow v9. If IPFIX is required, I need pcaps and some references to integrate this in IPFIX

**Comment by cbahcevan** [comment]
Hi,

Thank you for your response and your interest. I can share the pcaps as a mail, but even if pcaps are anonymous, publicly sharing seems inappropriate. Wireshark screenshot of pcap is below

![image](https://user-images.githubusercontent.com/14240595/126479699-8e2ca34b-17dd-4ea1-97b7-d496a53ece23.png)

**Comment by phaag** [comment]
Thanks - I perfectly understand your concern. Feel free to send me off list whatever you think is possible. You may use the email address in the AUTHORS file.
Having real pap helps a lot to implement and test.

**Comment by phaag** [comment]
NAT support is added in commit cbb4c13. Please check and verify.
Thanks!

**Comment by cbahcevan** [comment]
I checked it and it's working perfectly in the server with actual packets. Thanks for the development.
