### ISSUE TITLE
nfcapd startup problem under CentOS 7.2

### ISSUE THREAD

**Issue by Korxif** [phaag/nfdump#30]
All this setup perfectly works under CentOS 6.x.
Problems began when we decided to migrate to CentOS 7.2.

CentOS Linux release 7.2.1511 (Core) 
Linux flows 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

We have different sources, so we use shell-script to start all procesess:
nfcapd-start.sh:
#!/bin/sh
#start netflow-6500
/usr/local/bin/nfcapd -P /var/run/nfcapd/nfcapd-netflow-6500.pid -w -D -b x.x.x.x -p 3000 -S 7 -t 180 -z -l /mnt/array0/netflow/nfcapd-netflow-6500 -I cat6509 -x '/usr/local/adm/analyze.sh %i %d/%f'

#office
/usr/local/bin/nfcapd -P /var/run/nfcapd/nfcapd-netflow-office.pid -w -D -b x.x.x.x -p 3001 -S 7 -t 180 -z -l /mnt/array0/netflow/nfcapd-netflow-office 

#cisco 7206
/usr/local/bin/nfcapd -P /var/run/nfcapd/nfcapd-netflow-7206.pid -w -D -b x.x.x.x -p 3010 -S 7 -t 180 -R 127.0.0.1/3210 -z -l /mnt/array0/netflow/nfcapd-netflow-7206
/usr/local/flow-tools/bin/flow-fanout 127.0.0.1/0/3210 0/127.0.0.1/3310 -f /tmp/filter.flow -F xxx
/usr/local/bin/nfcapd -P /var/run/nfcapd/nfcapd-netflow-7206-b2b.pid -w -D -b 127.0.0.1 -p 3310 -S 7 -t 180 -z -l /mnt/array0/netflow/nfcapd-netflow-7206-b2b

flow-fanout used to separate b2b traffic from all flow.

here we go:
root     22703  0.0  0.0  22364  2628 ?        S    Jul11   0:00 /usr/local/bin/nfcapd -P /var/run/nfcapd/nfcapd-netflow-6500.pid -w -D -b 77.50.0.16 -p 3000 -S 7 -t 180 -z -l /mnt/array0/netflow/nfcapd-netflow-6500 -I cat6509 -x /usr/local/adm/analyze.sh %i %d/%f
root     22704  0.0  0.0  11080   580 ?        S    Jul11   0:00 /usr/local/bin/nfcapd -P /var/run/nfcapd/nfcapd-netflow-6500.pid -w -D -b 77.50.0.16 -p 3000 -S 7 -t 180 -z -l /mnt/array0/netflow/nfcapd-netflow-6500 -I cat6509 -x /usr/local/adm/analyze.sh %i %d/%f
root     22707  0.0  0.0  22360  2648 ?        S    Jul11   0:00 /usr/local/bin/nfcapd -P /var/run/nfcapd/nfcapd-netflow-office.pid -w -D -b 77.50.0.16 -p 3001 -S 7 -t 180 -z -l /mnt/array0/netflow/nfcapd-netflow-office

but when 7206 capturer starts we got error:

Jul 15 15:42:55 flows nfcapd[27478]: Add extension: 2 byte input/output interface index
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: 4 byte input/output interface index
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: 2 byte src/dst AS number
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: 4 byte src/dst AS number
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: 4 byte output bytes
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: 8 byte output bytes
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: NSEL Common block
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: NSEL xlate ports
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: NSEL xlate IPv4 addr
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: NSEL xlate IPv6 addr
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: NSEL ACL ingress/egress acl ID
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: NSEL username
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: NSEL max username
Jul 15 15:42:55 flows nfcapd[27478]: Add extension: NEL Common block
Jul 15 15:42:55 flows nfcapd[27478]: Bound to IPv4 host/IP: x.x.x.x, Port: 3010
Jul 15 15:42:55 flows nfcapd[27478]: Replay flows to host: 127.0.0.1 port: 3210
Jul 15 15:42:55 flows nfcapd[27480]: Another collector with pid 22707 is already running, and configured for '/mnt/array0/netflow/nfcapd-netflow-7206'
Jul 15 15:42:55 flows nfcapd[27480]: initialize bookkeeper failed.
Jul 15 15:42:55 flows nfcapd[27480]: Software error in bookkeeper.c line 401: Entry not found in list

As you can see, pid=22707 - is a pid of previous process with work dir '/mnt/array0/netflow/nfcapd-netflow-office'

What could it be? How to find a reason of such behavior?

**Comment by phaag** [comment]
By coincidence the token is on 64bit systems not unique enough. I try to work out a better token.

**Comment by phaag** [comment]
Thanks for the report! Should be now fixed!
