### ISSUE TITLE
include only specific protocols for ports

### ISSUE THREAD

**Issue by piorek94** [phaag/nfdump#300]
This issue could be treat as feature request.

I understand approach behind of port numbers storing: if they are exists, save it, otherwise zeroize (except icmp/6 code/type).

Have you thought about adding the mechanism to nfdump which could exclude this records (with missing ports) from port-related statistics/aggregation/filtering?

Without that nfdump's port-related output can be incorrect - I know that can be achieved by applying filter manually every time, but it is slight bothersome.

I have implemented simple solution (only as draft) for ports filtering using predefined protocol numbers in PR: #299

**Comment by phaag** [comment]
For now, I do not want to exclude them. Actually ports are set to zero, if not applicable for a specific protocol. For example, you also have port 0 when UDP gets fragmented (bytes > mtu). I see it as the users responsibility to correctly interpret the reslts from the tool and set filters accordingly. Therefore I do not want to auto-magically exclude stuff.
