### ISSUE TITLE
BPS in documentation

### ISSUE THREAD

**Issue by MuriloChianfa** [phaag/nfdump#301]
hello friends, I was reading the documentation and found this part... wouldn't it be wrong? BPS = Bits per second

https://github.com/phaag/nfdump/blob/5850f575fdea0a37cd6f3fc61379ee4c765403b5/man/nfdump.1#L82

thanks for sharing your time for a noob =D

**Comment by phaag** [comment]
Yes - it's bits per second. I'll fix the man page.
