### ISSUE TITLE
Question about sampling

### ISSUE THREAD

**Issue by antiuser** [phaag/nfdump#313]
Hi there!
I want to know if i send netflow v9 with NEL from ipt_NETFLOW and point sampler:deterministic:1024 should i point this to nfcapd -s 1024 or not?
Thank you!

**Comment by phaag** [comment]
nfcapd -s applies a default sampling to the flows received. If you know, that your exporter sends the sampling rate, it's pict up and applied automatically and therefore overwrites the -s <rate>. If you want to hard overwrite anything use a negative sampling rate -s -<rate>.
See nfcapd(1)
