### ISSUE TITLE
Nfanon problem

### ISSUE THREAD

**Issue by rafaelalmeida2909** [phaag/nfdump#315]
Guys, I recently tried to run nfanon on ubuntu 20.04. I'm using nfdump version 1.6.23. I follow nfanon's recommendations using the following command: nfanon -r file.csv -w test.csv -K al8BpDojSuFZkjm68zRUXZIlIRNYr73D

the key used is a 32-character char and is random, I confess that I didn't quite understand its purpose. When I run this command the following message appears: Open file "file.csv": bad magic: 0x7369

**Comment by phaag** [comment]
nfanon runs on nfdump binary files and not on .csv files. See nfanon(1)
