### ISSUE TITLE
nfreplay usage

### ISSUE THREAD

**Issue by ryswork1993** [phaag/nfdump#319]
I want to use Nfreplay to forward to other hosts. What should I do
nfreplay -h 192.168.1.1 -p 2055 Indicates whether to read all nfcapd files or only one file at a time. nfreplay -h 192.168.1.1 -p 2055 -r nfcapd.202111061115

**Comment by phaag** [comment]
Not sure what you mean - yes - the way you specified works: user -r for the file to replay
