### ISSUE TITLE
nfdump-1.6.23 compile issues in CentOS-6

### ISSUE THREAD

**Issue by yafrank** [phaag/nfdump#321]
Hi,
    Following raised during nfdump-1.6.23 compiling in my CentOS-6,
`
$ ./autogen.sh
autogen.sh: reconfigure with autoreconf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf --include=m4 --force
autoreconf: running: /usr/bin/autoheader --include=m4 --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:17: installing `./config.guess'
configure.ac:17: installing `./config.sub'
configure.ac:9: installing `./install-sh'
configure.ac:9: installing `./missing'
bin/Makefile.am:79: compiling `../extra/nftrack/nftrack.c' in subdir requires `AM_PROG_CC_C_O' in `configure.ac'
bin/Makefile.am: installing `./depcomp'
configure.ac: installing `./ylwrap'
Makefile.am: installing `./INSTALL'
autoreconf: Leaving directory `.'
autogen.sh: for the next step, run './configure' [or './configure --help' to check available options]
$ echo $?
0

$ ./configure --enable-sflow --enable-nfprofile --enable-nftrack
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for clang... no
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
./configure: line 3558: AX_CHECK_C11: command not found
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for a BSD-compatible install... /usr/bin/install -c
checking for rrd_update in -lrrd... yes
checking rrd.h usability... yes
checking rrd.h presence... yes
checking for rrd.h... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for rrd_update in -lrrd... (cached) yes
checking for rrd.h... (cached) yes
checking for struct sockaddr.sa_len... no
checking for struct sockaddr_storage.ss_family... yes
checking for struct sockaddr_storage.__ss_family... no
checking for struct sockaddr_storage.ss_len... no
checking for struct sockaddr_storage.__ss_len... no
checking for struct sockaddr.sa_len... (cached) no
checking for gethostbyname... yes
checking for setsockopt... yes
checking for fpurge... no
checking for __fpurge... yes
checking if htonll is defined... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for ANSI C header files... (cached) yes
checking stdio_ext.h usability... yes
checking stdio_ext.h presence... yes
checking for stdio_ext.h... yes
checking nameser8_compat.h usability... no
checking nameser8_compat.h presence... no
checking for nameser8_compat.h... no
checking features.h usability... yes
checking features.h presence... yes
checking for features.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking fts.h usability... yes
checking fts.h presence... yes
checking for fts.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking iso/limits_iso.h usability... no
checking iso/limits_iso.h presence... no
checking for iso/limits_iso.h... no
checking pcap-bpf.h usability... yes
checking pcap-bpf.h presence... yes
checking for pcap-bpf.h... yes
checking net/bpf.h usability... no
checking net/bpf.h presence... no
checking for net/bpf.h... no
checking for sys/types.h... (cached) yes
checking for netinet/in.h... (cached) yes
checking for arpa/nameser.h... yes
checking for arpa/nameser_compat.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking for netinet/in_systm.h... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking size of void *... 4
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether byte ordering is bigendian... no
checking for pid_t... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking whether closedir returns void... no
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking whether time.h and sys/time.h may both be included... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for alarm... yes
checking for working mktime... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking whether lstat dereferences a symlink specified with a trailing slash... yes
checking whether stat accepts an empty string... no
checking for strftime... yes
checking for inet_ntoa... yes
checking for socket... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strrchr... yes
checking for strstr... yes
checking for scandir... yes
checking for res_search in -lsocket... no
checking for res_search in -lresolv... yes
checking for BZ2_bzCompressInit in -lbz2... yes
checking for ptrdiff_t... yes
checking for size_t... (cached) yes
checking size of short... 2
checking size of int... 4
checking size of long... 4
checking size of long long... 8
checking size of __int64... 0
checking size of void *... (cached) 4
checking size of size_t... 4
checking size of time_t... 4
checking size of ptrdiff_t... 4
checking for an ANSI C-conforming const... (cached) yes
checking for memcmp... yes
checking for memcpy... yes
checking for memmove... yes
checking for memset... yes
checking for union semun... no
checking for the %z format string in printf()... yes
checking for doxygen... /usr/bin/doxygen
configure: creating ./config.status
config.status: creating doc/Doxyfile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: creating ./config.status
config.status: creating doc/Doxyfile
config.status: creating doc/Makefile
config.status: creating Makefile
config.status: creating bin/Makefile
config.status: creating man/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

* Many thanks for using nfdump tools
* Please send bug reports back to me: peter@people.ops-trust.net
* or open a ticket at https://github.com/phaag/nfdump/issues
* You may want to subscribe to the nfdump-discuss and/or
* nfsen-discuss mailing list:
* http://lists.sourceforge.net/lists/listinfo/nfdump-discuss
* http://lists.sourceforge.net/lists/listinfo/nfsen-discuss
$ echo $?
0

$ make
make  all-recursive
make[1]: Entering directory `/home/main/nfdump-1.6.23/nfdump-master'
Making all in .
make[2]: Entering directory `/home/main/nfdump-1.6.23/nfdump-master'
make[2]: Leaving directory `/home/main/nfdump-1.6.23/nfdump-master'
Making all in bin
make[2]: Entering directory `/home/main/nfdump-1.6.23/nfdump-master/bin'
/bin/sh ../ylwrap grammar.y y.tab.c grammar.c y.tab.h grammar.h y.output grammar.output -- bison -y  -d
conflicts: 1 shift/reduce
updating grammar.h
make  all-am
make[3]: Entering directory `/home/main/nfdump-1.6.23/nfdump-master/bin'
depbase=`echo output_util.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -ggdb  -g -O3 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -MT output_util.lo -MD -MP -MF $depbase.Tpo -c -o output_util.lo output_util.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -ggdb -g -O3 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -MT output_util.lo -MD -MP -MF .deps/output_util.Tpo -c output_util.c  -fPIC -DPIC -o .libs/output_util.o
output_util.c: In function ‘ProtoNum’:
output_util.c:207: error: ‘for’ loop initial declarations are only allowed in C99 mode
output_util.c:207: note: use option -std=c99 or -std=gnu99 to compile your code
make[3]: *** [output_util.lo] Error 1
make[3]: Leaving directory `/home/main/nfdump-1.6.23/nfdump-master/bin'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/main/nfdump-1.6.23/nfdump-master/bin'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/main/nfdump-1.6.23/nfdump-master'
make: *** [all] Error 2`

I've read https://githubmemory.com/repo/phaag/nfdump/issues/284 and tried 'sh bootstrap && ./configure .... && make' without luck. Is there anything else I can try?

Thanks!
Frank Wang

**Comment by phaag** [comment]
> ./configure: line 3558: AX_CHECK_C11: command not found

Seems you have not a clean src directory. Make sure to checkout the git master tree, or use the release tar ball provided.
The relevant files are in the m4 directory.
