### ISSUE TITLE
nfprofile | No channels to process

### ISSUE THREAD

**Issue by cde0** [phaag/nfdump#324]
I am trying to send data to influxdb but i get this error from nfprofile "No channels to process"
Any idea ? I cannot how to fix it. thanks

`nfcapd -w -D -B 200000 -S 1 -z -l /var/lib/nfsen -p 6500`
`nfprofile -p /var/lib/nfsen/ -S 1 -z  -r nfcapd.169 -i http://localhost:8086/write?....`

**Comment by phaag** [comment]
nfprofile is a command used by NfSen internally with rather complex channel parameters. It's not a good idea to abuse it for sending data to influxdb. Too many things can go wrong. If you still want to go for that, feed channel info to stdin. See NfSen src code for the details
