### ISSUE TITLE
configure: error: conditional "FT2NFDUMP" was never defined.

### ISSUE THREAD

**Issue by shao-hua-li** [phaag/nfdump#326]
Hi,

I'm trying to build nfdump. However, I encountered a configure error:
```
checking for an ANSI C-conforming const... (cached) yes
checking for memcmp... yes
checking for memcpy... yes
checking for memmove... yes
checking for memset... yes
checking for union semun... no
checking for the %z format string in printf()... yes
checking for doxygen... /usr/bin/doxygen
checking that generated files are newer than configure... done
configure: error: conditional "FT2NFDUMP" was never defined.
Usually this means the macro was only invoked conditionally.
$
```
- autoconf version 2.72
- Ubuntu 20.04.4 LTS, x86_64

Thanks!

**Comment by phaag** [comment]
How did you call configure? Which arguments?

**Comment by shao-hua-li** [comment]
> How did you call configure? Which arguments?

just `./autogen.sh` then `./configure`

**Comment by phaag** [comment]
Sorry, I can not confirm this. 
1. New Ubuntu 20.04.4 LTS. 
2. apt-get install gcc autoconf automake bison flex make libtool pkg-config libbz2-dev
3. ./autogen.sh
4. ./configure

Works without any problem

**Comment by shao-hua-li** [comment]
> 

Thanks for your reply. I downgraded my autoconf from 2.72 to 2.69, which is currently the default version in Ubuntu 20.04.4 LTS. Then it works. I'm not sure if similar issue will appear if 2.72 is used as default in the future.
