### ISSUE TITLE
nfanon displays "invalid option" when passed -h option but works OK otherwise

### ISSUE THREAD

**Issue by oza4h07** [phaag/nfdump#328]
Hello,
On my Debian Bullseye host, I've got:

`# nfanon -h
nfanon: invalid option -- 'h'
usage nfanon [options] 
-h		this text you see right here
-K <key>	Anonymize IP addresses using CryptoPAn with key <key>.
-r		read input from file
-M <expr>	Read input from multiple directories.
-R <expr>	Read input from sequence of files.
-w <file>	Name of output file. Defaults to input file.
`
Best regards

**Comment by phaag** [comment]
Fixed in master branch.
