### ISSUE TITLE
nfdump master > Makefile.in error "Makefile.in:15: * missing separator. Stop."

### ISSUE THREAD

**Issue by klakl4kla** [phaag/nfdump#329]
Hello dear community!  Thank you for the grat job you do every day! Love Github :))

Could someone help me to fix this error? After i run ./autogen.sh and then ./configure  
the next step would be to make and then make install but seems the Makefile.in  created has some syntax error (or other issue) as i see missing separator error (is there somewhere missing 'tab'? and need to replace the spaces with 'tab'?)

"make -f Makefile.in 
Makefile.in:15: *** separatore mancante.  Arresto."

Please help!! I'am a security analyst and really want to test nfdump suite with nfsen gui  to collect and analyse netflow data. 

P.S. i run the ./configure with  --enable-ftconv --enable-nfprofile --enable-nfpcapd

Thank you very much for support!
[Makefile.in.txt](https://github.com/phaag/nfdump/files/8231613/Makefile.in.txt)

**Comment by phaag** [comment]
This looks like a problem with your local autoconf/automake installation. What OS/version and autoconf/automake version are you using?

**Comment by klakl4kla** [comment]
Dear phaag, thanks for the answer. 
I realized that the ./autogen.sh returned an error related to missing libraries. Searched and installed them and then the ./configure were correctly completed by creating the makefile in nfdump/bin folder. 
Then the make and make install run successfully! 

We can close this issue as resolved. 
Thank you! 
KD
