### ISSUE TITLE
nfsen gui timeperiod 1hr off when it is before march 13th 0300

### ISSUE THREAD

**Issue by thezoggy** [phaag/nfdump#330]
Trying to get any data from nfsen gui before march 13th 0300 now results in a 1 hr offset being applied from what the user selects. This happens for both single timeslot and time window. This results in a different timeperiod being used than the user expects. This results in no/bad data.

example:
![Screen Shot 2022-03-14 at 4 01 33 PM](https://user-images.githubusercontent.com/500882/158261492-7c6e731c-6a11-444c-83fe-ff79d4765761.png)

I see that the machine this runs on, ubuntu 18.04 LTS, does have in fact the updated date and time:
```
> date
Mon Mar 14 21:13:23 UTC 2022
```

Sorry in advanced if this is a known bug as we are using  nfdump 1.6.18 /  nfsen 1.3.8 which I know  is a bit out dated.

**Comment by phaag** [comment]
Timeshift offsets usually come from not or wrong configured timezones.
Make sure, that all your timezones are identical: On your exporters (routers), collecting hosts, web servers (php) and Browser. It's most likely one of these settings and not a bug in nfdump.

**Comment by thezoggy** [comment]
everything already utc: routers / collecting host (vm that nfsen runs on) is utc. php defaults to utc but manually set to utc.  only thing that isnt utc is my machines timezone (central) just because i have to work in calendars and can do multiple timezones there and makes things easier. tried multiple browsers all suffer from the same thing where nfsen is shifting the time if the timeframe is before daylight savings. as browsers inherit system time, I've changed my mac time to utc and can confirm the issue goes away.

Is there a way to disable this 'feature' and just have it give me the time i ask for rather than it applying the offset and returning an unexpected timeframe? the other issue I see from this is  not only is it giving me back the wrong timeframe it also doesnt return results in that timeframe if you mimic to know its giving you the 1hr offset and -1hr from the selected time.

from the cli, if you ask for x time you get that time and the data within it. no issues. so purely a nfsen gui problem.

**Comment by thezoggy** [comment]
since changing the system timezone on a whim to get some data from nfsen is a bit cumbersome (makes outlook/calendars want to change stuff) the easiest way  I've found is just to focus on the browsers to override them inheriting the system timezone.

for firefox:

1.  enable resistFingerprinting, which one of the effects is it overrides your browser timezone to utc:
`about:config` and set  `privacy.resistFingerprinting` to *true*  

2.  addonL: https://addons.mozilla.org/en-US/firefox/addon/change-timezone-time-shift/
it's setup to load UTC by default, so no changes needed and can easily toggle on/off.
(tried other addons but still had the issue with UTC timezone because it leaked system daylight savings vs standard time)
