### ISSUE TITLE
netflow direction problem

### ISSUE THREAD

**Issue by lulululuej** [phaag/nfdump#338]
Hi, all

I monitor the traffic with flexible netflow v9 exported by Cisco3650, and hove both monitor-in and monitor-out like below. 
![image](https://user-images.githubusercontent.com/68433978/161899601-95792c26-6800-4031-8f89-d2ff4d762492.png)

The record fields I used in both monitor is below.
![image](https://user-images.githubusercontent.com/68433978/161899820-0cea2364-8fec-40f6-9c50-0c55d25bca96.png)

But i notice there is no *out_bytes* & *out_pkts* in the traffic log.
I wonder if I want to know the upload and download traffic seperately, how should i aggregate using only *in_bytes* & *in_pkts* value? Or is there anything I missing in the Cisco configuration?

Really appreciate with any advice.

**Comment by phaag** [comment]
I actually don't know how the configuration on the device is finally reflected at the netflow record level. Netflow v9 can but need not to send in/out traffic differently. Lots of devices take the view of the interface, the netflow data is collected.
Try to display the records in raw format -o raw which displays everything collected per record and check if you can distinguish between different device configurations.  
nfcapd is FNF aware and sotores and many fields possible. If you still think, there are problems, you need to send me a pcap with traffic sent too the nfcapd collecter process, so I can have a look. For that send it to my email in the Authors file.

**Comment by phaag** [comment]
Any new on that?

**Comment by phaag** [comment]
I close the issue, as no more info is sent. You can open the ticket any time again.
