### ISSUE TITLE
RouterOS Flow Data analysis

### ISSUE THREAD

**Issue by zerowolf001** [phaag/nfdump#339]
Hi guys,
I am trying to monitor Mikrotik devices,I have used nfdump to get NetFlow on the server, but now I can't distinguish which traffic is used for downloading and which traffic is generated by instant messaging or game video. I'd like to ask if there is any good way to meet the requirements of this scenario. thank you!

**Comment by phaag** [comment]
You need to check by IP address which IP generates which traffic. See also nfdump(1) and all the -s stat functions
Use -s ip/bytes for large downloads, -s ip/flows for frequent talkers etc.

**Comment by zerowolf001** [comment]
Upload or download traffic can be analyzed in this way, but what if we want to distinguish between games and videos? How to distinguish? Are there any landmark features?

**Comment by phaag** [comment]
You need to know IP addresses ports or other characteristics. This is outside the scope of nfdump, and you need to find some advice from the game or video portal operator

**Comment by zerowolf001** [comment]
OK, I see. Thank you
