### ISSUE TITLE
Generating new bi-directional flows from uni-directional ones through option -B

### ISSUE THREAD

**Issue by nesg-ugr** [phaag/nfdump#340]
Dear all,

I captured several NetFlow flows in a nfcapd file. I would like to export it after aggregating by the -B option by means of the use of the -w option. However something is wrong when I did it because I expected to have the same results after executing

`nfdump -r nfcapd_201604130000 -B -q -o "fmt:%dp" | sort | uniq | wc -l`

and

`nfdump -r nfcapd_201604130000 -B -w nfcapd_201604130000_B`
`nfdump -r nfcapd_201604130000_B -q -o "fmt:%dp" | sort | uniq | wc -l`

It is just a dummy example. What I would expect to get is the same number of different destination ports either directly using -B option or firstly aggregating and then exporting and finally using the exported version of the aggregation, the *_B file.  Sadly, I did not get the same results. Moreover, the *_B file is larger that the original one.

Is this right? Should I get the same results? In that case, Is there a bug or something that I missed or misunderstood when using nfdump in this way?

Thanks in advance.

Best,
Roberto.

**Comment by phaag** [comment]
I check with a dummy flow file f1, which I append here. ( Unzip first :)

```
./nfdump -r f1 -B -w f2 -y
./nfdump -r f1 -B -o "fmt:%dp" -q | sort | uniq | wc -l
./nfdump -r f2 -o "fmt:%dp" -q | sort | uniq | wc -l
```
The output results in 1341 in both cases. I also compared the output and and is identical.
The size of the files may be different for different reason:
Compression of both files may be different. Data blocks are not identical.
The flow records get expanded with -B because reverse counters are added to each flow. This blows up the file size too. 

If you have different results, please send me you anonymised  flow file to test.

[f1.zip](https://github.com/phaag/nfdump/files/8599137/f1.zip)

**Comment by nesg-ugr** [comment]
Hi,

First of all, thanks for quick answer. I reproduced your code steps but the problem remains equal. Attached you can see the results.
![screenshot](https://user-images.githubusercontent.com/46821804/169358098-74f20eec-77fa-4b55-aac4-6f1cd04c2411.png)

I ran the experiments on Ubuntu 20.04.4 LTS with nfdump  Version: NSEL-NEL1.6.18

Thanks for all!

Roberto.

**Comment by phaag** [comment]
I still can not confirm what you see:

```
host-2% ./nfdump -r f1 -B -w f2 -y
host-2% ./nfdump -r f1 -B -o "fmt:%dp" -q | sort | uniq | wc -l 
    1341
host-2% ./nfdump -r f2 -o "fmt:%dp" -q | sort | uniq | wc -l
    1341
```

Please sind me the output of ```head config.log``` in the build directory and please confirm you are using the Github master branch

**Comment by nesg-ugr** [comment]
Hi,

I can confirm you your output. The problem came from the nfdump release. I was using nfdump 1.6.18. After updating to the latest one, everything were well.

It seems to be fixed in the latest release.

Thanks for your kind support!

Best,
Roberto.

**Comment by phaag** [comment]
Great, that it works!
