### ISSUE TITLE
JSON output not always correct

### ISSUE THREAD

**Issue by borjam** [phaag/nfdump#342]
Tried with nfdump 1.6.24.

Using -o json it seems sometimes the JSON output is not complete. The end square bracket is missing.

I guess it happens when it finds some corrupt files while doing a long -R read. Despite sending several JSON records to the standard output, it failed to output the last square bracket. 

I think it should "finish what it started" so, despite errors, the JSON list should be terminated.

`% /usr/local/bin/nfdump -R /usr/local/var/nfsen/profiles-data/live -o json -t 2022/05/04.12:01-2022/05/04.12:02 > /tmp/jsonroto
Open file '/usr/local/var/nfsen/profiles-data/live/MX204M1/nfcapd.202104220115': bad magic: 0x0

Open file /usr/local/var/nfsen/profiles-data/live/MX204M1/nfcapd.202104220115: bad version: 0

read() error in nffile.c line 457: Bad file descriptor

Open file '/usr/local/var/nfsen/profiles-data/live/MX80INX1/nfcapd.202104220055': bad magic: 0x0

Open file /usr/local/var/nfsen/profiles-data/live/MX80INX1/nfcapd.202104220055: bad version: 0

read() error in nffile.c line 457: Bad file descriptor

Read error in file '/usr/local/var/nfsen/profiles-data/live/MX80INX1/nfcapd.202104220055': Bad file descriptor

read() corrupt data file: Unexpected EOF in nffile.c line 1109: ?X??????????????????̸x

Skip corrupt data file '/usr/local/var/nfsen/profiles-data/live/MX80INX1/nfcapd.202104220100'

Skip unknown record type 20645

Skip unknown record type 7440

Skip unknown record type 1474

Corrupt data file. Inconsistent block size in nfdump.c line 472

% tail /tmp/jsonroto 
	"dst_tos" : 0,
	"direction" : 255,
	"ip4_next_hop" : "A.B.C.D",
	"bgp4_next_hop" : "X.Y.Z.T",
	"src_vlan" : 0,
	"dst_vlan" : 0,
	"ip4_router" : "F.G.H.J",
	"t_received" : "2022-05-04T12:02:35.431",
	"label" : "<none>"
}

`

**Comment by phaag** [comment]
I don't understand this output: You can not have bad magic as well as bad version likewise. After a bad magic nfdump stops processing. As well after a bad version. 
You can not get a json output ( actually any output ) after these error messages. So this all is a bit wired.
nfdump should correctly terminate a json output if a valid file is given. If an error is not recoverable it is more safe to exit and terminate nfdump, than to try to evaluate if a print_epilog needs to be printed, as the status of previous output is unclear.
In nfdump line 471 you may replace exit with a return, but the result is hight unpredictable.

I assume, this output is compiled from different runs?

**Comment by phaag** [comment]
Any update on that issue?

**Comment by phaag** [comment]
I close this issue. If any new information pop up, let me know.
