### ISSUE TITLE
Netflow V9 and missing ICMP_TYPE...

### ISSUE THREAD

**Issue by ken-adey** [phaag/nfdump#346]
Hi Peter, we're seeing some netflow V9 come through without the expected ICMP_TYPE field, and I wanted to confirm that nfdump will report out 0 in the destination port when this happens and is expected behavior.

Thanks,

Ken....

**Comment by phaag** [comment]
Hi Ken,
Yes - this field is set to 0 and is to be expected.
Hope this helps
Peter
