### ISSUE TITLE
nfdump v1.7

### ISSUE THREAD

**Issue by hhamed1989** [phaag/nfdump#350]
Hello Dears,

I browsed the web and found that nfdump version 1.7 has multi-threaded and processes capabilities. But I did not find any file to install.
Thank you for telling me how to use version 1.7 or use multi-threaded and processes for nfdump.

Best Regards,

**Comment by phaag** [comment]
It is basically the same installation procedure as 1.6.x. With 1.7 (or unicorn) you can read older files from 1.6.x but not vice versa.

**Comment by hhamed1989** [comment]
Thanks for your quick reply,
But could you please let me know where can I download the 1.7 (or unicorn)? I can't find it in releases.
