### ISSUE TITLE
Cloudgenix IPFIX rejected...

### ISSUE THREAD

**Issue by ken-adey** [phaag/nfdump#364]
Nfcapd is unable to parse Cloudgenix IPFIX flows: "Error reading netflow header: Unexpected netflow version".

This error is seen in V1.6.23 and the latest master.

Pcap provided on request.

**Comment by phaag** [comment]
The pcap would be appreciated.  Many thanks

**Comment by phaag** [comment]
The error message can not be reproduced, however:
nfdump v.1.6.23 and v.1.6.24 did not accept the records due to missing packet/byte counters.
The very last v1.6.x release - nfdump-1.6.25 does accept the data and so do all v1.7.x releases as well as the master branch.

**Comment by phaag** [comment]
Any update on that issue?

**Comment by ken-adey** [comment]
This can be closed. Customer configured their exporter properly to include the missing packet/byte counts.

**Comment by phaag** [comment]
Very good! Thanks for the feedback.
