### ISSUE TITLE
nfdump not showing ifName from Cisco IOS-XR 6.7.3

### ISSUE THREAD

**Issue by cmason3** [phaag/nfdump#367]
I am trying to get ifName resolution working from an NetFlow v9 export from a Cisco IOS-XR device, but although I can see the options being sent, I am unable to display them using `nfdump`:

The Cisco device is configured as follows:

```
flow exporter-map FEM
 version v9
  options interface-table
  options vrf-table
  template timeout 300
 !
 transport udp 2048
 source <INTF>
 destination <IP> vrf <VRF>
!
```

I am running `nfcapd` using the following command line: `sudo nfcapd -p 2048 -b <IP> -4 -l /var/cache/nfdump -t 900 -z -w -D`.
I have also run `tcpdump` and I can see the following being received by my collector, for example:

```
Cisco NetFlow/IPFIX
    Version: 9
    FlowSet 1 [id=256] (19 flows)
        FlowSet Id: (Data) (256)
        FlowSet Length: 1372
        [Template Frame: 5]
        Flow 1
            ScopeSystem: ac10fc04
            InputInt: 381
            IfDescr: GigabitEthernet0_0_0_24.160
```

But when I run 'nfdump -r <file> -o raw', I am only seeing the ifIndex values and not the ifNames:

```
Flow Record:
  Flags        =              0x06 NETFLOW v9, Unsampled
  label        =            <none>
  export sysid =                 1
  size         =                84
  first        =        1665589845 [2022-10-12 16:50:45]
  last         =        1665590234 [2022-10-12 16:57:14]
  msec_first   =               431
  msec_last    =               903
  src addr     =              <SA>
  dst addr     =              <DA>
  src port     =             19754
  dst port     =                22
  fwd status   =                64
  tcp flags    =              0x18 ...AP...
  proto        =                 6 TCP
  (src)tos     =                40
  (in)packets  =              1534
  (in)bytes    =            108936
  input        =               381
  output       =               397
  src as       =                 0
  dst as       =                 0
  nat event    =                 0: IGNORE
  ingress VRF  =        1610612740
  egress VRF   =        1610612736
```

Is this not supported or am I doing something wrong?

**Comment by phaag** [comment]
I need to know, what the Cisco IOS-XR is sending exactly to the collector. @cmason3 Could you send me a pcap containing template and record data - the data sent to the collector to me be email? Please use the email in the AUTHORS file.

**Comment by cmason3** [comment]
I can now confirm that after the next export window it is now resolving them:

```
  input        =               199 BVI26
  output       =               387 GigabitEthernet0_0_0_24.2020
```

This is perfect, thank you!

**Comment by phaag** [comment]
Cool - so I close this issue. Feel free to reopen, or open a new one if something does not work.
