### ISSUE TITLE
Option -M does not work in 1.7.0.1

### ISSUE THREAD

**Issue by heiko3** [phaag/nfdump#369]
Option -M no longer works in version 1.7.0.1, since the file existence is already done in the option -r evaluation. This should happen later and considering the directories of the -M option.

Following example works in 1.6.x but fails in 1.7.0.1 ("beispiel is not a file or directory"):

```
mkdir -p /tmp/nfdemo/{eins,zwei}
nfgen > /tmp/nfdemo/eins/beispiel
nfgen > /tmp/nfdemo/zwei/beispiel
nfdump -r beispiel -M /tmp/nfdemo/eins:zwei
```

**Comment by phaag** [comment]
Thanks for the bug report. Fixed in master repo. Please note, that your commands only work with **nfgen** from nfdump-1.6.x.
