### ISSUE TITLE
nfdump NSEL zero packets

### ISSUE THREAD

**Issue by katrichnikitos** [phaag/nfdump#37]
Hello Peter,
First of all thanks for your great work.
I am using nfsen with several Cisco routers and ASAs. Recently I've migrated nfdump from 1.5.8-2-NSEL to the latest 1.6.15 (compiled it with options --enable-nfprofile --enable-compat15 --enable-nsel) and nfsen from 1.3.6 to 1.3.7.  $EXTENSIONS = 'all' in nfsen.conf
The netflow data from routers is ok, but there are no packet counters from ASAs. 
But there were packet counters with nfdump-1.5.8-2-NSEL. All ASAs sw versions are the same (the versions range from 8.2.3 to 9.5.1).
Do i miss something with configuration or compilation? Or is it the netflow protocol mismatch? Or is it normal  situation due to ASA behavior?

**Comment by phaag** [comment]
It is difficult to tell, what could be wrong. If you compiled as you write, it should work. Have you checked, that you correctly replaced all binaries and restarted all processes?

**Comment by sallevan** [comment]
Yes, I have correctly replaced all binaries, but it does not work. :)

Compile time parameters: `./configure --disable-compat15 --enable-nsel --disable-fixtimebug --enable-nfprofile --enable-nftrack --with-rrdpath=/usr/local --enable-ftconv --with-ftpath=/usr/local --enable-readpcap --enable-sflow --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/info/
`

tcpdump shows that NetFlow packets at least comes from Cisco ASA 5510:

```
host/domain# s ver

Cisco Adaptive Security Appliance Software Version 9.1(5)
Device Manager Version 7.1(5)

Compiled on Thu 27-Mar-14 09:36 by builders
System image file is "disk0:/asa915-k8.bin"
Config file at boot was "startup-config"
```

O.k, trying to start it with echo option:

```
/usr/local/bin/nfcapd -w -E -p 9995 -u www -g www -B 200000 -S 1 -P /var/run/nfsen/p9995.pid -z -I any -l /tmp -Tall -4                                                                                  
Add extension: 2 byte input/output interface index
Add extension: 4 byte input/output interface index
Add extension: 2 byte src/dst AS number
Add extension: 4 byte src/dst AS number
Add extension: dst tos, direction, src/dst mask
Add extension: IPv4 next hop
Add extension: IPv6 next hop
Add extension: IPv4 BGP next IP
Add extension: IPv6 BGP next IP
Add extension: src/dst vlan id
Add extension: 4 byte output packets
Add extension: 8 byte output packets
Add extension: 4 byte output bytes
Add extension: 8 byte output bytes
Add extension: 4 byte aggregated flows
Add extension: 8 byte aggregated flows
Add extension: in src/out dst mac address
Add extension: in dst/out src mac address
Add extension: MPLS Labels
Add extension: IPv4 router IP addr
Add extension: IPv6 router IP addr
Add extension: router ID
Add extension: BGP adjacent prev/next AS
Add extension: time packet received
Add extension: NSEL Common block
Add extension: NSEL xlate ports
Add extension: NSEL xlate IPv4 addr
Add extension: NSEL xlate IPv6 addr
Add extension: NSEL ACL ingress/egress acl ID
Add extension: NSEL username
Add extension: NSEL max username
Add extension: nprobe latency
Add extension: NEL Common block
Add extension: Compat NEL IPv4
Add extension: NAT Port Block Allocation
Bound to IPv4 host/IP: any, Port: 9995
Standard setsockopt, SO_RCVBUF is 42080 Requested length is 200000 bytes
System set setsockopt, SO_RCVBUF to 200000 bytes
Startup.
Init IPFIX: Max number of IPFIX tags: 62
```

Well, it seems to catch some traffic from ASA:

`Process_v9: New exporter: SysID: 1, Domain: 0, IP: 10.132.0.1`

But does not recognise anything:

```
^CFile Block Header:
  NumBlocks     =           1
  Size          =          32
  id             =           2

Ident: 'any' Flows: 0, Packets: 0, Bytes: 0, Sequence Errors: 0, Bad Packets: 0
Total ignored packets: 0

```

What could be wrong?

**Comment by phaag** [comment]
No further information
