### ISSUE TITLE
Pimp good old NfSen for nfdump-1.7.

### ISSUE THREAD

**Issue by mkoelewijn** [phaag/nfdump#371]
Would be awesome if good old NfSen can be used with nfdump 1.7. for multithreading.

**Comment by atbohmer** [comment]
Start by launching nfsenn:
nfsen[22946]: No valid directory: -D
Nov 18 12:01:30 nfsen: : collector did not start - see logfile (router)path does not exist: -D

**Comment by phaag** [comment]
You can find a pimped version of nfsen at https://github.com/phaag/nfsen
Feedback and further patches are appreciated.

**Comment by atbohmer** [comment]
Very much appreciated , will try to test it on a Linux server today!

**Comment by atbohmer** [comment]
When opening the Details tab, it is incomplete and Apache logs:
PHP Fatal error:  Uncaught Error: Call to undefined function formatLanguage() in /var/www/html/nfsen/details.php:814\nStack trace:\n#0 /var/www/html/nfsen/nfsen.php(779): DisplayDetails()\n#1 {main}\n  thrown in /var/www/html/nfsen/details.php on line 814

Is this due to using PHP 7.4.33 and should I use a PHP 8 version?

**Comment by atbohmer** [comment]
Ok adding PHP 8.1 to the equation ads an extra exception:

[Thu Dec 08 09:22:03.279968 2022] [php:error] [pid 34155] [client ip:50433] PHP Fatal error:  Uncaught Error: Call to undefined function formatLanguage() in /var/www/html/nfsen/details.php:814\nStack trace:\n#0 /var/www/html/nfsen/nfsen.php(779): DisplayDetails()\n#1 {main}\n  thrown in /var/www/html/nfsen/details.php on line 814, referer: https://server/nfsen/nfsen.php?tab=0

[Thu Dec 08 09:22:03.280113 2022] [php:error] [pid 34155] [client ip:50433] PHP Fatal error:  Uncaught Exception: Serialization of 'Socket' is not allowed in [no active file]:0\nStack trace:\n#0 {main}\n  thrown in [no active file] on line 0, referer: https://server/nfsen/nfsen.php?tab=0

**Comment by phaag** [comment]
Sigh .. either too old or too new - either deprecated or undefined. I will fix that

**Comment by phaag** [comment]
Fixed. Please open for other bugs an issue in the nfsen repo https://github.com/phaag/nfsen

**Comment by atbohmer** [comment]
Yesss, looking much better, much appreciated Peter!!
