### ISSUE TITLE
write out to json file

### ISSUE THREAD

**Issue by laoshaw** [phaag/nfdump#373]
I can see clear text json file with `nfdump -b -R /var/log/2022/ -n 15 -o json -b -q -j` but when I tried to save that to a file, the nfdump.json file below is a binary file that does not look like json:

`nfdump -b -R /var/log/2022/ -n 15 -o json -b -q -j -w /tmp/nfdump.json` , is -w designed for something else?

**Comment by phaag** [comment]
The option -w is for writing binary files. You mix up too many option generally. Those are all ignored.
-n is only useful for statistics, -b is used twice. -q only for txt output. 
Right now you can not combine json output with -b, it is used for listing flows only.
