### ISSUE TITLE
ipfix.c: samplingPacketInterval (305) behaviour

### ISSUE THREAD

**Issue by ytti** [phaag/nfdump#377]
https://github.com/phaag/nfdump/commit/31137a3f5b893c17d3bb3295916b133b79e6b7c7 -creates equivalency between samplingInterval(34) and samplingPacketInterval(305). 

However [IANA](https://www.iana.org/assignments/ipfix/ipfix.xhtml) states:
![Näyttökuva 2022-11-5 kello 10 09 59](https://user-images.githubusercontent.com/200527/200110344-cb2b1967-2fe5-4a59-b50d-822763810e0c.png)

That is, almost exclusively samplingPacketInterval(305) will have value of 1, run-length of 1 packet sampled when sampling is triggered. While samplingPacketSpace(306) defines gaps between intervals, which almost exclusively is samplingInterval(34)-1. 

Practical example from Nokia SR7750 running 21.10R3.
![image](https://user-images.githubusercontent.com/200527/200110386-cbe9c914-b46a-45a5-ab24-8a4ed8995d09.png)

[Pmacct ](https://github.com/pmacct/pmacct/commit/481ffa39ca6349c7ef8729188ba7fb417ec53707) appears to use the non-deprecated entities as defined by IANA.

**Comment by phaag** [comment]
Ahh .. I see. So the estimated sampling rate would then be (305)/((305)+(306)) . At least it would be more accurate.

**Comment by ytti** [comment]
> Ahh .. I see. So the estimated sampling rate would then be (305)/((305)+(306)) . At least it would be more accurate.

Correct, this is how I read pmacct to perform this. I couldn't identify anywhere else where this is implemented as designed. Arbor is broken too, and was accepted as bug and is being fixed.

I'm speculating here, but very likely in future most IPFIX implementations become stateless, Juniper is going stateless with PTX, this is on basis that in most practical implementations vast majority of flow caches see only 1 packet ever, making stateless useless over head. But if we go stateless, then it may become attractive to pick >1 packet, when we export, to fill up the MTU of export. So if my speculation (based on nothing) is correct, these may become more common going forward.

**Comment by phaag** [comment]
Fixed in latest master. Reworked sampling code in general. Sampler are now reported in new notation using ./nfdump -E <file>
