### ISSUE TITLE
1.7.0.1: nfcapd building: libnetflow.a should be placed before libnfdump.a

### ISSUE THREAD

**Issue by asy972** [phaag/nfdump#382]
Hello. I came across such an error:

libtool: link: x86_64-alt-linux-gcc -pipe -Wall -g -O2 -std=gnu11 -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -DNSEL -pthread -o nfcapd nfcapd-nfcapd.o nfcapd-netflow_pcapd.o  -L../lib ../lib/.libs/libnfdump.a ../collector/libcollector.a ../netflow/libnetflow.a ../conf/libconf.a -lm -lresolv -lpthread -latomic -lbz2 -pthread
../netflow/libnetflow.a(netflow_v9.o): In function `removeTemplate':
/home/asy/RPM/BUILD/nfdump-1.7.0.1/src/netflow/netflow_v9.c:484: undefined reference to `ClearSequencer'
<and some other errors>
collect2: error: ld returned 1 exit status
make[2]: *** [nfcapd] Error 1

This patch helps:

--- src/nfcapd/Makefile.am.bak  2022-12-02 19:54:05.209937371 +0400
+++ src/nfcapd/Makefile.am      2022-12-02 19:54:05.211937396 +0400
@@ -9,7 +9,7 @@

 nfcapd_SOURCES = nfcapd.c \
        $(nfpcapd)
-nfcapd_LDADD = ../lib/libnfdump.la ../collector/libcollector.a  ../netflow/libnetflow.a
+nfcapd_LDADD = ../netflow/libnetflow.a ../lib/libnfdump.la ../collector/libcollector.a
 nfcapd_LDADD += ../conf/libconf.a -lm
 nfcapd_LDFLAGS = -L../lib

**Comment by phaag** [comment]
Hmm .. interesting, that I never came across this error. I tested the build on several platforms without any problem. But if this fixes your problem - I certainly can add this change.
