### ISSUE TITLE
Aggregation (-A) not working for GeoDB's enriched AS data.

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#390]
Aggregation is not working for GeoDB's enriched AS information.

**ORIGINAL, AS-LESS INFORMATION:** ✅
root@aa88b9ce3ad5# nfdump -r 1 -O bytes -o "fmt: %sas" | head -n5
 Src AS
      0
      0
      0
      0

**GEODB-ENRICHED INFORMATION** ✅
root@aa88b9ce3ad5# NFGEODB=mmdb.nf nfdump -r 1 -O bytes -o "fmt: %sas" | head -n5
 Src AS
  28573
  28573
 266388
 266388

**AGGREGATION PER SOURCE AS FAILS** ❌
root@aa88b9ce3ad5# NFGEODB=mmdb.nf nfdump -r 1 -A srcas
Date first seen             Duration      Src AS   Packets    Bytes      bps    Bpp Flows
2022-12-11 10:15:43.400     00:00:59.310       0      7280    4.1 M   550895    561   409
Summary: total flows: 409, total bytes: 4.1 M, total packets: 7280, avg bps: 550895, avg pps: 122, avg bpp: 561
Time window: 2022-12-11 10:15:43 - 2022-12-11 10:16:42
Total flows processed: 409, passed: 409, Blocks skipped: 0, Bytes read: 69464
Sys: 0.5640s User: 1.4800s Wall: 0.0006s flows/second: 706245.5 Runtime: 0.0008s

**Comment by phaag** [comment]
Thanks for the report. I am glad to see, people are using the geoDB features. :) It's not yet wired everywhere and I still think about some more elegant ways to enrich the records. For performance reasons, I enrich records only, if that information is used at some point. I try t go for a quick fix.
