### ISSUE TITLE
There will be aggregate option per country code?

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#391]
nfdump's man page refers to filtering per source country code (src geo) and destiny country code (dst geo).

But there's nothing regarding to aggregating by those elements. Something like "-A srcctry/dstctry" to aggregate by country code. There are plans to include this feature?

**Comment by phaag** [comment]
Yes. This can be added as well. It going to be implemented as -A srcgeo,dstgeo

**Comment by phaag** [comment]
It is implemented with [3550a3f](https://github.com/phaag/nfdump/commit/3550a3f42ffa924e924048cf16b8baafda8a1437)

**Comment by gabrielmocan** [comment]
Thank you very much for quick replies and fixes, Pete.
