### ISSUE TITLE
configure:17350: error: conditional "HAVEPCAPAPPEND" was never defined. 

### ISSUE THREAD

**Issue by atbohmer** [phaag/nfdump#396]
This seems odd to me because it is yes or no reading the configure script?

$ lsb_release -d
Description:	Red Hat Enterprise Linux Server release 7.9 (Maipo) 

$ scl enable devtoolset-11 bash
$ ./autogen.sh
autogen.sh: reconfigure with autoreconf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --include=m4 --force
autoreconf: running: /usr/bin/autoheader --include=m4 --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:27: installing './config.guess'
configure.ac:27: installing './config.sub'
configure.ac:9: installing './install-sh'
configure.ac:9: installing './missing'
Makefile.am: installing './INSTALL'
src/collector/Makefile.am: installing './depcomp'
configure.ac: installing './ylwrap'
src/nfsen/Makefile.am:15: warning: compiling '../collector/nfstatfile.c' in subdir requires 'AM_PROG_CC_C_O' in 'configure.ac'
parallel-tests: installing './test-driver'
autoreconf: Leaving directory `.'
autogen.sh: for the next step, run './configure' [or './configure --help' to check available options]

$ ./configure --enable-nftrack --enable-nfprofile --enable-sflow --enable-readpcap
....
checking for doxygen... /usr/bin/doxygen
checking that generated files are newer than configure... done
configure: error: conditional "HAVEPCAPAPPEND" was never defined.
Usually this means the macro was only invoked conditionally.

**Comment by phaag** [comment]
Fixed!
