### ISSUE TITLE
Nfdump - wrong date on CISCO logs

### ISSUE THREAD

**Issue by mateuszbm** [phaag/nfdump#397]
Hi,
after update to version 1.7 we have problem with nfdump.
Some dates are not read right, instead we see: 1970-01-01 01:00:00.000 
There was no problem in the earlier version 1.6.
Please tell me what additonal info/debug logs should I give you to verify this.
Regards.

**Comment by phaag** [comment]
Could you please send me a pcap to my email address in the AUTHORS file.

**Comment by mateuszbm** [comment]
Thanks for response. I send a message to your email address.

**Comment by phaag** [comment]
The collected data is correct, however, not always correctly displayed. It should be fixed in latest master repo.

**Comment by mateuszbm** [comment]
Thank you, it is working just fine.

**Comment by phaag** [comment]
Cool.
