### ISSUE TITLE
output_fmt.c:618:18: error: expected ‘;’ before ‘}’ token

### ISSUE THREAD

**Issue by atbohmer** [phaag/nfdump#399]
Running make:
....
mv -f $depbase.Tpo $depbase.Po
output_fmt.c: In function ‘ParseOutputFormat’:
output_fmt.c:618:18: error: expected ‘;’ before ‘}’ token
  618 |         return 0l
      |                  ^
      |                  ;
  619 |     }
      |     ~
make[2]: *** [Makefile:382: output_fmt.o] Error 1
make[2]: Leaving directory '/data/software/netflow/nfdump/src/output'
make[1]: *** [Makefile:423: all-recursive] Error 1
make[1]: Leaving directory '/data/software/netflow/nfdump'
make: *** [Makefile:354: all] Error 2

Having a look at output_fmt.c:618:18 
    if (!s) {
        LogError("malloc() allocation error in %s line %d: %s", __FILE__, __LINE__, strerror(errno));
        return 0l
    }

The l after return 0 seems like a typo to me, replaced it with a ; and now make runs to completion.

**Comment by gabrielmocan** [comment]
Yeah, I've pointed that on the commit also.

**Comment by phaag** [comment]
Oh .. how embarrassing. Yes - return 0; would be correct.
