### ISSUE TITLE
Not getting BGP Next Hop in ipv6.

### ISSUE THREAD

**Issue by Zeawiel** [phaag/nfdump#4]
Hello, I'm collecting Cflow v9 from Alcatel Lucent SRxx and i'm trying to aggregate on bgpnext.
This is my setting 
- nfdump: Version: 1.6.13
- Ubuntu 14.04LTS

When I aggregate with 

```
 nfdump -r nfsen/profiles-data/live/xxx/2015/11/02/nfcapd.201511021815 -A 'srcas,dstas,inif,outif,bgpnext' -o raw "ipv6" | grep bgp
```

And all i'm getting is something like that :

```
bgp next hop =           0.0.0.0
bgp next hop =                ::
bgp next hop =           0.0.0.2
bgp next hop =                ::
bgp next hop =           0.0.0.0
bgp next hop =                ::
bgp next hop =           0.0.0.0
bgp next hop =                ::
bgp next hop =           0.0.0.0
bgp next hop =                ::
bgp next hop =           0.0.0.0
bgp next hop =                ::
bgp next hop =           0.0.0.1
bgp next hop =                ::
(...)
```

Do you notice that bug ?

When I sniff the cflow packets from the interface. I see the correct Ipv6 Bgp Next Hop Address (or Ipv4 address is there is not an Ipv6)

If I apply a filter on ipv4 I get the BGP next hop ipv4 address properly. It seems only appear on Ipv6.

**Comment by phaag** [comment]
Did you add extension 5 BGP next hop IP to the collectors args? -T5. If in doubt use -Tall. If next hop is still empty, please let me know

**Comment by Zeawiel** [comment]
Hello,
I'm already using the extension 5 within the nfcapd command. This is mine:
> ps aux | grep nfcapd
> /usr/local/bin/nfcapd -w -D -p 2055 -u www-data -g www-data -B 200000 -S 1 -P /data/nfsen/var/run/p2055.pid -z -T +4,+5 -n (...)

I'm getting correctly the BGP next hop ipv4.
When I look at the netflow packet coming in the interface (with tcpdump), I see the nexthop ipv4 & ipv6 correctly. That weird.

If you need something, don't hesitate !

Happy new year ;)

**Comment by liuzf13** [comment]
Heello,

We meet the same problem. The filter of nexthop bgp or nexthop ip on ipv6 doesn't work well, and the result is always 0.0.0.0. Is there any methods to solve this problem?

**Comment by phaag** [comment]
Hi,
Would it be possible to collect me a pcap of a few minutes (incl. templates) sent to
nfcapd with next hop/bgp next hop in IPv6?

That would help

Thanks
Peter

**Comment by liuzf13** [comment]
Hi phaag,

It seems that some of our routers get the wrong nfcapd configuration.  We have figured it out and solve this problem. I think you can close the issue. Thank you.
