### ISSUE TITLE
output_raw.c: In function ‘stringEXgenericFlow’:

### ISSUE THREAD

**Issue by atbohmer** [phaag/nfdump#400]
RHEL 7

$ scl enable devtoolset-11 bash
$ ./autogen.sh 
$ ./configure --enable-nftrack --enable-nfprofile --enable-sflow --enable-readpcap
$ make
...
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I../include -I../lib -I../conf -I../maxmind -I../inline    -g -O3 -std=gnu11 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -pthread -MT output_raw.o -MD -MP -MF $depbase.Tpo -c -o output_raw.o output_raw.c &&\
mv -f $depbase.Tpo $depbase.Po
output_raw.c: In function ‘stringEXgenericFlow’:
output_raw.c:68:31: error: ‘master_record_t’ {aka ‘struct master_record_s’} has no member named ‘msecEvent’
   68 |         uint64_t eventTime = r->msecEvent ? r->msecEvent : r->msecFirst;
      |                               ^~
output_raw.c:68:46: error: ‘master_record_t’ {aka ‘struct master_record_s’} has no member named ‘msecEvent’
   68 |         uint64_t eventTime = r->msecEvent ? r->msecEvent : r->msecFirst;
      |                                              ^~
make[2]: *** [Makefile:382: output_raw.o] Error 1

**Comment by phaag** [comment]
Ohh -

**Comment by atbohmer** [comment]
No sweat Peter, I'm such I guy who is so lucky to step on the needle in a hay stack ;-)

**Comment by phaag** [comment]
That’s not the point - please do so. I just think, such bugs are a bit embarrassing  ..
