### ISSUE TITLE
Not able to process ASA NSEL flows

### ISSUE THREAD

**Issue by johnelisity** [phaag/nfdump#401]
Hello Team,

I have Cisco ASA version 9.8 configured to send flows:

```
flow-export destination inside X.X.X.X 3008
flow-export template timeout-rate 1 
flow-export delay flow-create 60 
!
access-list netflow-export extended permit ip any any 
!
class-map netflow-export-class 
 match access-list netflow-export 
!
policy-map global_policy 
 class netflow-export-class 
  flow-export event-type all destination X.X.X.X 
!
service-policy global_policy global
```

on X.X.X.X i have nfcapd version 1.7 (compiled from source with nsel support) listening:
```
[root@log]# /opt/nfdump/bin/nfcapd -V
/opt/nfdump/bin/nfcapd: Version: 1.7.1

[root@log]# /opt/nfdump/bin/nfcapd -n 77,Y.Y.Y.Y,/netflow/77/ -p 3008 -t 60 -T all -E -v
Add flow source: ident: 77, IP: Y.Y.Y.Y, flowdir: /netflow/77/
Option -T no longer supported and ignored
Verbose log level: 4
Bound to IPv4 host/IP: any, Port: 3008
Init v1
Init v5/v7: Default sampling: 1
Init v9: Max number of v9 tags: 105, default sampling: 1
Init IPFIX: Max number of ipfix tags: 80, default sampling: 1
Startup nfcapd.

File Block Header: type: 3, size: 0, NumRecords: 0
Ident: '77' Flows: 0, Packets: 0, Bytes: 0, Sequence Errors: 0, Bad Packets: 0
File Block Header: type: 3, size: 0, NumRecords: 0
Ident: '77' Flows: 0, Packets: 0, Bytes: 0, Sequence Errors: 0, Bad Packets: 0
```

At the same time when sniffing that traffic i can see ASA NSEL flows correctly:
```
[root@log]# tshark -i eth0 -p -nnV -f "host Y.Y.Y.Y" -2 -d udp.port=3008,cflow
.....
    Source: Y.Y.Y.Y (Y.Y.Y.Y)
    Destination: X.X.X.X (X.X.X.X)
User Datagram Protocol, Src Port: 6345 (6345), Dst Port: 3008 (3008)
    Source port: 6345 (6345)
    Destination port: 3008 (3008)
    Length: 1440
    Checksum: 0xe00c [validation disabled]
        [Good Checksum: False]
        [Bad Checksum: False]
Cisco NetFlow/IPFIX
    Version: 9
    Count: 12
    SysUptime: 2054744553
    Timestamp: Jan 27, 2023 18:19:40.000000000 UTC
        CurrentSecs: 1674843580
    FlowSequence: 15752
    SourceId: 0
    FlowSet 1
        FlowSet Id: (Data) (265)
        FlowSet Length: 136
        Flow 1
            Flow Id: 58301081
            SrcAddr: 118.42.a.b (118.42.a.b)
            SrcPort: 61349
            InputInt: 3
            DstAddr: 217.17.c.d (217.17.c.d)
            DstPort: 3392
            OutputInt: 5
            Protocol: 6
            IPv4 ICMP Type: 0
            IPv4 ICMP Code: 0
            Post NAT Source IPv4 Address: 118.42.a.b (118.42.a.b)
            Post NAT Destination IPv4 Address: 192.168.20.5 (192.168.20.5)
            Post NAPT Source Transport Port: 61349
            Post NAPT Destination Transport Port: 3389
            Firewall Event: Flow deleted (2)
            Extended firewall event code: Unknown (2038)
            Observation Time Milliseconds: Jan 27, 2023 18:19:39.113000000 UTC
            Initiator Octets: 1324
            Responder Octets: 1250
            Unknown Field Type: Type 298: Value (hex bytes): 00 00 00 00 00 00 00 09
            Unknown Field Type: Type 299: Value (hex bytes): 00 00 00 00 00 00 00 07
            Ingress ACL ID: e1428d5668d5bd8d00000000
            Egress ACL ID: 000000000000000000000000
            AAA username:
            StartTime: Jan 27, 2023 18:19:35.613000000 UTC
        Padding (2 bytes)
    FlowSet 2
```

In /var/log/messages i can see:
```
Unknown flow source: 'Y.Y.Y.Y'
Skip UDP packet. Ignored packets so far 48 packets
```
Only empty files are created in `/netflow/77` (no packets inside, all with fixed size ~200B).

Why ?
On the same host i have many other instances of nfcapd (running various versions) capable of receiving Netflow v9 from other various devices. So the problem is only with ASA NSEL for all versions of nfcapd.

I have found a past issue: https://github.com/phaag/nfdump/issues/115 and it seems that i should be able to receive + store those correctly.

The above error seems to be caused at https://github.com/phaag/nfdump/blob/cc8680e9772dcd3873d08f950110ed20d1e20904/src/collector/collector_inline.c#L119 - but i can not draw any conclusions here :(
Is it a bug ? How to troubleshoot it ?

Thanks for all the support, really do appreciate your software !

**Comment by phaag** [comment]
Many thanks for reporting this issue. I don't see a reason, why it should not work. Would it be possible for you to send me a pcap - actually what you send to the collector - worth a few minutes? I'd happily have a look, why it does not collect the flows. Send it to my email in the AUTHORS file.

**Comment by johnelisity** [comment]
hell @phaag - many thanks for the prompt response. While preparing pcaps for you i have noticed that my host is sending ICMP echo unreachable for those NetFlow packets. After investigating those it appeared that my iptables PREROUTING entries did not work correctly (i internally redirect to a different port) because i have no rerun famous "conntrack --flush" (causing to refresh NAT entries which are super static for NetFlow).

Summary: nfcapd is working perfectly fine, it was a mistake in my networking config, thanks a lot !

**Comment by phaag** [comment]
Fine! Nice to hear it works 🤗. Enjoy nfdump and have fun! 😉
