### ISSUE TITLE
Include new fields on JSON output when using GeoDB

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#402]
JSON output currently does not includes GeoDB enriched data fields.

Important fields which are missing on JSON's output:

- AS Number
- AS Name
- Country
- City
- Lat/Long

Can we have these?

**Comment by phaag** [comment]
Sure! Give me some time.

**Comment by phaag** [comment]
Added geo location identical as in -o raw.

**Comment by gabrielmocan** [comment]
@phaag thanks for implementing that. But the AS information is not being shown:

root@63e140f4d812# NFGEODB=mmdb.nf nfdump -r sample -o raw
Flow Record: 
  ...
  src as       =             264297
  dst as       =             22697
  ...

root@63e140f4d812# NFGEODB=mmdb.nf nfdump -r sample -o json
{
  ...
        "src_as" : 0,
	"dst_as" : 0,
  ...
}

**Comment by phaag** [comment]
Sorry - Added.
