### ISSUE TITLE
CSV merge strategy when building new GeoDB with geolookup tool

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#403]
@phaag it seems that the default merge strategy for geolookup tool is set to "recurse" -- meaning that if we add a network to MaxMind's CSV that is smaller than the bigger network which the smaller one is contained, it will translate to the bigger one.

Can we have a flag to the geolookup tool to define the desired merge strategy based on MaxMind's official options?

Example:

-m, --merge <none | toplevel | recurse>
      the merge strategy to use when inserting entries that conflict.
        none     => no merge; only replace conflicts.
        toplevel => merge only top-level keys.
        recurse  => recursively merge.
        
Thanks in advance.

**Comment by phaag** [comment]
Right now, this does not work by design. I need to check how to handle overlaps best.

**Comment by gabrielmocan** [comment]
@phaag as I moved to go-nfdump as default reader, this issue here it's not really a problem anymore to me. Feel free to close this issue, as I think it's a very specific use-case.

**Comment by phaag** [comment]
put on todo stack.
