### ISSUE TITLE
Stuck adding source IP address selection to nfreplay

### ISSUE THREAD

**Issue by borjam** [phaag/nfdump#404]
Hi,

I am adding support for the specification of a source IP address to nfreplay.

It should be easy (adding a -S ip.addr parameter, doing the proper bind() after creating the socket, etc) but I am a bit mystified  about this:

Looking at send_net.c:

```
while (res) {
        sockfd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
        if (sockfd < 0) {
            LogError("socket() error: could not open the requested socket: %s", strerror(errno));
        } else {
            // socket call was successsful
            if (connect(sockfd, res->ai_addr, res->ai_addrlen) < 0) {
                // unsuccessful connect :(
                LogError("connect() error: could not open the requested socket: %s", strerror(errno));
                close(sockfd);
                sockfd = -1;
            } else {
                // connect successful - we are done
                close(sockfd);
                // ok - we need now an unconnected socket
                sockfd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
                break;
            }
        }

```
So, if I understand correctly, this is what happens here:

socket()
connect()
if connect() was successful, **close it and create a new socket**. 

Indeed the comment says "ok - we need now an unconnected socket"

May I ask why? I didn't notice this at first and I added the bind() call right after the first socket(). 

I see if I comment out the close() and new socket() call it complains it can't send because the socket is already
connected. 

Shouldn't that connect() be removed after all? Legacy code sticking there? ;)

Thanks!

**Comment by phaag** [comment]
Next year is the 20th anniversary of nfdump. Therefore, you are right - some parts of the code are already a bit older. However, I try to do my best to update old code, which lacks functionality or security. 

The code in send_net.c did a good job and I can explain you why it is, as it is:
With UDP sockets, you can send data on a connected or unconnected socket:
connected:
```
socket (socket.AF _INET, socket.SOCK_ DGRAM)
connect (('1.1.1.1', 53))
send (b"hello world")
```
or unconnected:
```
socket. socket (socket.AF _INET, socket.SOCK DGRAM)
sd. sendto (b"hello world", ('1.1.1.1', 53))
```
There are advantages and disadvatages for either way you can send data. `sendto` used to be way for UDP, `send` for TCP. These days both ways work. As `sendto` is finally used in nfreplay, this requires an unconnected socket.  If you use the connect call while opening the socket, you may check, if this connection could work, to trap all possible errors, when setting the network connection and before sending actual data. Furthermore, the code should compile and work across the landscape os many *nix platforms. Even this is a challenge on its own, not only, that it compiles on different platforms but also behaves alike.
That's the reason, why the code is, as it is :) But as I said, I am always ready to improve.

**Comment by borjam** [comment]
> On 2 Feb 2023, at 10:50, Peter Haag ***@***.***> wrote:
> 
> 
> Next year is the 20th anniversary of nfdump. Therefore, you are right - some parts of the code are already a bit older.
> However, I try to do my best to update old code, which lacks functionality or security.

Of course, not criticizing at all! I really depend on good oldie nfdump! ;)

> The code in send_net.c did a good job and I can explain you why it is, as it is:
> With UDP sockets, you can send data on a connected or unconnected socket:
> connected:
> socket (socket.AF _INET, socket.SOCK_ DGRAM)
> connect (('1.1.1.1', 53))
> send (b"hello world")
> 
> or unconnected:
> socket. socket (socket.AF _INET, socket.SOCK DGRAM)
> sd. sendto (b"hello world", ('1.1.1.1', 53))

Yes, what I found puzzling is this:

1- Create a socket

2- Obtain the IP address using getaddrinfo() (in the case of a hostname it might return a list)

3- Connect it

4- IF connection has been successful, destroy the socket, create a new one and return it

5- Otherwise iterate to the next address in the list and repeat the process

> 
> There are advantages and disadvatages for either way you can send data. sendto used to be way for UDP, send for TCP. These days both ways work. As sendto is finally used in nfreplay, this requires an unconnected socket. If you use the connect call while opening the socket, you may check, if this connection could work, to trap all possible errors, when setting the network connection and before sending actual data. Furthermore, the code should compile and work across the landscape os many *nix platforms. Even this is a challenge on its own, not only, that it compiles on different platforms but also behaves alike.
> That's the reason, why the code is, as it is :) But as I said, I am always ready to improve.

Understood of course!

I am implementing the source address selection which calls bind() on the socket after creating it. I have made a simple test and it
works, at least on FreeBSD. Anyway it’s socket programming 101 :)



Pull request coming soon!

Thank you very much,





Borja.
