### ISSUE TITLE
Master branch won't compile on non Linux systems / include issues

### ISSUE THREAD

**Issue by borjam** [phaag/nfdump#407]
There is an include file problem in some new files that won't compile on non Linux systems.

Linux standard library header files usually include all the files they need, which doesn't happen on
more traditional systems such as FreeBSD.

Right now it affects

- src/collector/repeater.c
- src/collector/nfnet.c

/usr/include/sys/types.h should be included at least **before** /usr/include/netinet/ip.h and, in the case of nfnet.c before nfnet.h itself.

Actually, regarding nfnet.c, wouldn't it be better to include "nfnet.h" **after** the system include files?

**Comment by phaag** [comment]
I try to stick to the recommended coding style:

For example in a project  `baz.c` is the order as follows:

```C
#include "bar/baz.h"

#include <system/headers.h>

#include "local/deps/header.h"

#include "project/other/header.h"
```

This means the order of including headers:

- Related headers
- A-BLANK-LINE
- C system headers
- A-BLANK-LINE
- C++ system headers
- A-BLANK-LINE
- Libraries headers
- A-BLANK-LINE
- Project headers

There is more on: https://codingart.readthedocs.io/en/latest/c/HeaderFile.html

If you use an IDE such VS-Code, then it arranges the header automatically in that order. Of course, I guess there is no absolute truth - and I know others may have other opinions on that. At least each `.h` file should have an include fence and should self compile without errors, which means all types referred in a header file should be included as well.

I need to check with FreeBSD, if there is an issue. 

Remember, what I said on an other place? To make it compile on all *nix is often as complicated as writing the code :)

**Comment by phaag** [comment]
It seems to be a FreeBSD issue. The FreeBSD header file `netinet/ip.h` does not include `sys/types.h` although it uses u_char. Other BSDs compile, such as OpenBSD or DragonFly.
I fixed it with a configure test.

**Comment by borjam** [comment]
Hmm seems the other *BSDs adopted the Linux custom of include files including their dependencies as well. As far as I know it wasn´t the case before!


And yes, making stuff compile on lots of systems is tricky, you are right!

**Comment by phaag** [comment]
True - but I would say, this was back in times of ANSI C and is independent of *BSD or Linux. These days it is good practice to include it's own dependancies. Specifically this makes the code much more portable. 
Btw. I am also a BSD guy and the code is more related to BSDs. :)
