### ISSUE TITLE
nfdump show wrong "event time" when list flows

### ISSUE THREAD

**Issue by alsinitsa** [phaag/nfdump#409]
Hello.
nfdump show wrong event time when listing flows:
![изображение](https://user-images.githubusercontent.com/35499704/217725199-baf21747-c0c8-4aa4-8076-1656a2c2e537.png)

but when showing top flows -- event time correct:
![изображение](https://user-images.githubusercontent.com/35499704/217725395-2bb9db35-7f90-48de-a85e-f144cded1b32.png)

nfdump: Version: 1.7.1-33f9a6a NSEL-NEL, Date: 2023-02-07 14:57:41 +0100

**Comment by thezoggy** [comment]
if time bucket is 0530 and duration is 1h50m..   first seen time looks to be correct?

**Comment by alsinitsa** [comment]
If I list flows with time window -- event time looks correct
![изображение](https://user-images.githubusercontent.com/35499704/217999179-49462d44-c71e-4ec6-a5f8-5ca8dfe8ec31.png)

**Comment by phaag** [comment]
are you using the latest github master branch?

**Comment by alsinitsa** [comment]
```
[account0078@nfsen nfdump]$ git branch --show-current
master
[account0078@nfsen nfdump]$ git show -s
commit 33f9a6ac93a6615f106e050d3b618147d477d204 (HEAD -> master, origin/master, origin/HEAD)
Author: Peter Haag <peter@people.ops-trust.net>
Date:   Tue Feb 7 14:57:41 2023 +0100

    Update README
```

**Comment by phaag** [comment]
Could you please identify the source, of the flows with the wrong event times and capture a pcap file of the traffic, sent to the collector for about a few minutes. Please send me that pcap to my mill in the AUTHORS file. I need to debug that.

**Comment by borjam** [comment]
I my case, with both nfsen and nfdump cloned from master today I see the same effect.

The exporters are Mikrotik routers. It is also happening for SFlow flows exported from Aruba switches.

The flows seem to be fine, SFlow JSON example  (nfdump -o json)

```
[
{
	"type" : "FLOW",
	"sampled" : 1,
	"export_sysid" : 1,
	"first" : "2023-02-15T10:39:04.253",
	"last" : "2023-02-15T10:39:04.253",
	"received" : "2023-02-15T10:39:04.253",
	"in_packets" : 4096,
	"in_bytes" : 286720,
	"proto" : 6,
	"tcp_flags" : "...A....",
	"src_port" : 58948,
	"dst_port" : 22,
	"src_tos" : 0,
	"src4_addr" : "192.XXXX",
	"dst4_addr" : "192.168.1.205",
	"src_geo" : "",
	"dst_geo" : "",
	"input_snmp" : 1,
	"output_snmp" : 10,
	"src_mask" : 0,
	"dst_mask" : 0,
	"src_net" : "",
	"dst_net" : "",
	"fwd_status" : 0,
	"direction" : 0,
	"dst_tos" : 0,
	"src_vlan" : 1,
	"dst_vlan" : 1,
	"src_as" : 0,
	"dst_as" : 0,
	"ip4_router" : "192.168.1.196",
	"in_src_mac" : "08:55:31:XXXXXX",
	"out_dst_mac" : "a0:1d:48:XXXXXXX",
	"in_dst_mac" : "00:00:00:00:00:00",
	"out_src_mac" : "00:00:00:00:00:00",
	"label" : "<none>"
},

```

but doing  nfdump -r nfcapd.202302151039 I see this:

```
Event time               Event  XEvent Proto      Src IP Addr:Port          Dst IP Addr:Port     X-Src IP Addr:Port        X-Dst IP Addr:Port   In Byte Out Byte
1970-01-01 01:00:00.000 INVALID  Ignore TCP     192.XXXXXXX:58948 ->    192.168.1.205:22             0.0.0.0:0     ->          0.0.0.0:0       286720        0
1970-01-01 01:00:00.000 INVALID  Ignore 0              0.0.0.0:0     ->          0.0.0.0:0              0.0.0.0:0     ->          0.0.0.0:0       262144        0
Summary: total flows: 2, total bytes: 548864, total packets: 8192, avg bps: 152956, avg pps: 285, avg bpp: 67
Time window: 2023-02-15 10:39:04 - 2023-02-15 10:39:32
Total flows processed: 2, passed: 2, Blocks skipped: 0, Bytes read: 416
Sys: 0.0026s User: 0.0000s Wall: 0.0007s flows/second: 2963.1 Runtime: 0.0007s

```

**Comment by borjam** [comment]
Interesting. Specifying an output format such as "line", "extended", "json" etc makes it work. It only fails when no output format is specified.

**Comment by borjam** [comment]
Mine was compiled with nsel support.

Looks like the nsel support makes the "auto" output format selection fail for nfdump when printing timestamps.

**Comment by phaag** [comment]
The ”auto” output shows the event time when compiled with NSEL/NEL option. If you overwrite that with “line” oder “extended” you see the flow time. This actually means the exporters does not export the event time but the flow time.

**Comment by borjam** [comment]
> The ”auto” output shows the event time when compiled with NSEL/NEL option. If you overwrite that with “line” oder “extended” you see the flow time. This actually means the exporter does not properly export the event time but the flow time.

Understood, so there are  two separate issues here!

First: Is it correct that nfdump compiled with NSEL options requires **all the sources** to support NSEL? In my test bed example I have sFlow sources for which NSEL doesn't make sense at all and a couple of routers (Mikrotik) that export flows with the NSEL option.

I think the most sensible approach for the automatic format would be to display the flow timestamps in case the even timestamps were not available.

The second is trickier, dealing with buggy/poor implementations of NSEL like Mikrotik's. They are using the X- IP address fields but they are not including any event related fields. 

Anyway, given that it is an "auto" format, don't you think it would be a lesser evil to display the flow start timestamp in both cases when the event timestamp is not available?

**Comment by borjam** [comment]
Or maybe it's better to keep it simple and POLA compliant ;)

The trivial solution is to keep "line" as the default output format and having the user choose "nsel" or whatever when the NSEL related fields (misused at least by Mikrotik to report NAT flows).

**Comment by phaag** [comment]
@alsinitsa 
I assume you have a mixed environment with flows and events (ASA devices). I assume msk_buy is a plain flow source. Most likely the latest github repo should work for your case. 
Please note, that all your pictures show different flows/events even it's only one file, because they get either linearly printed, calculated as stats or printed on a different collector host. If you have a mix of flows and events, please carefully select, which output format you want to see and apply it accordingly in order to get the correct interpretation.

**Comment by phaag** [comment]
@borjam  - moved your comments to discussion #420
