### ISSUE TITLE
nfcapd -s sample rate and samplingPacketInterval/samplingPacketSpace

### ISSUE THREAD

**Issue by thezoggy** [phaag/nfdump#410]
to follow up on: https://github.com/phaag/nfdump/issues/377

in our nfsen sources, we normally use the optarg and define `-s 10000` which from what I understand tells nfcapd that it should use a 10k sample rate by default unless flow template says otherwise. 

testing out latest nfdump and two nokia 7750 routers running same code (as we reported previous issue) they do the whole samplingPacketInterval / samplingPacketSpace instead of samplingInterval. 

```
    'dummy_router'    => { 'port' => '40172', 'col' => '#6633EE', 'type' => 'netflow', 'optarg' => '-s 10000' },
    'dummy_router2'    => { 'port' => '40169', 'col' => '#6633EE', 'type' => 'netflow' },
```

nfdump: Version: 1.7.1

with `-s 10000`
```
nfdump -E /data/nfsen/profiles-data/live/dummy_router/2023/02/09/nfcapd.202302091825
Exporters:

SysID: 1, IP:    100.100.0.169, version: 10, ID:  0, Sequence failures: 2, packets: 219, flows: 1935
    Sampler: Static default Sampler: algorithm: 0, packet interval: 1, packet space: 9999
```
```
nfdump -R /data/nfsen/profiles-data/live/dummy_router/2023/02/09/nfcapd.202302091825 | head
Date first seen             Duration     Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
2023-02-09 18:24:44.614     00:00:00.000 TCP        19x.xx.x6.2:57258 ->  1xx.xx.x29.140:443      10000   400000     1
```

without the optarg, no sampler...  and packets = 1
```
nfdump -E /data/nfsen/profiles-data/live/dummy_router2/2023/02/09/nfcapd.202302091825
Exporters:

SysID: 1, IP:    100.100.0.156, version: 10, ID:  0, Sequence failures: 2, packets: 972, flows: 8073
```
```
nfdump -R /data/nfsen/profiles-data/live/dummy_router2/2023/02/09/nfcapd.202302091825 | head
Date first seen             Duration     Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
2023-02-09 18:24:44.321     00:00:00.000 UDP   2001:41..:2:0:53.47329 -> 2001:41..0:2:0:5.2823         1      122     1
```
tried various buckets but nothing.  

so it would appear that the embedded sampling rate logic is not working? 

side note, i noticed that if i change the optarg in nfsen.conf and tell nfsen to reconfig it says there are no changes. the only way to get it to actually use the new values is to stop/start nfsen so it kills the collector and starts it up with the new values. is there a more efficient way to modify the optarg values for a channel? (as a restart takes a really long time due to how many devices we have)

**Comment by phaag** [comment]
I don't see your point. If you add a default sampling, it's added and packets are 10000, if not packets is 1. Sampling works as expected.

Side note: reconfig is for reconfiguring the sources in nfsen. It has nothing to do with the collector parameters. If you change optarg, you need to restart the collectors, as this optional arg is in fact a command line variable

**Comment by thezoggy** [comment]
i was under the impression that it should know the sampling automatically from the sampler?  

as having a juniper router setup the same way (which does do samplingInterval)
```
    'junos_router'    => { 'port' => '40332', 'col' => '#6633EE', 'type' => 'netflow', 'optarg' => '-s 10000' },
```

we see it has two samplers, the 'default' one and then the one it gleams from the template
```
nfdump -E /data/nfsen/profiles-data/live/junos_router/2023/02/09/nfcapd.202302091825
Exporters:

SysID: 1, IP:    100.000.0.153, version: 10, ID: 525314, Sequence failures: 70, packets: 6533, flows: 19775
    Sampler: Static default Sampler: algorithm: 0, packet interval: 1, packet space: 9999
    Sampler: Generic Sampler: algorithm: 0, packet interval: 1, packet space: 9999
SysID: 2, IP:    100.000.0.153, version: 10, ID: 524288, Sequence failures: 62, packets: 23402, flows: 92635
    Sampler: Static default Sampler: algorithm: 0, packet interval: 1, packet space: 9999
    Sampler: Generic Sampler: algorithm: 0, packet interval: 1, packet space: 9999
SysID: 3, IP:    100.000.0.153, version: 10, ID: 524544, Sequence failures: 70, packets: 21946, flows: 86803
    Sampler: Static default Sampler: algorithm: 0, packet interval: 1, packet space: 9999
    Sampler: Generic Sampler: algorithm: 0, packet interval: 1, packet space: 9999
```

**Comment by thezoggy** [comment]
ok so we are same page, i was pointing out how the nokia not have the 'generic sampler'. i assume its because it used that newer method of samplingPacketInterval/samplingPacketSpace rather than send the legacy samplingInterval.

**Comment by phaag** [comment]
well - nfcapd internally converts older sampling models with a simple rate into the new model. The same applies with you -s ootion.

**Comment by thezoggy** [comment]
if a device sends  `samplingInterval` you dont have to use -s it does know the sampling rate. (in this example 10k) and all just works.

if a device does not send `samplingInterval` but only the newer  `samplingPacketInterval` + `samplingPacketSpace` you have to use the -s option to set the sampler rate otherwise its going to use 1.  

which is the same issue we noted before in #377 

As that was closed I thought this was fixed, but from what I'm understanding the only thing from that change was the output format of -E to denote how the sampling rate is done?

**Comment by phaag** [comment]
377 has been fixed. If your device uses a different model, I would need a pcap of the data sent to the collector. You can send it to me to my email in the AUTHORs file. Then I can have a look.

**Comment by thezoggy** [comment]
> 377 has been fixed. If your device uses a different model, I would need a pcap of the data sent to the collector. You can send it to me to my email in the AUTHORs file. Then I can have a look.

377 is same device as before, i'm just testing the newer version of nfdump to validate that it was fixed..  this came about because we wanted to change our sampling rate from 10k to 5k and noticed that nfsen wasn't reading the embedded rate which lead to us reporting the issue to you and arbor (as they also default to 1 if samplingInterval wasnt sent, but have now since released a patch to handle when a device uses `samplingPacketInterval` + `samplingPacketSpace` like nokia sros 21.x+ ) .

sure thing I'll send you a pcap shortly.

**Comment by phaag** [comment]
It looks like the device does not send a sampler ID. I added a fix to interpret this as a general sampler, even if the new tags 305, 306 are used. Hope this fixes the issue.

**Comment by thezoggy** [comment]
pulled latest, built+installed:
```
nfdump -V
nfdump: Version: 1.7.1-d46474b, Date: 2023-02-11 15:25:24 +0100
```

with source defined as:
```
    'dummy_router2'    => { 'port' => '40156', 'col' => '#99CC33', 'type' => 'netflow', 'optarg' => '-s 5000' },
```

can confirm now it is getting sampler from template now
```
nfdump -E /data/nfsen/profiles-data/live/dummy_router2/2023/02/11/nfcapd.202302111750
Exporters:

SysID: 1, IP:    100.100.0.156, version: 10, ID:  0, Sequence failures: 17, packets: 829, flows: 5865
    Sampler: Static default Sampler: algorithm: 0, packet interval: 1, packet space: 4999
    Sampler: Generic Sampler: algorithm: 1, packet interval: 1, packet space: 4999
```

thanks!

**Comment by phaag** [comment]
The algorithm is basically tag 304. It has no meaning for nfdump and is pri ted for user convenience. The value depends on your device and may be described in the manual.
