### ISSUE TITLE
filter by asn - now requires geo db?

### ISSUE THREAD

**Issue by thezoggy** [phaag/nfdump#412]
When testing newer nfsen/nfdump I noticed that we can no longer filter by asn:
```
nfdump -V
nfdump: Version: 1.7.1-d46474b, Date: 2023-02-11 15:25:24 +0100

nfdump -M /data/nfsen/profiles-data/live/dummy_router -T -r 2023/02/13/nfcapd.202302132225 -n 10 -s ip/flows 'dst as 16509'
Can not filter according geo elements without a geo location DB
```

nfdump was built with (both our older instance and this new one are built using same flags, however we can filter by asn just fine on 1.6.x):
```
./configure --enable-nfprofile --enable-nftrack --enable-readpcap --enable-nfpcapd --enable-sflow
```

**Comment by phaag** [comment]
Ohh - I see. Fixed.

**Comment by thezoggy** [comment]
can confirm it works now! thanks

**Comment by phaag** [comment]
Make sure you run the code from the latest master repo. The bug has been fixed. A next release will be due by the end of April.

You don't need geo lookup for ASN filtering. If you don't need the country codes, you don't need maxmind at all, if you have ASN numbers I your flows.

**Comment by wallacemariadeandrade** [comment]
> Make sure you run the code from the latest master repo. The bug has been fixed. A next release will be due by the end of April.
> 
> You don't need geo lookup for ASN filtering. If you don't need the country codes, you don't need maxmind at all, if you have ASN numbers I your flows.

I have used latest release, not from master repo so I think that's the problem. Is there a way to upgrade it? Or I have to recompile everything?

**Comment by phaag** [comment]
Just get the code from the master repo and compile it the same way as you did for the release. If you install the new binaries, you are fine. There is no change for the data.

**Comment by wallacemariadeandrade** [comment]
Pretty good! Really thanks, bro. You've done a very good job.
