### ISSUE TITLE
nfcapd collector issue

### ISSUE THREAD

**Issue by CharlyBote** [phaag/nfdump#416]
I have a fresh install from scratch, with nfdump 1.7.1 and nfsen 1.3.8, but when nfsen starts, nfcapd gives an error.

Syslog report:
Feb 15 09:59:41 nfsen[50860]: Starting nfcapd:(ccr1036cs ccr1036np)path does not exist: -D Feb 15 09:59:41 nfsen[50860]: No valid directory: -D Feb 15 09:59:46 nfsen[50860]: : collector did not start - see logfile 
CLI
 ./nfsen start Starting nfcapd:(ccr1036cs ccr1036np)path does not exist: -D No valid directory: -D : collector did not start - see logfile  Starting nfsend.

Config File attached

[nfsen.conf.txt](https://github.com/phaag/nfdump/files/10755764/nfsen.conf.txt)

Could help me with this issue?

Thanks

**Comment by phaag** [comment]
This is an nfsen issue. Please do not use nfsen-1.3.8 with nfdump-1.7.x. If you have issues with nfsen, open an issue at the other repo. Use nfsen-1.3.9
Thanks.
