### ISSUE TITLE
nfcapd and ipfix via erspan

### ISSUE THREAD

**Issue by atbohmer** [phaag/nfdump#417]
Hello,

Is it possible to extract ipfix flow data from an erspan datalink? So we are filtering out an ipfix netflow stream and send it over a routed network via an erspan. Is nfcapd capable to read this, or should we convert the erspan data on the Linux box to the origin ipfix data and use that as an ingest for nfcapd?

Cheers,
Andre

**Comment by phaag** [comment]
Do you have any link to a  erspan datalink reference?

**Comment by atbohmer** [comment]
Should I email you a pcap file? Bit so sensitive data to upload in this issue.

**Comment by phaag** [comment]
That would be awesome! Thanks!

**Comment by phaag** [comment]
@atbohmer - Any update on the pcap file? It would be very appreciated.

**Comment by atbohmer** [comment]
Had a week of leave due to carnaval ;) Coming week working again so will let you know!

Op 25 feb. 2023 om 17:27 heeft Peter Haag ***@***.***> het volgende geschreven:

﻿

@atbohmer<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fatbohmer&data=05%7C01%7Candre.tenbohmer%40wur.nl%7C05b76252f0ed46393db808db174d1ea6%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C638129392231358812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rUnjfCD%2BWRbAlUsm5O2%2BcCnTjBX9SXyykzUoqMIOcu0%3D&reserved=0> - Any update on the pcap file? It would be very appreciated.

**Comment by atbohmer** [comment]
[erspan_ipfix.pcap.gz](https://github.com/phaag/nfdump/files/10851100/erspan_ipfix.pcap.gz)

**Comment by phaag** [comment]
While studying ERSPAN, I learned, that this is basically a GRE/VLAN protocol. The proper way would be to terminate the GRE tunnel at the kernel level and feed the unwrapped traffic into nfcapd. 
Now we have two options:
1. Unwrap the vlan also on kernel level and bind the traffic on a virt. interface with the final IP. No changes would be required for nfcapd.
2. Modify nfcapd to listen at the gre tunnel end point. All traffic on the gre endpoint is considered as ipfix stream.

Could you elaborate a bit more on your setup and ideas? 
Meanwhile I update the pcap reader to digest ERSPAN data.

**Comment by atbohmer** [comment]
Great, well suricata is able to ingest erspan traffic so I was interested if this is possible with nfdump software. Our idea is to span Cisco DNA traffic, place a filter on it regarding ipfix traffic and forward this to our netflow Linux server. Both 1 and 2 are a viable solution, but 2 makes our setup on the netflow server not that exotic.

**Comment by phaag** [comment]
With the latest master update, nfcapd can also ingest erspan traffic, if data is provided via pcap reader. The question is only, do you need to snoop on an interface or do you want to feed pcaps.

**Comment by atbohmer** [comment]
Snoop is the need, thanks.

From: Peter Haag ***@***.***>
Date: Tuesday, 14 March 2023 at 15:09
To: phaag/nfdump ***@***.***>
Cc: Bohmer, Andre ten ***@***.***>, Mention ***@***.***>
Subject: Re: [phaag/nfdump] nfcapd and ipfix via erspan (Issue #417)

With the latest master update, nfcapd can also ingest erspan traffic, if data is provided via pcap reader. The question is only, do you need to snoop on an interface or do you want to feed pcaps.

**Comment by phaag** [comment]
The latest master repo contains an updated cap reader to listen on an interface specified by -d.
To enable this feature, run configure with argument --enable-readpcap

**Comment by phaag** [comment]
Feel free to re-open in case of problems.
