### ISSUE TITLE
unable to retreive flow records

### ISSUE THREAD

**Issue by vmanju123** [phaag/nfdump#418]
I have enabled netflow on 2 of my 3650 switches (IP 192.168.1.207 and 192.168.1.202), both exactly same model. Exporting to UDP port 9992 for netflow collector.
running IPFIX and exact same record template on both the switches. below is the link to download the sample pcap file which was captured using tcpdump on the collector linux machine to observe the packets arriving at the collector machine

https://drive.google.com/file/d/1Vu7nF7YbMoxdz-7anDb9_NDYi_nHJl51/view?usp=sharing

Running nfcapd and nfdump latest version for netflow collection on a linux machine for both the switches 

process looks like below
root     2637469 2637454  0 16:57 pts/1    00:00:07 ./nfcapd -p 9992 -t 300 -n Switch1 192.168.1.207 /usr/local/td/netsense/flow_data/192.168.1.207 -n Switch2 192.168.1.202 /usr/local/td/netsense/flow_data/192.168.1.202

i can get flow records recorded only from 192.168.1.207 but not 192.168.1.202

Not sure what i am doing wrong
the only minor difference i see in flow records is that in 192.168.1.202 there is no 2 bytes enterprise private entry at the beginning of the flow which is there from records in 192.168.1.207. not sure how that matters and if there is any control on the switch to change, but the collector would not pick up any records from 192.168.1.202

any help is appreciated

**Comment by phaag** [comment]
In your pcap provided, you have 533 flows for 192.168.1.207 and 3 flows for 192.168.1.202. Although the difference is substantial there are flows from  192.168.1.202.

You can test it yourself by adding the configure flag `--enable-readpcap` and run the following command:

`nfcapd -f test114.cap -n Switch1,192.168.1.207,tmp1 -n Switch2,192.168.1.202,tmp2`

you will see:

```
Add flow source: ident: Switch1, IP: 192.168.1.207, flowdir: tmp1
Add flow source: ident: Switch2, IP: 192.168.1.202, flowdir: tmp2
Setup pcap reader
...
Startup nfcapd.
Process_ipfix: New ipfix exporter: SysID: 1, Observation domain 16777217 from: 192.168.1.207
Process_ipfix: New ipfix exporter: SysID: 2, Observation domain 16777217 from: 192.168.1.202
Ident: 'Switch1' Flows: 533, Packets: 1793, Bytes: 242064, Sequence Errors: 28, Bad Packets: 0
Ident: 'Switch2' Flows: 3, Packets: 3, Bytes: 250, Sequence Errors: 0, Bad Packets: 0
```

Did you check for any ipfilter or SeLinux rules?

**Comment by phaag** [comment]
Any update on that?

**Comment by phaag** [comment]
Seems no update on this issue. I close it for now. Feel free to reopen, if you have any news.
