### ISSUE TITLE
nftrack [regression]: -r <file> aborts if <file> is not in current directory

### ISSUE THREAD

**Issue by candlerb** [phaag/nfdump#432]
Running nfsen PortTracker plugin with nfdump 1.7.1 and nfsen 1.3.9, the graphs do not build, and I see the following errors in syslog:

```
Mar  6 16:50:15 noc nfsen[15762]: /usr/local/bin/nftrack -L local3 -M /var/nfsen/profiles-data/live/bdr1 -r nfcapd.202303061645 -d /var/ports-db -A -t 202303061645 -s -p -w /var/ports-db/portstat.txt
...
Mar  6 16:50:15 noc nfsen[15762]: nftrack exited with value 255
Mar  6 16:50:15 noc nfsen[15762]: /usr/local/bin/nftrack -d /var/ports-db -S -p -w /var/ports-db/portstat24.txt
Mar  6 16:50:15 noc nfsen[15762]: nftrack exited with value 0
```

Using strace I see:

```
[pid 17817] newfstatat(AT_FDCWD, "/var/nfsen/profiles-data/live/bdr1", {st_mode=S_IFDIR|0775, st_size=58, ...}, 0) = 0
[pid 17817] newfstatat(AT_FDCWD, "nfcapd.202303061655", 0x7ffc5cec5f60, 0) = -1 ENOENT (No such file or directory)
[pid 17817] write(2, "path does not exist: nfcapd.202303061655\n", 41) = 41
[pid 17817] exit_group(255)             = ?
[pid 17817] +++ exited with 255 +++
```

The problem is that in nfdump 1.7, `-r nfcapd.202303061645` checks for the existence of that file in the current directory, and exits if it is not there. This defeats the "GuessSubDir" logic which happens later, in both old and new versions of nfdump, to build the full path (e.g. `/var/nfsen/profiles-data/live/bdr1/2023/03/06/nfcapd.202303061645`)

Compare nfdump 1.6.25 (extra/nftrack/nftrack.c):

```
                        case 'r':
                                rfile = strdup(optarg);
                                break;

...
        if ( Mdirs || Rfile || rfile ) {
                SetupInputFileSequence(Mdirs, rfile, Rfile);
```

with nfdump 1.7.1 (src/nfsen/nftrack.c):

```
            case 'r':
                if (!CheckPath(optarg, S_IFREG)) exit(255);       <<<<<< NOTE!
                flist.single_file = strdup(optarg);
                break;

...
    if (flist.multiple_dirs || flist.multiple_files || flist.single_file) {
        queue_t *fileList = SetupInputFileSequence(&flist);
```

Simply commenting out the line marked "NOTE!" appears to be sufficient to fix the problem.  (Alternatively, the logic could be changed to use GuessSubDir, but it would need to have parsed all arguments first to get the channeldir)

**Comment by phaag** [comment]
This bug felt victim of the wrong argument check.
