### ISSUE TITLE
Nfcapd's packet repeater doesn't seem to work

### ISSUE THREAD

**Issue by innogrey** [phaag/nfdump#433]
When -R option used, no packets are actually repeated. The problem seems to be occurring both with nfcapd-1.7.1 and 1.6.20 running on FreeBSD 13.1. It's a bit strange, since I'm 100% positive that at some point one of the previous versions was working just fine.

**Comment by phaag** [comment]
There was no change in 1.6.20 or any of the 1.6.x version regarding repeating. For 1.7.x I verified the repeater is working on FreeBSD 13 as expected. Did you check any firewalls or other rules, which could block outgoing traffic?

**Comment by phaag** [comment]
I close this issue, unless you have further details. Feel free to reopen, if you think, this is an nfdump issue.
