### ISSUE TITLE
Nfdump collecting interval

### ISSUE THREAD

**Issue by wallacemariadeandrade** [phaag/nfdump#437]
Documentation says:

> The data is organized in a time-based fashion. Every n minutes

> - typically 5 min - nfcapd rotates and renames the output file with the timestamp nfcapd.YYYYMMddhhmm of the interval e.g. nfcapd.200907110845 contains data from July 11th 2009 08:45 onward. Based on a 5min time interval, this results in 288 files per day.

Is there a way to configure this rotation time? I'd like to use 1 minute instead of 5, for example.

Thanks!

**Comment by rogerwh** [comment]
Hi! Sorry if i'm intruding ...

You can use the `-t` flag for change the interval in seconds of time for `nfcapd` command.

Example:

Create a file each minute
```
nfcapd -D -t 60 -S 2 -p 2055 -w /tmp/netflow/2055/flows
```

Create a file every two minutes

```
nfcapd -D -t 120 -S 2 -p 2056 -w /tmp/netflow/2056/flows
```

**Comment by phaag** [comment]
See answer from @rogerwh . Many thanks.
