### ISSUE TITLE
Nfanon and filter mode?

### ISSUE THREAD

**Issue by Igor-178** [phaag/nfdump#438]
Nfanon from nfdump version 1.7.x, built from source, does it support filter mode (stdin->nfanon->stdout)?

**Comment by phaag** [comment]
No - 1.7.x does not support filter mode. This is due to the changed file format.

**Comment by Igor-178** [comment]
Very sorry. The possibility of organizing flow processing in one pipe (nfdump -> nfanon -> nfreplay), was very convenient.
