### ISSUE TITLE
request/ selective anonymization

### ISSUE THREAD

**Issue by Igor-178** [phaag/nfdump#439]
I suggest considering the possibility of selective anonymization. For example, the source IP is anonymized, the others are not. Or other options via the nfanon setting. This can be useful in analyzing real traffic, while maintaining the privacy of the packet source.

**Comment by phaag** [comment]
Hmm .. not sure if this is useful. Finally you have a mix between real and anonymised IPs.

**Comment by Igor-178** [comment]
You're probably right. As I said above, I needed to implement a real traffic analysis case when the traffic source should remain anonymous. I can come up with a case for analyzing anonymized traffic from a real source. For other cases, a mixture of real and anonymized IP probably doesn't make sense.

**Comment by phaag** [comment]
For now, I would like to stick as it is.
