### ISSUE TITLE
tiny build issue in make: ../../ylwrap: line 176: yacc: command not found

### ISSUE THREAD

**Issue by aalku** [phaag/nfdump#442]
I think the `makefile` uses the `yacc` command and `./configure` does not check if it's installed.

`make` returned `../../ylwrap: line 176: yacc: command not found`

It was fixed with: `sudo dnf install byacc` in almalinux 8.

**Comment by thezoggy** [comment]
the list of required packages varies a little bit by os, `byacc` for example is one that you can infer needs to be installed via the ubuntu docker
https://github.com/phaag/nfdump/blob/master/extra/docker/Dockerfile.ubuntu#L25

but even then, this doesnt cover if you use nfsen or certain plugins..  or options. 

here are my notes for for what i installed in ubuntu for example:

### install requirements for nfdump
```
sudo apt-get install git wget unzip man apt-utils dialog pkg-config libtool autoconf autogen bison byacc flex make libpcap-dev libbz2-dev rrdtool bzip2
```
 
### install requirements for nfsen (nfprofile/nftrack)
```
sudo apt-get install  librrdp-perl librrds-perl librrd-dev liburi-perl
```
 
### install requirements for nfsen/bin scripts - nfsen alerting breaks if perl is compiled with threading
```
sudo apt-get install libdbi-perl
```

**Comment by phaag** [comment]
It checks for `bison` or `yacc`, whereas `bison` is preferred. It uses the standard autoconf macro AC_PROG_YACC. Therefore you should be safe.
