### ISSUE TITLE
Include source name and/or source IP in "Unexpected record count in header" error

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#447]
Hi Pete, how you doing?

It is possible to include source's name/IP in the following error message from nfcapd?

`Process_v5: Unexpected record count in header: xxxxxx. Abort v5/v7 record processing`

I have a lot of exporters in this collector and I cant find whose is sending those bad packets.

Best,
Gabe.

**Comment by phaag** [comment]
Hey Gabe,
Thanks - busy, but ok. 
As of the record count - looking at the code, this number is limited to the number of max possible records in an ethernet frame. It's from good old times - 1500 bytes per frame.
I changed the code to be more dynamic and compare now against the size left in the input buffer. 
Could you please check with the master repo? If there are still too many records announced compared to the input buffer size, you get an error with the IP address of the exporter.

**Comment by phaag** [comment]
Very good! - at least from to nfdump point of view :)

**Comment by gabrielmocan** [comment]
Yeah, we removed the exporter as it is going to decommissioned soon. Most likely a firmware bug, but we won't bother with that as this device is going to be removed from customer's infrastructure. Thanks Pete for fast response.
