### ISSUE TITLE
flow filter not working

### ISSUE THREAD

**Issue by piualves** [phaag/nfdump#448]
The primitive filter 'flow comp num' (that is in the manual page) is not working as the nfdump do not even regognize the 'flow' as a correct syntax filter
![nfdump_screenshot](https://github.com/phaag/nfdump/assets/111385999/fe30b29c-03f9-4b88-a74f-afbd27a36858)

**Comment by phaag** [comment]
The correct term is `flows` not `flow`.
The man page has been updated.
