### ISSUE TITLE
Invalid values (bps, pps) in `pipe` output format for statistic mode.

### ISSUE THREAD

**Issue by piorek94** [phaag/nfdump#459]
### Problem:

Invalid values (bps, pps) in `pipe` output format for statistic mode.

### Enviroment

nfdump version: v1.7.2

OS: Debian 9.13 (stretch)

### Description:

Output for statistic in `long` format:
```bash
$ nfdump -n 1 -r file -s srcport/bps -o long
Top 1 Src Port ordered by bps:
Date first seen                 Duration Proto          Src Port    Flows(%)     Packets(%)       Bytes(%)         pps      bps   bpp
2023-08-15 15:14:15.514     00:00:29.504 any                 443     7780(35.1)   19.1 M(36.6)   23.6 G(52.1)   645747    6.4 G  1240

Summary: total flows: 22180, total bytes: 45.3 G, total packets: 52.1 M, avg bps: 12.3 G, avg pps: 1.8 M, avg bpp: 870
Time window: 2023-08-15 15:14:15 - 2023-08-15 15:14:45
Total flows processed: 22180, passed: 22180, Blocks skipped: 0, Bytes read: 3640464
Sys: 0.0040s User: 0.0080s Wall: 0.0097s flows/second: 2276289.2 Runtime: 0.0122s
```

Output for statistic in `pipe` format:
```bash
$ nfdump -n 1 -r file -s srcport/bps -o pipe
0|1692105255514|1692105285018|0|443|7780|19052126|23638159767|645747|2114512033|1240
```

Issue is related to `PrintPipeStatLine` function of `nfdump/src/nfdump/nfstat.c` file:
- variables `bps` and `pps` should be declared as `uint64_t`;
- variables `bps` and `pps` should be casted to `(long long unsigned)` in `printf` function.

### Expected behavior

Values of bps, pps should be proper in `pipe` output format for statistic mode.

**Comment by phaag** [comment]
Fixed in master repo.
Please note, that the pipe output format is deprecated and will get removed in future.
