### ISSUE TITLE
Compilation issue on Ubuntu LTS 16.04

### ISSUE THREAD

**Issue by ddurvaux** [phaag/nfdump#46]
Dear,

We compiling with nfpcapd support, I have an issue with a type 'sig_atomic_t'.

Configure set with option --enable-nfpcapd then make.
Make failed with the following error:
`gcc -DHAVE_CONFIG_H -I. -I..    -D_BSD_SOURCE -g -O2 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -MT nfpcapd-pcaproc.o -MD -MP -MF .deps/nfpcapd-pcaproc.Tpo -c -o nfpcapd-pcaproc.o `test -f 'pcaproc.c' || echo './'`pcaproc.c
In file included from pcaproc.c:72:0:
flowtree.h:112:2: error: unknown type name ‘sig_atomic_t’
  sig_atomic_t list_lock;
  ^
Makefile:1283: recipe for target 'nfpcapd-pcaproc.o' failed
make[3]: *** [nfpcapd-pcaproc.o] Error 1
make[3]: Leaving directory '/home/durvada/git/nfdump/bin'
Makefile:780: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/durvada/git/nfdump/bin'
Makefile:403: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/durvada/git/nfdump'
Makefile:335: recipe for target 'all' failed
make: *** [all] Error 2
`
Thanks for help!
Best regards,

David

**Comment by lucadistefano** [comment]
hi, I'm building on 16.04 (desktop) the project from master branch without errors .
I use:
autoreconf -i

./configure \
        --enable-nfprofile \
        --enable-nftrack \
        --enable-sflow \
        --enable-nsel \
        --enable-readpcap \
        --enable-nfpcapd

**Comment by phaag** [comment]
Fixed. close issue.
