### ISSUE TITLE
Invalid statistic values for bidirectional elements.

### ISSUE THREAD

**Issue by piorek94** [phaag/nfdump#460]
### Problem:

Invalid statistic values for bidirectional elements.

### Enviroment

nfdump version: v1.7.2

OS: Debian 9.13 (stretch)

### Description:

Statistics are calculated incorrectly for bidirectional elements (this ones were detected - not sure if others are affected).

_bidirectional elements: elements which has direction expression but is allowed to gather statistic without it, ex. ip, port, as, vlan._

Example outputs:
```bash
$ nfdump -n 1 -r file -s as
Top 1 AS ordered by flows:
Date first seen                 Duration Proto                AS    Flows(%)     Packets(%)       Bytes(%)         pps      bps   bpp
2023-08-15 15:14:15.514     00:00:29.504 any                   0    44360(200.0)  104.2 M(200.0)   90.7 G(200.0)    3.5 M   24.6 G   870

Summary: total flows: 22180, total bytes: 45.3 G, total packets: 52.1 M, avg bps: 12.3 G, avg pps: 1.8 M, avg bpp: 870
Time window: 2023-08-15 15:14:15 - 2023-08-15 15:14:45
Total flows processed: 22180, passed: 22180, Blocks skipped: 0, Bytes read: 3640464
Sys: 0.0000s User: 0.0080s Wall: 0.0064s flows/second: 3474886.6 Runtime: 0.0068s
```

```bash
$ nfdump -n 1 -r file -s vlan
Top 1 Vlan ordered by flows:
Date first seen                 Duration Proto              Vlan    Flows(%)     Packets(%)       Bytes(%)         pps      bps   bpp
2023-08-15 15:14:15.514     00:00:29.504 any                 100    26434(119.2)   70.8 M(135.8)   68.7 G(151.5)    2.4 M   18.6 G   970

Summary: total flows: 22180, total bytes: 45.3 G, total packets: 52.1 M, avg bps: 12.3 G, avg pps: 1.8 M, avg bpp: 870
Time window: 2023-08-15 15:14:15 - 2023-08-15 15:14:45
Total flows processed: 22180, passed: 22180, Blocks skipped: 0, Bytes read: 3640464
Sys: 0.0000s User: 0.0040s Wall: 0.0052s flows/second: 4225547.9 Runtime: 0.0053s
```

### Expected behavior

Proper values and order of statistic for all supported elements.

**Comment by phaag** [comment]
If I look at the output, it looks correct to me. By definition is a single flow has src as == 0 and dest as == 0 it is counted twice as the direction is not relevant and as a result it adds up to 200% of flows. You can have statistics on different directions, which then count one direction only.

**Comment by piorek94** [comment]
ok - if this behavior is expected. For 1.6.x versions output for this case is different (count only once if value for element occurs for dst or src).

**Comment by phaag** [comment]
As of 1.6.x: yes and no. All percentage summed up results also in 200% unless all flows are counted twice, then it is 100%. That was not consistent, therefore it was changed.
