### ISSUE TITLE
ipfix sample rate not being used

### ISSUE THREAD

**Issue by bdreisbach** [phaag/nfdump#47]
we are sending ipfix from a juniper ptx at 1:10000. the template includes the sample rate field, and the sample rate is being sent periodically. however, the flows are showing up in nfcap/nfdump as unsampled.

i have attached a pcap with the exported flows. packet 26, set 5, flow 1 contains the sample rate as you can see.
[ptx-ipfix.pcap.zip](https://github.com/phaag/nfdump/files/622466/ptx-ipfix.pcap.zip)

here is an example from nfdump -o raw:
Flow Record:
  Flags        =              0x06 FLOW, Unsampled
  export sysid =                 1
  size         =                96
  first        =        1480524513 [2016-11-30 16:48:33]
  last         =        1480524513 [2016-11-30 16:48:33]
  msec_first   =               958
  msec_last    =               958
  src addr     =      x.x.x.x
  dst addr     =     y.y.y.y
  src port     =             44861
  dst port     =                80
  fwd status   =               230
  tcp flags    =              0x10 .A....
  proto        =                 6 TCP
  (src)tos     =                 8
  (in)packets  =                 1
  (in)bytes    =                52
  input        =               796
  output       =               637
  src as       =             65000
  dst as       =              65001
  src mask     =                23 x.x.x.x/23
  dst mask     =                24 y.y.y.y/24
  dst tos      =                 0
  direction    =                 0
  ip next hop  =     a.a.a.a
  bgp next hop =     b.b.b.b
  ip router    =     c.c.c.c
  received at  =     1480524600006 [2016-11-30 16:50:00.006]

**Comment by phaag** [comment]
Implemented in master tree. Please verify.

**Comment by bdreisbach** [comment]
is there a trick to get master to compile on linux? ive tried centos6, centos7, and ubuntu 14.04 LTS. i get this error:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -ggdb -g -O2 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -fno-strict-aliasing -MT nffile.lo -MD -MP -MF .deps/nffile.Tpo -c nffile.c  -fPIC -DPIC -o .libs/nffile.o
nffile.c: In function ‘NewFile’:
nffile.c:642: error: ‘for’ loop initial declarations are only allowed in C99 mode
nffile.c:642: note: use option -std=c99 or -std=gnu99 to compile your code
nffile.c: In function ‘DisposeFile’:
nffile.c:667: error: ‘for’ loop initial declarations are only allowed in C99 mode
make[3]: *** [nffile.lo] Error 1

surprisingly it compiled fine on macOS.

**Comment by bdreisbach** [comment]
seems that older gcc cannot compile master after 3bf72967fcacdea01213e94507b57967d9d32801
installed devtools7 on my centos machine and it compiled. 

i am still verifying that the fix for ipfix sampling is working. will get back to you this week.

**Comment by phaag** [comment]
Compile issue fixed. clang and gcc do not agree on local variable declarations.

**Comment by bdreisbach** [comment]
cool. the ipfix sampling does seem to be working. thanks!

**Comment by gabrielmocan** [comment]
I've tested this fix with a Juniper MX104 exporting at 1:100 ratio using IPFIX template but have no sucess. Flows are still showing as "Unsampled" when nfdump'd using raw output.

pcap attached bellow. I think sampling information is available in packets 623 and 4410.

[mx104_ipfix.zip](https://github.com/phaag/nfdump/files/1594993/mx104_ipfix.zip)

**Comment by phaag** [comment]
Juniper does not export a sampling algorithm. nfdump required an algorithm in order to recognise sampling correctly. 
I fixed that as the algorithm is not really used internally.

**Comment by gabrielmocan** [comment]
I've just tested this fix. Sampling factor is properly being applied now. Thanks!
