### ISSUE TITLE
Can't finish ./configure with --enable-nfprofile error: can not link librrd on FreeBSD 13.2

### ISSUE THREAD

**Issue by litmk** [phaag/nfdump#472]
Hey I'm trying to complie nfdump 1.73 on FreeBSD 13.2 and I can compile it without issue if I configure it with these options:

./configure --enable-maxmind --enable-nsel 

But I need to enable:
./configure --enable-maxmind --enable-nsel --enable-nfprofile --enable-nftrack

The configure script errors with:
checking for rrd_update in -lrrd... no
configure: error: Can not link librrd. Please specify --with-rrdpath=.. configure failed!

I've tried adding --with-rrdpath=/usr/local/bin/ or --with-rrdpath=/usr/local/lib/ with no luck. 

rrdupdate  and rrdtool are in /usr/local/bin/
librrd.so and librrd.so.8.3.0 are in /usr/local/lib/

I'm not sure what to try next. Any help is greatly appreciated.

**Comment by phaag** [comment]
It's the function `rrd_update()` which is required in the lib. `/usr/local` is the default path, so you do need specify `--wit-rrdpatch` only if librrd is located on another location.
I have not tried 8.3.0 - configure tests, if the function `rrd_update()` is available.

**Comment by phaag** [comment]
It looks like FreeBSD 13.2 does not include /usr/local by default in the compile process. Therefore use `--with-rrdpath=/usr/local` and it does compile.

**Comment by litmk** [comment]
Worked. Thanks very much!
