### ISSUE TITLE
Cached file is not readable after upgrade to 1.7.3

### ISSUE THREAD

**Issue by moonsho41** [phaag/nfdump#473]
The files that are being written to by Nfcapd (1.7.3) process in realtime do not return any data when processed with Nfdump (1.7.3). However the files that are generated on the disk work as expeceted. Is there a known bug on this? Please see outputs below:

nfdump: Version: 1.7.3-46d2db0  Date: 2023-09-25 12:51:59 +0200

nfdump -r ./nfcapd.current.1099 

Date first seen             Duration     Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
No matching flows
Summary: total flows: 0, total bytes: 0, total packets: 0, avg bps: 0, avg pps: 0, avg bpp: 0
Time window: <unknown>
Total flows processed: 0, passed: 0, Blocks skipped: 0, Bytes read: 0
Sys: 0.0046s User: 0.0000s Wall: 0.0022s flows/second: 0.0 Runtime: 0.0022s

**Comment by phaag** [comment]
`nfcapd.current.xxx` is a temporary file written by nfcapd and should not be read at the same time with nfdump. If you do so, you probably get corrupted data.
