### ISSUE TITLE
Allow using external lz4 library

### ISSUE THREAD

**Issue by bernhardschmidt** [phaag/nfdump#475]
Hi Peter, Debian packager for nfdump here.

During discussion  to upgrade nfdump in stable from 1.7.1 to 1.7.3 we have come across a large change in the embedded liblz4 copy. Debian (and most other distributions) dislike shipping (and especially, building against) embedded code copies because they cannot be reliably tracked on upstream security vulnerabilities. See https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code .

It would be really appreciated if nfdump could link against a distribution-supplied liblz4.

**Comment by bernhardschmidt** [comment]
Same for lzo2 of course, although that is much smaller, more often embedded and not under active development.

**Comment by phaag** [comment]
There are pros and cons to embed library code and I perfectly understand the your view. However, there is also a view from the developer side, to ship code, which has been tested and works for the application as intended. There is nothing worse, than 3rd party  libraries, which  change, even worse frequently, and are incompatible in their API or also even worse, same APi and different result. If you add an extra dimension such as the whole of the *nix universe in all their different versions and flavors, then it becomes a pain … somewhere .. You are expected of corse  to write software which compiles smoothly and runs at it’s best performance everywhere .. Meanwhile I have a pretty nice collection of virtual machines.
 That’s said - it’s a general remark and in no way any critique  to the lz4 library and it’s people. Thanks for that excellent library which I like by the way very much! 🤗

I tried to use a tradeoff, with larger and more complex libraries, which I don’t dare to fully overview in it’s details, to link externally and smaller ones to embed with the goal, that even with no external reference at all, the program builds and runs, maybe with less features. 

I certainly can add a configure option to use the system installed lz4 library in favor of the embedded. I do not (yet) want to get rid of the embedded code until time proves, all is fine on all versions and flavors 🙃

The lzo code remains embedded. It is not maintained that frequently and is for a minimal setup without external references a good option.

**Comment by phaag** [comment]
The latest master repo improves the linking with external compression libraries. Furthermore the bzip2 library is no longer required, but optional.
The standard `configure` process checks for the installed libraries lz4, bz2 and zstd and enables them if they are found. 
configure understands the following options:
```
  --with-lz4path=PATH     Expect liblz4 installed in PATH; default /usr/local
  --with-zstdpath=PATH    Expect libzstd installed in PATH; default /usr/local
  --with-bz2path=PATH     Expect libbz2 installed in PATH; default /usr/local
```
Bz2 and Zstd are optional. If no option is give and no library is found that compression algorithm is disabled. For lz4, if no library is found, the embedded version is used.
Compression algorithms can also be explicitly disabled by setting `with-xxxpath=no` In the case of lz4, it disables the system installed version.

**Comment by thezoggy** [comment]
before todays change, you would show options in the version:
```
nfdump 1.7.3-46d2db0 Options: ZSTD Date: 2023-09-25 12:51:59 +0200
```

post make/install, now version shows:
```
nfdump: Version: 1.7.3-ec8b602  Date: 2023-10-14 16:54:44 +0200
```

Made me question if that meant something stopped working with zstd..
I see during configure it showed:
```
  LIBS                 = -lresolv -lpthread -latomic  -lbz2 -lzstd
  Enable liblz4        = embedded
  Enable libbz2        = yes
  Enable libzstd       = yes
```

so I assume that means that all the compression libs were found and all was good (just making sure I didnt need to add paths/install any new dependencies)

**Comment by phaag** [comment]
@thezoggy - Updated version string to be compatible again.

**Comment by thezoggy** [comment]
> @thezoggy - Updated version string to be compatible again.

looks good now
```
nfdump -V
nfdump: Version: 1.7.3-6b69002 Options: ZSTD BZIP2 Date: 2023-10-14 20:12:29 +0200
```

**Comment by phaag** [comment]
The option is now available as requested.
