### ISSUE TITLE
"nfexpire causes infinite loop, fills up logs"  resurfaced ?

### ISSUE THREAD

**Issue by ronnyaa** [phaag/nfdump#481]
Hello 

I suspect this issue have resurfaced:   https://github.com/phaag/nfdump/issues/271

installed the latest master branch from git  and when i set the expire time in the web user interface i quickly saw the same error messages.  and it noticed it when /var/log filled the disk. 

tried to apply the fix from https://github.com/phaag/nfdump/commit/f134b16a5e86f9c9bfcc7c54fb7df970d17d6c39
and it seems to have fixed the issue. 

best regards

**Comment by phaag** [comment]
Thanks - Fixed in master branch.
