### ISSUE TITLE
nfcapd logs problem ?

### ISSUE THREAD

**Issue by przemeksw** [phaag/nfdump#490]
Hi
I'm using nfcapd version 1.7.2 running on gentoo.
It is invoked as follows:
nfcapd -4 -S7 -t 60 -p 1234 -w /logs/vol0/ -x %u -D -j -B 128000
Logs from two routers are sent to nfcapd.

I'm worried about logs full of entries like:
Dec 16 12:15:00 nlogk nfcapd[14655]: Ident: 'none' Flows: 820158, Packets: 73070592, Bytes: 79306611841, Sequence Errors: 2, Bad Packets: 0
Dec 16 12:15:00 nlogk nfcapd[29536]: Can't execvp: 1702725240: No such file or directory

What could be the reason, I used the 1.6 series before and there were no such errors

**Comment by phaag** [comment]
You execute the command: `%u -D -j -B 128000` where %u resolves to the current time slot. But the time slot is not a binary, which you can execute - you missed the binary before %u, therefore ` 1702725240: No such file or directory`

This is the same as in the 1.6 series binaries.

**Comment by przemeksw** [comment]
Thank you for the information.
Version 1.6 never screamed at me in the logs about something like this.

Unfortunately, I don't fully understand what this binary file is about. I can't read this anywhere in your documents regarding cg nfcapd, could you show me where to look or what it should look like - I will be very grateful

**Comment by phaag** [comment]
Sure! - 1.6.x did as well - it's the same code:
```
    execvp(*args, args);
    LogError("Can't execvp: %s: %s", args[0], strerror(errno));
    _exit(1);
```

Maybe you did not check the logs, but in any case you did not get the result you wanted. At least that should have triggered you. 
In your case the `-x` argument is useless anyway, as it does not do anything.
