### ISSUE TITLE
RAM consumption 

### ISSUE THREAD

**Issue by LaysonRC** [phaag/nfdump#494]
I've made a VM in VMware ESXI 8.0 Update 1, 
with Debian 11,
4 cores CPU,
500GB of disk,
16GB of swap,
and up to 32GB of RAM.
With one netflow source.

Searching for 2 days, it consums 8GB of RAM,
3 days, 16GB of RAM,
4 days 26GB of RAM.

If I search a bigger period of time, that consumes all RAM and Swap, it get killed.

Or if I set a not so big period, but it use the swap memory, after several hours, it return:
ERROR: nfsend socket_read() communication error: Interrupted system call!

**Comment by phaag** [comment]
If there are further issues or remarks, feel free to reopen this issue.
