### ISSUE TITLE
nfdump current (1.7.3) has a bug exporting NSEL (cisco ASA) fw events

### ISSUE THREAD

**Issue by MrdUkk** [phaag/nfdump#498]
captured via nfcapd from CISCO ASA device 
after that try to convert capture to text csv:
nfdump -q -o "fmt:%tsr,%ra,%evt,%xevt" -r nfcapd.dump

in outputfile i see
"UNKNOWN, Ignore"
last field values

if i launch
nfdump -q -o raw -r nfcapd.dump
i see correct
fw event = 5: UPDATE
fw ext event = 0: Ignore

looking at source code file output_raw.c
i see function stringsEXnselCommon():
where is CORRECT code is placed (r->event_flag boolean test)

now looking at output_fmt.c
function String_evt(): seems to be incorrectly interpreting flag r->fwXevent instead of r->event_flag and writes incorrect value.

**Comment by phaag** [comment]
Thanks! - It's fixed in master repo.

**Comment by MrdUkk** [comment]
thank you!

i think it should respect '-N' switch too. instead of printing human string -> simply intege fw event. (printPlain  int flag, like in String_Duration function for example)

**Comment by phaag** [comment]
String_evt respects -N flag. Fixed in 0001529
