### ISSUE TITLE
Include timezone in nfcapd file names

### ISSUE THREAD

**Issue by exaexa** [phaag/nfdump#5]
It would be cool to have a possibility to include a timezone in files produced by nfcapd, for following reasons:

- there would not be collisions on timezone changes (e.g. I suspect that when switching the daylight saving time some NF data are currently lost as a result)
- It would make the filenames zone-oblivious globally, making moving/indexing easier.

Actual solution may be quite easy, e.g. using gettimeofday() somewhere around this:
https://github.com/phaag/nfdump/blob/master/bin/nfcapd.c#L486
Suggested final filename form is something like `nfcapd.yyyymmddHHMM+ZZZZ`.

I'll try to write a patch asap to see if there's no compatibility issue.

(side note: is there any reason why not to include seconds in the filename as well?)

**Comment by phaag** [comment]
There are pros and cons. The topic is known. 
As for the daylight saving time: If you set your system to UTC, you will not loose any  data.

If this does not work for you - I added a -Z to nfcapd/sfcapd to add the UTC offset to nfcapd files
e.g. +0100 or  -0600 for example, so you can play with it. However, please note: THIS BREAKS EXPIRING DATA. Autoexpire -e or nfexpire can not (yet) handle timezone extension, as this is a bit more 
complicated to fix.

The file format is limited to minutes format, as one minute as smallest time slice seams reasonable to me.

**Comment by exaexa** [comment]
Works perfectly, thanks a lot. I'm expiring the data by some other system.

I guess the problem with nfexpire is just in the parsing of new file names?

**Comment by phaag** [comment]
nfexpire expects a certain file naming. It also has other implications. Therefore -Z is not recommended. Use it at your own risk.
