### ISSUE TITLE
sfcapd -T Extensions 1.6.x missing in 1.7.x

### ISSUE THREAD

**Issue by dannyfrazer** [phaag/nfdump#501]
Is it still possible in 1.7.x to use the -T extension list in any other way?

In version 1.7.1-3 (testing) the option is available (https://manpages.debian.org/testing/nfdump-sflow/sfcapd.1.en.html) but in other 1.7.x versions its not available.

**Comment by phaag** [comment]
The change of the backend format in 1.7.x also changed the extensions. Therefore -T x would not behave the same in 1.6.x and 1.7.x. However I could sync the `-X extension`from nfcapd to sfcapd.
