### ISSUE TITLE
nfprofile: Skip unknown record type 13 (after upgrrading from 1.6.20 to 1.7.3)

### ISSUE THREAD

**Issue by avamal** [phaag/nfdump#503]
Hi

After upgrading nfdump from 1.6.20 to 1.7.3  the following error occurs every 5 minutes multiple time (10-20 times per 5 min):
nfprofile[pid]: Skip unknown record type 13

This is installation together with nfsen under FreeBSD, nfsen has been upgraded too from 1.3.8 to 1.3.11. 
Everything looks working, including old profiles.

What means this error, how I can fix it?

Thanks!

**Comment by phaag** [comment]
Yes - that's correct. It looks like you have an exporter, which exports interface names (ASA firewall?). These names go into a special data array record of type 13. As this is not a flow record, nfprofile can not deal with this record and skips it.
This has no influence of the filtering of flow records, however, if you want to list the associated interface names of flow records in a profile, no names will show up.
I need to patch nfprofile for that.

**Comment by avamal** [comment]
> It looks like you have an exporter, which exports interface names (ASA firewall?).

It is service router [Eltex-3100](https://eltex-co.com/catalog/service_gateway_esr-3100-en.php). Upgrading firmware and switching between netflow 5 and 9 does not resolve problem.

> I need to patch nfprofile for that.

I'd like at least to suppress logging of this messages. Will wait you patch.

Thanks!

**Comment by phaag** [comment]
@avamal - Would you mind to capture a few minutes of the netflow traffic, sent to the collector? - Just tcpdump those traffic and send it to my email in the AUTHORS file. This would help me to understand those flows and improve the software.
I would prefer the v9 flows.
Thanks

**Comment by avamal** [comment]
Yes, of course. Tomorrow I'll do it.

**Comment by phaag** [comment]
Fixed in master repo

**Comment by cron2** [comment]
Good to see this being already fixed ;-) - I just bumped into this as well, after upgrading 1.6 to 1.7.3 (FreeBSD port).

Not sure which device is causing this over here, either IOS XR or Arista EOS (nfprofile doesn't tell which file it encountered this).

**Comment by phaag** [comment]
@cron2 - It’s not a but in one of your exporters, but the profiler did not handle correctly the sampler records. Therefore I would recommend you to upgrade to 1.7.4.

**Comment by cron2** [comment]
Thanks.  Have upgraded to 1.7.4, and the nfprofile messages are gone.

Have opened a FreeBSD PR to get the port updated as well (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277572)
