### ISSUE TITLE
sfcapd not working properly after last commits

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#506]
Hi Pete, how you doing?

I have a switch that was exporting sFlow for a couple years and after I upgraded his nfdump to master, I now have the following error:

`Corrupt data file. Inconsistent block size in nfdump.c line 377`

What do you need to troubleshoot this?

**Comment by gabrielmocan** [comment]
After rolling back to commit `4b961bd432e01cb4db0c042ad3aade3116203a6a`, it works fine. So I guess this bug was introduced after #501

**Comment by phaag** [comment]
Thanks for the report. I will check that.

**Comment by phaag** [comment]
Sorry - that commit was completely buggy! I hope it works now as expected.

**Comment by gabrielmocan** [comment]
@phaag just works

thanks
