### ISSUE TITLE
nfdump: Skip unknown record type 9

### ISSUE THREAD

**Issue by SanderDelden** [phaag/nfdump#508]
Hi,

We have recently upgraded our nfdump instance from 1.6.17 to 1.7.4. We use sfcapd to capture sFlow traffic from our routers and store this. When using nfdump 1.7.4 to read the old data the following errors are shown:

```
Skip unknown record type 9

Skip unknown record type 9

Skip unknown record type 9

Skip unknown record type 9

Skip unknown record type 9

Skip unknown record type 9
```

No issues occur when reading the new data.

**Comment by phaag** [comment]
You may add the patch below and check again:

For src/nfdump/nfdump.c
```
--- nfdump.c.orig	2024-02-22 07:10:44.000000000 +0100
+++ nfdump.c	2024-02-22 07:10:48.000000000 +0100
@@ -494,6 +494,7 @@
                 case ExporterStatRecordType:
                     AddExporterStat((exporter_stats_record_t *)record_ptr);
                     break;
+                case SamplerLegacyRecordType:
                 case SamplerRecordType: {
                     int ret = AddSamplerInfo((sampler_record_t *)record_ptr);
                     if (ret != 0) {
```

**Comment by SanderDelden** [comment]
With the patch applied the errors are no longer observed. Thanks for the (very) quick reply!

**Comment by phaag** [comment]
Welcome! 
If you have built nfprofile, you should apply the same patch also to nfprofile.c around line 206 - otherwise the profile counters could be wrong.

**Comment by SanderDelden** [comment]
Am I correct in presuming that this patch will not be included in master or any release?

**Comment by phaag** [comment]
I committed a patch to the master branch this morning. The approach was a bit different, but with the same result.
