### ISSUE TITLE
Support for NetFlow version 10

### ISSUE THREAD

**Issue by cdcrawford** [phaag/nfdump#510]
Good morning,

Could we add support for netflow version 10? It's the extension used for VXLAN.

Cheers,
Chris

**Comment by cdcrawford** [comment]
I see that it's been added as ipfix.h and ipfix.c.

I think this can be closed.

**Comment by phaag** [comment]
Ipfix is actually version 10. Although, nfdump supports a huge number of ipfix elements, it does not support all possible elements. 
If you have specific use case, please describe a bit more detailed and feel free to send me a sample packet capture, so I can see, how your exporter works. You will find my email address in the AUTHORS file.
