### ISSUE TITLE
sfcapd not acknowledging -W <Worker>

### ISSUE THREAD

**Issue by bpahlke** [phaag/nfdump#513]
Hello,
the sfcapd is ignoring the -W parameter.

Which I think, I tracked down to a missing W here:
https://github.com/phaag/nfdump/blob/8fe6a2b25c119367f27c6a9d2baac859847d033b/src/sflow/sfcapd.c#L603

I think the getopt() options should read something like this, this string identical to the [nfcapd.c:637](https://github.com/phaag/nfdump/blob/8fe6a2b25c119367f27c6a9d2baac859847d033b/src/nfcapd/nfcapd.c#L637) one, except it is missing the "s":
`46AB:b:C:d:DeEf:g:hI:i:jJ:l:m:M:n:p:P:R:S:T:t:u:vVW:w:x:X:yz::Z`

At least with this string, and a newly compiled sfcapd, it is no longer complaining about the invalid option "W", and not printing "Number of workers should not be greater than number of cores online. 4 is > 1".

I hope this is correct and of use.

**Comment by phaag** [comment]
Sure! - thanks! - I'll fix that.

**Comment by bpahlke** [comment]
Thank you very much!

**Comment by phaag** [comment]
Fixed in master repo.
