### ISSUE TITLE
IPFIX (V10) support for dot1q VLAN IDs

### ISSUE THREAD

**Issue by jbemmel** [phaag/nfdump#515]
Hi,

As stated in another issue, nfdump/nfcapd works mostly fine for IPFIX (V10) flow reports. However, it is still lacking some fields:

IP version 60
Ingress Physical Interface 252
Egress Physical Interface 253
Dot1q VLAN ID 243
Dot1q Customer VLAN ID 245
Post Dot1q VLAN ID 254
Post Dot1q Customer VLANId 255

The dot1q fields were added to v9 in 2019, but not for v10. See https://www.rfc-editor.org/rfc/rfc7133.html#page-26 for specs

Attached pcap trace contains a sample with L2 MAC addresses and VLAN tag 100 for a simple ICMP flow, as produced by Nokia SR OS
[ipfix-2055.zip](https://github.com/phaag/nfdump/files/14775390/ipfix-2055.zip)

![image](https://github.com/phaag/nfdump/assets/2031627/cfbc909c-e87a-4841-9cab-632c2b3bc3e4)

**Comment by jbemmel** [comment]
See https://github.com/phaag/nfdump/commit/ecf9b12ce55908930c659bcd44cdbc1b584ee025 for v9 support

**Comment by phaag** [comment]
The implementation of the new fields takes a bit more time.

**Comment by phaag** [comment]
@jbemmel - I see, there could be a potential need for the others except `IP version 60`. You already have that implicit with the IP addresses being IPv4 or IPv6. Can you elaborate the use case for that, so I can see your needs.

**Comment by phaag** [comment]
@jbemmel - Could you please specify what processing you need with the new elements?

**Comment by jbemmel** [comment]
See https://github.com/jbemmel/IXP-Manager/blob/add-goflow2-support/tools/runtime/sflow/goflow2-to-rrd-handler#L131

My use case is populating IXP Manager similar to how sflowtool is being used. I was trying to use goflow2 but it does not support V10 IPFIX

The IP version could possibly be inferred from the ipv4/v6 address, but the data is there and it's simpler to just take that byte. It's less critical than the missing VLAN fields

**Comment by phaag** [comment]
I added an `ip_version` tag in the json output format. Just tell me, where you need this info in which nfdump output. Just a single byte is pretty much a waste of space in the extension backend. If I can provide you that information otherwise, that would be a better solution.

The VLAN fields as well as the physical interface IDs are integrated in the latest master repo and accepted vor v9 and IPFIX.

**Comment by jav4** [comment]
Some devices (i.e. Cisco) don't populate the IP version field whiel capturing ethernet traffic (layer 2). I've submitted a PR to add the ethertype filed (256) for that same use case.

**Comment by phaag** [comment]
I have seen the PR. The point is the same as for the IP version - just 2 bytes for a backend extension is pretty much a waste of space. I could rearrange the code, such, that all the physical elements (layer ) go into the same extension. 
So please do not yet use the master branch, as the code will change for that.

**Comment by phaag** [comment]
PR resolved and integrated in layer2 extension. Please check, if this works for you.

**Comment by jbemmel** [comment]
There is an issue with this PR (not sure if it was present before)
```
jeroen@jvb-vm:~/srlinux/nfdump$ nfdump -r /tmp/nfcapd.202404011450 -o raw

Flow Record: 
  RecordCount  =                 1
  Flags        =              0x02 NETFLOW v10, Sampled
  Elements     =                10: 1 2 3 8 9 12 15 36 38 39 
  size         =               220
  engine type  =                 0
  engine ID    =                 0
  export sysid =                 1
  first        =     1711983095784 [2024-04-01 14:51:35.784]
  last         =     1711983095784 [2024-04-01 14:51:35.784]
  received at  =     1711983171593 [2024-04-01 14:52:51.593]
  proto        =                58 ICMP6
  tcp flags    =              0x00 ........
  ICMP         =              133.0  type.code
  in packets   =                 1
  in bytes     =                78
  src addr     =           0.0.0.0
  dst addr     =           0.0.0.0
  src addr     =  fe80::a8c1:abff:fe2b:2f14
  dst addr     =           ff02::2
  bgp next hop =           0.0.0.0
  bgp next hop =                ::
  ip exporter  =      172.30.201.3
  in src mac   = aa:c1:ab:2b:2f:14
  out dst mac  = 00:00:00:00:00:00
  in dst mac   = 33:33:00:00:00:02
  out src mac  = 00:00:00:00:00:00
  ingress VRF  =                 1
  egress VRF   =                 0
  vlanID       =               100
  post vlanID  =                 0
  custID       =                 0
  post custID  =                 0
  ingress IFid =        1610899521
  egress IFid  =        4294967295
```

```
jeroen@jvb-vm:~/srlinux/nfdump$ nfdump -r /tmp/nfcapd.202404011450 -o json
[
{
	"type" : "FLOW",
	"export_sysid" : 1,
	"ip_version" : "4",
	"src4_addr" : "0.0.0.0",
	"dst4_addr" : "0.0.0.0",
	"src_geo" : "",
	"dst_geo" : "",
	"bgp4_next_hop" : "0.0.0.0",
	"ip4_router" : "172.30.201.3",
	"in_src_mac" : "aa:c1:ab:2b:2f:14",
	"out_dst_mac" : "00:00:00:00:00:00",
	"in_dst_mac" : "33:33:00:00:00:02",
	"out_src_mac" : "00:00:00:00:00:00",
	"ingress_vrf" : "1",
	"egress_vrf" : "0",
	"vlanID" : 100,
	"post_vlanID" : 0,
	"cust_vlanID" : 0,
	"post_cust_vlanID" : 0,
	"sampled" : 1
}]
```

The 'json' output format wrongly picks IPv4 for an IPv6 flow

**Comment by phaag** [comment]
Well - it's not wrong either. Your exporter send both IP address records type - IPv4 and IPv6. 
The json output assumes, if v4 is present, it prints v4. There is an ambiguaty which IP version is correct. I could print both, if both are present, but this may violate the unique key of the json record. 
In the sample pcap you have records with both IPv4 and IPv6, none of them is filled and the IP version is set to 0. 
It's a bit difficult with ambigious data.

**Comment by jav4** [comment]
Aggregation (-A) doesn't work with any option now:

`nfdump -r nfcapd.202404011805 -o fmt:'%eth %ismc %idmc %byt' -A insrcmac
Number of workers should not be greater than number of cores online. 4 is > 1
Date first seen         Duration            In src MAC Addr   Packets    Bytes      bps    Bpp Flows
Summary: total flows: 1930, total bytes: 340.2 M, total packets: 539020, avg bps: 4.9 M, avg pps: 976, avg bpp: 631
Time window: 2024-04-10 01:44:11 - 2024-04-10 01:53:23
Total flows processed: 1930, passed: 1930, Blocks skipped: 0, Bytes read: 332136
Sys: 0.0109s User: 0.0000s Wall: 0.0035s flows/second: 545375.4 Runtime: 0.0051s
`

Without aggregation, works fine. This specific file has >20 source MAC addresses:

`nfdump -r nfcapd.202404011805 -o fmt:'%ismc' | sort -u | wc -l`

**Comment by phaag** [comment]
If you think, your flow file does not produce the correct results, feel free to send it to me by email ..

**Comment by jbemmel** [comment]
> Well - it's not wrong either. Your exporter send both IP address records type - IPv4 and IPv6. The json output assumes, if v4 is present, it prints v4. There is an ambiguaty which IP version is correct. I could print both, if both are present, but this may violate the unique key of the json record. In the sample pcap you have records with both IPv4 and IPv6, none of them is filled and the IP version is set to 0. It's a bit difficult with ambigious data.

This is not intended as criticism, I'm only sharing how devices behave in my world and the consequences of that.
In my case, the exporter includes the IP version field in its report - so I think the JSON formatter should either dump all fields, or if the IP version field is present it should pick the corresponding src/dst address fields (instead of assuming v4)

Noting that it may be possible to have non-IP flows - I have seen reports with IP version "0"

**Comment by phaag** [comment]
> > Well - it's not wrong either. Your exporter send both IP address records type - IPv4 and IPv6. The json output assumes, if v4 is present, it prints v4. There is an ambiguaty which IP version is correct. I could print both, if both are present, but this may violate the unique key of the json record. In the sample pcap you have records with both IPv4 and IPv6, none of them is filled and the IP version is set to 0. It's a bit difficult with ambigious data.
> 
> This is not intended as criticism, I'm only sharing how devices behave in my world and the consequences of that. In my case, the exporter includes the IP version field in its report - so I think the JSON formatter should either dump all fields, or if the IP version field is present it should pick the corresponding src/dst address fields (instead of assuming v4)
> 
> Noting that it may be possible to have non-IP flows - I have seen reports with IP version "0"

No worries! It’s important, I understand the needs. 
However, it looks like, that field as implemented is not useful. I will remove it and check, if there is another option.

**Comment by phaag** [comment]
Thanks! - The flow aggregation is fixed. It triggered a bug, if no ipv4 or ipv6 block was present.

**Comment by phaag** [comment]
@jbemmel - as you opened the issue, could you confirm, if the current master would work for you?

**Comment by jbemmel** [comment]
> @jbemmel - as you opened the issue, could you confirm, if the current master would work for you?

![image](https://github.com/phaag/nfdump/assets/2031627/b8c533eb-823e-4e8c-9100-c7a5a2a27fb9)
![image](https://github.com/phaag/nfdump/assets/2031627/dfcff131-3950-45ad-a22f-12a657f585f0)

Not directly related to the original FR, but the 'json' output still selects the wrong addresses to include in its output. Not sure what fields are present in the original packet - I did not do a packet capture - but type 'ICMP6' should trigger selection of ipv6 addresses

**Comment by phaag** [comment]
Please make sure, to skip old files. Since the merge, there is no longer an extension 39. Please test with new collected data and delete the old one.

**Comment by phaag** [comment]
The json output is fixed. You see now all available extensions.

**Comment by phaag** [comment]
Seems, that the implementation works. I therefore close this ticket. Feel free to re-open it in case of problems.
