### ISSUE TITLE
Typo in IPFIX fields

### ISSUE THREAD

**Issue by jbemmel** [phaag/nfdump#516]
https://github.com/phaag/nfdump/blob/fb664fcb903551841f8ff075ae897cddc8773575/src/netflow/ipfix.c#L175

Should be
```
    {IPFIX_postVlanId, SIZEdstVlan, NumberCopy, EXvLanID, OFFdstVlan, STACK_NONE, "dst VLAN ID"},
```

**Comment by phaag** [comment]
Sure! - Thanks!
