### ISSUE TITLE
nfdump default workers calculation on low-cpu systems

### ISSUE THREAD

**Issue by philhagen** [phaag/nfdump#518]
It looks like any system with a core count below 4 trips a warning:

This appears to have been introduced with 02ee700893f19730084018685fa275c64d5be4d8.

On a system with fewer than 4 cores, the following is always displayed:
```
$ nfdump -r nfcapd.202403090000
Number of workers should not be greater than number of cores online. 4 is > 1
...
```

This occurs even if setting `maxworkers = 1` in `/etc/nfdump.conf`, and it does not occur when running on a system with >=4 cores.

I tested with 1, 2, and 4 cores on a Linux system, and 12 cores on a macOS system.  The 1- and 2-core systems show the error with and without `maxworkers` set, and the 4- and 12-core systems do not.

This is a non-terminal warning, so it's not a blocker but it does appear that this may have _just_ been addressed in 8941a799251d4582a6b14e038a61a748466a6de5, so the issue may be unnecessary.  Still wanted to document in case there are other edge cases that need to be tested.

**Comment by phaag** [comment]
Addressed and updated in latest master.
