### ISSUE TITLE
Bad magic 0x10CF

### ISSUE THREAD

**Issue by Fishmoon5** [phaag/nfdump#522]
Good morning,

I was given some netflow v5 raw files and would like to use nfdump to convert them to a human-readable format. However, when I run nfrump -r file, I saw the following error:
```
Date first seen            Event  XEvent Proto      Src IP Addr:Port          Dst IP Addr:Port     X-Src IP Addr:Port        X-Src IP Addr:Port   In Byte Out Byte
Open file 'ft-v05.2024-03-13.040001-0400': bad magic: 0x10CF
No matching flows
```

Any idea on what might be wrong? Thank you!

**Comment by thezoggy** [comment]
nfdump is to read files stored in the nfcapd format... not read raw netflow files.
nfcapd = is the netflow collector which stores the flow records into files for nfdump..

which would explain why they arent in the correct 'format' hence your file doesnt have the expected magic bit set in it:
https://github.com/phaag/nfdump/blob/master/src/libnffile/nffileV2.h#L46

there are various tools to get data into nfdump formatted files if your not just sending the netflow to the box.

readpcap = load data via pcap
nfpcapd = create netflow data from interface or pcap data
ft2nfdump = converts flow-tools data into nfdump format.
-- from what you said this might be what you are looking for?

also its generally good practice when opening a github issue for an app is to share what version of the software / and info about your env (what os/how you running it).

**Comment by phaag** [comment]
@thezoggy - thanks for your explanation! - I need to add, that the`ft2nfdump(1)` is unfortunately outdated. 
Sice 1.7.x. nfdump no longer reads from `stdin`. So the correct command line is:

```
% ft2nfdump -r  ft-v05.2024-03-13.040001-0400 -z=lz4 -w ft-v05.2024-03-13.040001-0400.nf
% nfdump -r ft-v05.2024-03-13.040001-0400.nf
```

I need to correct the man page!

**Comment by Fishmoon5** [comment]
Thank you both for your help! It works after I configure with the '--enable-ftconv' option and running the suggested ft2nfdump commands.

**Comment by Fishmoon5** [comment]
Thank you both for your help! It works after I configure with the '--enable-ftconv' option and running the suggested ft2nfdump commands.

**Comment by Fishmoon5** [comment]
Closing the issue now
