### ISSUE TITLE
nfdump - help/error text for compression argument

### ISSUE THREAD

**Issue by thezoggy** [phaag/nfdump#526]
in nfdump (latest from git,  Version: 1.7.4-564f3a9), help shows:
```
-J <num>	Modify file compression: 0: uncompressed - 1: LZO - 2: BZ2 - 3: LZ4 - 4: ZSTDcompressed.
```

noticed there is a missing space before compressed.

Then log for error is missing 4, ZSTD:

https://github.com/phaag/nfdump/blob/master/src/nfdump/nfdump.c#L752C1-L752C95
```
./nfdump -J -9999
Expected -J <arg>, 0 for uncompressed, 1, LZO, 2, BZ2, 3, LZ4
```

**Comment by phaag** [comment]
The numbers are obsolete anyway and legacy. I fixed the help and error text accordingly.
Thanks
