### ISSUE TITLE
nfcapd 1.7.4 - Segmentation Fault

### ISSUE THREAD

**Issue by David00** [phaag/nfdump#527]
Hello,

I have just built nfcapd from master, which reports version `1.7.4-release`.

I've built (and am trying to run it) on Ubuntu 22.04 server, kernel 5.15.0-102-generic.

Running it with very minimal options eventually stops after several minutes (1-5).

```
$ sudo nfcapd -M /var/nfdump/flow-data -p 9995 -S 2
Bound to IPv4 host/IP: any, Port: 9995
Init v5/v7: Default sampling: 1
Init v9: Max number of v9 tags enabled: 112, default sampling: 1
Init IPFIX: Max number of ipfix tags enabled: 104, default sampling: 1
Startup nfcapd.
Segmentation fault
```

This happens after just a couple minutes of running the daemon, and I'm not even sending any netflow data to it.  

The Ubuntu server is a virtual machine running on Intel Xeon Gold 6230, 8 vCPUs and 64GB of memory.

Here is a little bit more output from `time`ing the program:

```
$ sudo time nfcapd -M /var/nfdump/flow-data -p 9995 -S 2
Bound to IPv4 host/IP: any, Port: 9995
Init v5/v7: Default sampling: 1
Init v9: Max number of v9 tags enabled: 112, default sampling: 1
Init IPFIX: Max number of ipfix tags enabled: 104, default sampling: 1
Startup nfcapd.
Command terminated by signal 11
0.00user 0.00system 2:23.16elapsed 0%CPU (0avgtext+0avgdata 2476maxresident)k
0inputs+0outputs (0major+109minor)pagefaults 0swaps
```

**Comment by phaag** [comment]
Thanks for the report! The dynamic exporter node `-M` did not expect no packets within the interval :)
It's fixed in master branch.
