### ISSUE TITLE
Missing json format in statistic mode

### ISSUE THREAD

**Issue by piorek94** [phaag/nfdump#528]
### Problem:

Missing `json` format in statistic mode.

### Environment

nfdump version: v1.7.4-18e174a

### Description:

`pipe` output format is deprecated and documentation says to use `json` format instead, but it is not implemented.

```bash
nfdump -r nfcapd.202405221501 -s proto -o json
Not yet implemented output format
...
]
```

### Expected behavior

Implemented `json` output format for statistic mode.

**Comment by piorek94** [comment]
Do you plan to implement this functionality in version 1.7.5?

**Comment by phaag** [comment]
I hope, I can make it.

**Comment by phaag** [comment]
Implemented in master.
