### ISSUE TITLE
Strange output for ip4 aggregation with ipv6 filter

### ISSUE THREAD

**Issue by piorek94** [phaag/nfdump#537]
### Problem:

Strange output for ip4 aggregation with ipv6 filter.

### Environment

nfdump version: v1.7.4-7b701c9

### Description:

During aggregation by IPv4 address (`srcip4/net`/`dstip4/net`) with `ipv6` filter (I know it makes no sense but it is possible) there is strange output (comparing to previous versions of nfdump):

```bash
nfdump -r nfcapd.202405221501 -n 2 -A srcip4/32 -O bytes 'ipv6'
Date first seen         Duration               Src IP Addr   Packets    Bytes      bps    Bpp Flows
2000-00-00 00:00:00.000     00:00:00.000  xxxx:xx..:x:xxxx    792017  882.6 M   15.2 M   1114   460
Summary: total flows: 460, total bytes: 882.6 M, total packets: 792017, avg bps: 15.2 M, avg pps: 1708, avg bpp: 1114
Time window: 2023-08-13 20:23:09 - 2023-08-14 12:23:09
Total flows processed: 22112, passed: 460, Blocks skipped: 0, Bytes read: 4596784
Sys: 0.0000s User: 0.0000s Wall: 0.0021s flows/second: 10650488.1 Runtime: 0.0021s
```

The output includes stats for all IPv6 records, and the returned address `xxxx:xx..:x:xxxx` is the first encountered IPv6 source address.
For previous versions of nfdump, the given command is equivalent to `nfdump -r nfcapd.202405221501 -n 2 -A srcip6/128 -O bytes 'ipv6'` and the result is correct.

### Expected behavior

Reverting behavior from previous versions or returning an empty result in such cases.

**Comment by phaag** [comment]
Nulled in master.
