### ISSUE TITLE
Request: Add TTL field

### ISSUE THREAD

**Issue by caikpigosso** [phaag/nfdump#543]
Hello, I would like to know if it's possible to add the TTL field to be displayed in nfdump. It would be very useful for monitoring altered sources with spoofing.

**Comment by phaag** [comment]
Do you have an exporter, which sends this information? Which element IDs are used? There are multiple option: `192, 52, 53`

**Comment by phaag** [comment]
@caikpigosso - any comments on the question above?

**Comment by caikpigosso** [comment]
Hello, 

I sent the sample to your email, with this wireshark screenshot to select the field

<img width="462" alt="Captura de Tela 2024-07-08 às 09 14 12" src="https://github.com/phaag/nfdump/assets/17514768/009a428d-46af-4cd2-8695-30b4e5e17274">

**Comment by phaag** [comment]
give it a try with latest commit.
Implements filtering e.g. `ttl > 64` as well as aggregation and statistics `-s ttl`

**Comment by gabrielmocan** [comment]
@phaag mind adding this extension to go-nfdump as well?

**Comment by caikpigosso** [comment]
@phaag 
It worked, thank you very much.

<img width="325" alt="image" src="https://github.com/phaag/nfdump/assets/17514768/f317234d-2430-447f-b2b1-632ac1855370">

**Comment by phaag** [comment]
@gabrielmocan see https://github.com/phaag/go-nfdump/issues/15 completed.
