### ISSUE TITLE
Documentation on tcp_flags

### ISSUE THREAD

**Issue by sandervandegeijn** [phaag/nfdump#549]
I'm trying to parse nfdump files to elastic and would like to interpret the tcp flags. So in the data you will see something like:

"tcp_flags" : "......S."

I can't find documentation on what each letter / position means. Is it possible to describe this somewhere?

Thanks!

**Comment by phaag** [comment]
No worries! The new **csv-fast** format could also be an option for you.

**Comment by sandervandegeijn** [comment]
Thanks! I'm using Vector(.dev) to ingest the logs into opensearch with ECS mapping, so the json is fine for that! Can share the pipeline if that's useful.

**Comment by phaag** [comment]
Sure! Feel free to share it here or at my email in the authors file.
