### ISSUE TITLE
nfdump segfaults with ident filter expression

### ISSUE THREAD

**Issue by brownej** [phaag/nfdump#554]
nfdump -M /apps/flow/data/live/isb-border:hill-border -T  -r 2024-08-08/nfcapd.202408080125 -n 10 -s ip/flows ident hillborder
Segmentation fault (core dumped)

This happens with head of master branch commit 493c542

**Comment by phaag** [comment]
Ups ..

**Comment by phaag** [comment]
Fixed.

**Comment by brownej** [comment]
Seems to work in my setup now. Thanks!
