### ISSUE TITLE
nfdump filter src/dst geo issue with country codes that coincide with comparison operators

### ISSUE THREAD

**Issue by Takalele** [phaag/nfdump#560]
Hi,

It appears that for certain countries, it is not possible to use their [ISO 3166-1](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) Alpha-2 country codes as geo filter when these codes coincide with comparison operators. 

Examples:
- dst geo **lt** (Lithuania) — Less than (**lt**)
- dst geo **ne** (Niger) — Not equal (**ne**)
- dst geo **gt** (Guatemala) — Greater than (**gt**)
- dst geo **ge** (Georgia) — Greater than or equal (**ge**)

edit, found more:
- dst geo **as** (American Samoa)
- dst geo **pf** (French Polynesia)
- dst geo **in** (India)

```ERROR: Filter error: Line 1: syntax error at 'lt'!```

BR
Takalele

**Comment by phaag** [comment]
Thanks! Known issue, which should have been fixed already! It was not yet ..

**Comment by Takalele** [comment]
thank you very much!
