### ISSUE TITLE
1.7.4 - geolookup - header check failed at index: 10, '(null)' - 'is_anycast'

### ISSUE THREAD

**Issue by ttrupel** [phaag/nfdump#572]
Hello Peter,

In version 1.7.4, building lookup database fails.

Starting from december 2023, a new field is present in the Blocks CSV files: {GeoIP2,GeoLite2}-{Enterprise,City,Country}-Blocks-IPv4.csv and {GeoIP2,GeoLite2}-{Enterprise,City,Country}-Blocks-IPv6.csv

[https://dev.maxmind.com/geoip/release-notes/2023/#anycast-flag-releasing-soon-for-geoip-web-services-and-databases](https://dev.maxmind.com/geoip/release-notes/2023/#anycast-flag-releasing-soon-for-geoip-web-services-and-databases)

Because the field "is_anycast" is not present in ipFieldNames, CheckFile fails.

Can you confirm that this issue is resolved since you reworked maxmind code [https://github.com/phaag/nfdump/commit/a988a40c44a7ddcd3b5e5383953a4127555b2b41](https://github.com/phaag/nfdump/commit/a988a40c44a7ddcd3b5e5383953a4127555b2b41) ?

Best regards,
Thomas

**Comment by phaag** [comment]
Hey Thomas,
Yes - that has been fixed. Extra fields are reported and ignored.
