### ISSUE TITLE
huawei netstream nat events issue

### ISSUE THREAD

**Issue by skinner-trust** [phaag/nfdump#573]
Hello! first of all let me thank you for such a wonderful product! I've been using it many times to capture and analyze cisco netflow.
Nowadays I'm trying to capture huawei nat events by huawei netstream wich is seemed a clone of netflowV9 and faced to strange issue. nfcapd (Version: 1.7.4-release) simply does not see any flows from my huawei device, and creates empty files, but netstream flow successfully observed by tcpdump. 
    Also nfcapd correctly capture classic neflow_v5 and jflow from my other test devices. Interesting point that nfcapd version 1.6.25 could see and capture netstream nat flows, but nfdump version 1.6.25 was unable to decode it and reported that no flows in files, .
please advise what can be done in this situation

I run nfcapd and tcpdump with a following keys:
nfcapd -w /var/flows -z -p 9001
tcpdump -i eno1 "port 9001" -v
I attached a screenshot of a pcap which I will send on email then
![image_2024-10-30_111705720](https://github.com/user-attachments/assets/5864f367-9f6f-4c5b-b53c-1cb9cfa8b6bb)

**Comment by skinner-trust** [comment]
sorry, seems that was our fault, we have a lot of interfaces in collector vm and in our case the problem was that rp_filter=1. Sending flow to a proper interface solves the issue

**Comment by phaag** [comment]
👍
