### ISSUE TITLE
Have the "xip xport xnet" filters been disabled?

### ISSUE THREAD

**Issue by remontti** [phaag/nfdump#581]
```bash
# nfdump -r nfcapd.202411221727 -O bytes -n 10 xip 100.64.9.26
Line 1: syntax error at 'xip'

# nfdump -r nfcapd.202411221727 -O bytes -n 10 xnet 100.64.0.0/10
Line 1: syntax error at 'xnet'

# nfdump -r nfcapd.202411221727 -O bytes -n 10 xport 443
Line 1: syntax error at 'xport'
```

```bash
man nfdump
```
The options are still present in the manual.

```bash
....
     xip ipaddr 
     src xip ipaddr
     dst xip ipaddr      True, if the field of the translated source or destination IP address matches ipaddr if xip is specified with‐
                         out src or dst both IP addresses may match.

     xport ipaddr
     src xport ipaddr
     dst xport ipaddr    True, if the field of the translated source or destination IP address matches ipaddr if xport is specified 
                         without src or dst both ports may match.

     xnet network/mask
     src xnet network/mask
     dst xnet network/mask
                         True if the translated source or destination IP address matches network if mask mask is applied.  if xnet is
                         specified without src or dst both IP addresses may match.
....
```

**Comment by remontti** [comment]
> did you compile nfdump with `--enable-nsel` so it can read and process ASA/NSEL/NEL event data?

Yes, it was compiled as follows

```
./autogen.sh
./configure --enable-nfprofile --enable-nftrack --enable-maxmind --enable-sflow --enable-nsel
make
make install
ldconfig
```
It even shows in the queries:

![image](https://github.com/user-attachments/assets/87c286a6-b1be-473a-87d5-d68f38b9054d)

**Comment by phaag** [comment]
Thanks for the hint! These filters have been slightly modified in order to combine asa/nel/nsel flows into a more generic name `nat`. Hopefully a bit more understandable.
Instead of `xip` it is now `nat ip` od `src nat ip`, `nat port`, `dat nat port`. These should work likewise for all flows from asa/nsel/nel devices. Unfortunately the manual missed the upgrade, which I will now update.

**Comment by phaag** [comment]
@thezoggy the flag --enable-nsel lost its meaning since the elimination of the internal master record. The only thing, which this flag does theses days, is to define the output format `line` to `nsel`. It has no other meaning and may get removed in future. All nfdump tools can process all flow types without flags.

**Comment by remontti** [comment]
> @thezoggy the flag --enable-nsel lost its meaning since the elimination of the internal master record. The only thing, which this flag does theses days, is to define the output format `line` to `nsel`. It has no other meaning and may get removed in future. All nfdump tools can process all flow types without flags.

Thanks for the information!

**Comment by phaag** [comment]
Tip: In order to see almost all filter elements, have a look into the file `src/test/nftest.c`

**Comment by phaag** [comment]
@thezoggy / As already written - it only sets the output format `line` to `nsel` for compatibility. In a second step the option can be fully removed, as it's recommended anyway to store the output formats in nfdump.conf file for even more flexibility.

**Comment by phaag** [comment]
Seems to works! No negative feedback.

**Comment by chilek** [comment]
@phaag please update man page in filter and format output description area. Thanks in advance!

**Comment by chilek** [comment]
Sorry - it's fixed already!
