### ISSUE TITLE
nfpcapd exits when specifying a pid file

### ISSUE THREAD

**Issue by teeth706** [phaag/nfdump#582]
Running the latest version from git and when the -P flag is specified nfpcapd exits.

```
[root@box nfpcapd]# ./nfpcapd -v -S 2 -w /tmp -i lan -o fat,payload -P /tmp/p 
Add flow source: ident: none, IP: any IP, flowdir: /tmp
Verbose log level: 1
[root@box nfpcapd]# echo $?
1
```
I added some debugging and it's exiting here:

https://github.com/phaag/nfdump/blob/master/src/nfpcapd/nfpcapd.c#L653C1-L656C6
```
    if (pidfile) {
        if (check_pid(pidfile) != 0 || write_pid(pidfile) == 0) pcap_close(packetParam.pcap_dev);
        exit(EXIT_FAILURE);
    }
```
in my env check_pid(pidfle) returns the current PID of the process, so that looks correct.  I'm not sure about the logic here, write_pid just wrote the pid file but this code is basically doing

if (pidfile) {exit(EXIT_FAILURE);}

**Comment by phaag** [comment]
Many thanks for the report. It's fixed in the master repo.
