### ISSUE TITLE
[nfdump 1.7.5] ipv6 records aggregated incorrectly using -Asrcip,inif,outif

### ISSUE THREAD

**Issue by ttrupel** [phaag/nfdump#584]
Hello Peter,

Example :

```
nfdump -r /tmp/bug-nfdump-ipv6 -o "csv:%sa,%in,%out,%pkt,%byt"
srcAddr,input,output,packets,bytes
fe80::aaaa:aaaa:aaaa:aaaa,0,0,4096,655360
fe80::bbbb:bbbb:bbbb:bbbb,0,0,4096,655360
```

```
nfdump -r /tmp/bug-nfdump-ipv6 -Asrcip,inif,outif -o csv
firstSeen,duration,srcAddr,input,output,packets,bytes,bps,bpp,flows
2024-12-09 08:01:45.363,23.191,fe80::aaaa:aaaa:aaaa:aaaa,0,0,8192,1310720,452147,160,2
```

Diving in source code, I figure out that when custom aggregation -Asrcip,inif,outif is used, a wrong hash key is returned by New_HashKey : only the first 64 bits of source ipv6 are used to formed a hash key.
It seems that line 790 (nflowcache.c) should be modified in "keymem += 2 * sizeof(uint64_t);"

Beside this, I was wondering why you chose using hash to store stats on a given aggregation ? Isn't there a risk of real collision using hash ?

PS : I also noticed what I think is a typo on line 1451 (nflowcache.c) : "outBytes = cntFlow->outPackets;"

Best regards,
Thomas

**Comment by phaag** [comment]
Hey Thomas,
Thanks for the bug report. You are right! I fixed the two bug in the master repo.

As of the hash - No - there is no risk. If the aggregated and concatenated elements are less than 2 x uint64_t in size, the hash value is equal the original element, which is unique. If it is more, than there is a memory pointer with all elements, which is compared when searching the hash. So it should be safe all time.
