### ISSUE TITLE
Nfdump - wrong date / timestamp on Cisco Viptela SD-WAN devices

### ISSUE THREAD

**Issue by Cameron-84** [phaag/nfdump#585]
Hello,

I have similar issue as was mentioned here: https://github.com/phaag/nfdump/issues/397 with bad date / timestamp.
There was no problem in the earlier version 1.6.x. My current version is 1.7.5 (latest).
Devices: Cisco Viptela SD-WAN vEdge routers (practically no netflow customisable settings).
![image](https://github.com/user-attachments/assets/159e5431-1ae6-4296-aba8-f5f23e6c54b3)

My troubleshooting output's:
![image](https://github.com/user-attachments/assets/cde8e2ce-a6fb-47c1-87f3-afaef35f2126)

![image](https://github.com/user-attachments/assets/d8d23423-a44d-4dee-8aad-54d6fd074c67)

![image](https://github.com/user-attachments/assets/4c4e884d-019e-400a-89a6-451b8daed942)

![image](https://github.com/user-attachments/assets/c5135ab2-0164-40d3-b61a-6becd8883751)

Device time is synced with NTP servers.
Nfdump compiled with "--enable-nfprofile --enable-nftrack --enable-sflow" (I also tried "--enable-nsel" but has no effect...). 
Thanks for your help.

**Comment by phaag** [comment]
The timestamp you have marked in red is the time, when the ipfix packet has been exported from the CISCO device and does not correspond with the time of the flows start/stop, which are sent by that ipfix packet. You need to check the template, which is associated with that flow. However, it looks like a malformed package for some reason.
If you have difficulties in debugging the package stream feel free to send me a pcap of the traffic, sent to the collector, which contains enough information (template and data records), so I can check for you.

**Comment by Cameron-84** [comment]
Thanks for response.
Here is pcap of the traffic: [cflowd.pcap.zip](https://github.com/user-attachments/files/18186616/cflowd.pcap.zip)

![image](https://github.com/user-attachments/assets/aaac1357-08de-4c69-b103-d04bb9f61ce9)

![image](https://github.com/user-attachments/assets/712ad3b7-90ff-432f-a2c7-d033d8badaba)

![image](https://github.com/user-attachments/assets/2941397d-82a2-4ca9-b93b-9e005bfa6052)

Thank you very much for your help.

**Comment by phaag** [comment]
The pcap unfortunately does not contain any template records. Please make sure, you record a time slot long enough, which contains template records. May I ask you to give it another try?
Thanks

**Comment by phaag** [comment]
If the file is too big or you do not want to share it here, feel free to send it to my email address in the AUTHORS file.

**Comment by Cameron-84** [comment]
I sent you an email. Please check it. Thank you.

**Comment by phaag** [comment]
Added elements 150/151 to netflowv9/ipfix module. Please note, these elements only have seconds resolution. Your flows have only second accuracy.
