### ISSUE TITLE
incorrect Time Window (sfcapd / sflow)

### ISSUE THREAD

**Issue by andrege** [phaag/nfdump#6]
nfdump version: 1.6.13

Debian Gnu Linux version 8.2, i386 (32 bits)

Flow type being collected: sflow

First and last date in "Time window" line are not being reported correctly, for example:
Time window: 1906-11-07 07:19:46 - 2010-03-31 15:12:53

I tracked down this issue and found that there is an overflow happening in variable _t, in sflow.c

Instead of:
_t  = 1000*now.tv_sec + common_record->msec_first;

It should be:
_t  = (unsigned long long) 1000*now.tv_sec + common_record->msec_first;
 
Doing this cast to uint64_t solves the problem.

**Comment by phaag** [comment]
Thx for the report. Fixed.
