### ISSUE TITLE
Pcap analysis with ELK through nfdump

### ISSUE THREAD

**Issue by Kame160** [phaag/nfdump#61]
Hi,
I would like to use the SOF-ELK VM (https://github.com/philhagen/sof-elk/blob/master/VM_README.md) to analyse an archived pcap (acquired from another source). SOF-ELK use nfdump to parse netflow as input to logstash but I am interested into parsing pcap's.

I didn't manage to read any pcap with nfdump (bad magic: 0xC3D4) nor nfpcapd (1KB outputfile without any data in it) - see printscreen: <img width="343" alt="printscreen sof-elk" src="https://cloud.githubusercontent.com/assets/6997425/24006731/e0b81060-0a6c-11e7-821b-39d2fe38b37f.PNG"> and 1KB output file from nfpcapd (renamed .txt to be able to upload it): [nfcapd.201703161358.txt](https://github.com/phaag/nfdump/files/848337/nfcapd.201703161358.txt)
I understand that nfdump handles netflow's and no pcap's but I think that nfpcapd was design to do it. 

I didn't find documentation on nfpcapd utility (well on nfdump en nfcapd) and I do not understand what is the problem ...
If you could recommend me with a another way to parse pcap in order to pass it to logstash instead of nfpcapd, it is also good for me.

Thank you in advance,

Kame

**Comment by philhagen** [comment]
I run the SOF-ELK project.  The `nfpcapd` utility is the way to accomplish this.  Simply run: `nfpcapd -r infile.pcap -S 1 -z -l output_directory/` to generate nfcapd-compatible files that can be injected to SOF-ELK with the newly-merged `nfdump2sof-elk.sh` script, available in the SOF-ELK VM distribution.

From your screenshot, it appears the input file is not actually a pcap or has been corrupted.  The magic value for a pcap file is 0xa1b2c3d4 or 0xd4c3b2a1.  Possibly lost first two bytes of the file?

**Comment by phaag** [comment]
Thanks for commenting on this. I hope importing nfdump data into ELK system get easier, once json output is added.

**Comment by phaag** [comment]
json output has been added. Give it a try and if there are still issues, feel free to reopen the ticket.
