### ISSUE TITLE
Possible memory leak nfpcapd

### ISSUE THREAD

**Issue by nmeyer00** [phaag/nfdump#67]
Hi,

I have found a memory leak in nfpcapd.

My dedicated server has 32GB RAM and the memory just goes up and up constantly.
I have written a small Script to kill nfpcapd, set swapoff, swapon and free all memory.

Version: latest.

Regards,
Nils

**Comment by phaag** [comment]
Can you please send the command line you use to start nfpcapd? It may narrow the search.

Thanks
Peter

**Comment by nmeyer00** [comment]
/usr/bin/nohup /usr/local/bin/nfpcapd  -i eth1 -T all -l /data/internet/ >/data/internet.log 2>&1 &

**Comment by phaag** [comment]
The leak could be localised - finally.  Work is still in progress

**Comment by phaag** [comment]
Found some potential memory leaks. Can you please test.

**Comment by nmeyer00** [comment]
It works fine now :-) Thanks
