### ISSUE TITLE
Feature Request JSON output

### ISSUE THREAD

**Issue by kisienya** [phaag/nfdump#68]
Hi all,

Great tool. Much appreciate.

Is there a possibility for nfdump to produce JSON output after reading pcap files?

This will be good for sending output to for example Elasticsearch.

Cheers

**Comment by phaag** [comment]
It is planed to add json output. Any suggestion how it should look like is welcomed.

**Comment by phaag** [comment]
json output format added. Pls check if it fits your requirements. Otherwise feel free to reopen the ticket.

**Comment by kisienya** [comment]
Many thanks for this update. I will check it out

**Comment by kisienya** [comment]
Does this replace the pipe format or do I have to use flags e.g. --enable-json
