### ISSUE TITLE
bin/nfdump.test.out is not distributed in release tarballs

### ISSUE THREAD

**Issue by jer-gentoo** [phaag/nfdump#71]
This leads to failures in `make check`:

make  check-TESTS
make[3]: Entering directory '/var/tmp/portage/net-analyzer/nfdump-1.6.15/work/nfdump-1.6.15/bin'
make[4]: Entering directory '/var/tmp/portage/net-analyzer/nfdump-1.6.15/work/nfdump-1.6.15/bin'
PASS: nftest
FAIL: test.sh
============================================================================
Testsuite summary for nfdump 1.6.15
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See bin/test-suite.log
Please report to peter@people.ops-trust.net
============================================================================

=======================================
   nfdump 1.6.15: bin/test-suite.log
=======================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test.sh
=============

IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv4 32bit packets 32bit bytes
IPv6 32bit packets 32bit bytes
IPv6 32bit packets 32bit bytes
IPv6 32bit packets 64bit bytes
IPv6 64bit packets 32bit bytes
IPv6 64bit packets 64bit bytes
IPv4 32bit packets 64bit bytes
IPv4 64bit packets 32bit bytes
IPv4 64bit packets 64bit bytes
4 bytes interfaces, 2 bytes AS numbers 24 25
2 bytes interfaces, 4 bytes AS numbers 25 27
4 bytes interfaces, 4 bytes AS numbers 26 29
diff: nfdump.test.out: No such file or directory
FAIL test.sh (exit status: 2)

See also https://bugs.gentoo.org/624336

**Comment by phaag** [comment]
Included in tar release
