### ISSUE TITLE
Nfsen starting problem regarding Nfprofile.pm

### ISSUE THREAD

**Issue by elfinston** [phaag/nfdump#74]
Hello Everyone,

I have issue regarding start of Nfsen.

------------------------------------------------------------------------------------------------------------------
[root@localhost bin]# ./opt/nfsen/bin/nfsen start
Starting nfcapd:(home)[10551]
---->>>>
Starting nfsendPANIC nfsend dies: Insecure dependency in sysopen while running with -T switch at /opt/nfsen/libexec/NfProfile.pm line 836.
Insecure dependency in sysopen while running with -T switch at /opt/nfsen/libexec/NfProfile.pm line 836.
------------------------------------------------------------------------------------------------------------------

My environment is below.
 - Centos 6.9 (on ESXi 5.5)
 - Nfdump 1.6.15
 - Nfsen 1.3.8

Please let me know any idea for this issue?

Regards,

**Comment by phaag** [comment]
Not an nfdump issue.
