### ISSUE TITLE
Timestamp always 1.1.1970 as Cisco NX-OS 8.1.1 uses 8 byte for timestamps

### ISSUE THREAD

**Issue by volhar00** [phaag/nfdump#80]
Netflow from NX-OS 8.1.1 on Nexus 7700 produces timestamp 1970-01-01 01:00:00 for every flow. 
A tcpdump shows that the template describes 8 byte for FIRST_SWITCHED (22) and LAST_SWITCHED (21).
nfdump 1.6.13 has fix 4 bytes in netflow_v9.c
{ NF9_LAST_SWITCHED,             "time sec end",        _4bytes,  _4bytes, move32, zero32, COMMON_BLOCK },
So this is the cause for the miscalculation.
Nfdump needs an enhancement for this problem.
Thanks 
Harald (Unibas)

**Comment by phaag** [comment]
Hi Harald,
Thx for the report. This is now fixed. Nexus still uses 4 bytes for timestamps, but exports them in 8 bytes - hence add 4 zero byes. nfdump can now cope with 8 byte Nexus timestamps
Cheers
Peter

**Comment by volhar00** [comment]
Hi Peter
works wonderful!
Thank you for this incredible speed to fix it.
Kind regards
Harald
