### ISSUE TITLE
Strange durations/bps with sflow

### ISSUE THREAD

**Issue by KlaasT** [phaag/nfdump#82]
Hi,

I've got a very weird issue. When viewing sflow entries using nfdump I'm getting very low durations (below 1 second). This causes the calculation of the used bandwidth to go crazy.

This is viewing 40 minutes of sflow data:

Date first seen         Date last seen           Duration      bps    Bytes Flows
2017-11-16 16:06:08.104 2017-11-16 16:06:08.105     0.001   49.7 G    6.2 M     2
2017-11-16 16:00:10.742 2017-11-16 16:00:10.777     0.035    2.1 G    9.4 M     3

The customer generating the flow has a 1Gbit/s interface and the router exporting the flow has a 10Gbit/s link.

On the router, which is exporting the sflow data, I have a sampling rate of 2048 and a polling interval of 10. 

I don't know if this could be a bug in the sflowd or if my router is just acting strangely.

**Comment by phaag** [comment]
It is difficult o tell. the very low durations result from the difference of just two packets, with just 1ms apart. Do you have more information on that? Does sfcapd say anything in the log file which looks strange?

**Comment by gabrielmocan** [comment]
One can always use total values (in bytes*8 and packets) and a fixed active timeout value in order to properly calculate "per second" stats without having to rely on flow duration fields sent by arbitrary exporters.

**Comment by phaag** [comment]
Any feedback on that?
