### ISSUE TITLE
Flood in nfcapd logs from VyOS router

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#84]
nfcapd logs are being flooded by "Update existing sampler id" messages when receiving netflow packets from VyOS routers.

Excerpt from logs:

"Ident: 'Ident: 'VYOS.PB' Flows: 45507, Packets: 7954800, Bytes: 12105072400, Sequence Errors: 4, Bad Packets: 0'
Total ignored packets: 0
Update existing sampler id: 1, mode: 2, interval: 100

Update existing sampler id: 1, mode: 2, interval: 100

Update existing sampler id: 1, mode: 2, interval: 100"

There is no related config inside router OS to increase sampler id update time or such.

I've attached a nfcapd file for further analysis, if needed.

[nfcapd.zip](https://github.com/phaag/nfdump/files/1525205/nfcapd.zip)

**Comment by phaag** [comment]
Fixed in master tree.

**Comment by gabrielmocan** [comment]
I've tested this fix against the same router and a couple others similar to them. It's working properly. Thanks!
