### ISSUE TITLE
Sampling rate not being used -- Huawei NetStream

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/nfdump#90]
How do I know if NetFlow packets exported from Huawei NE-20 are coming with proper sampling rate value? I have some Huawei NE-20 with 1:100, 1:1000 sampling rate but all of them dump like this:

Flow Record:
  Flags        =              0x06 FLOW, **Unsampled**
  export sysid =                 1
  size         =                68
  first        =        1513573373 [2017-12-18 02:02:53]
  last         =        1513573373 [2017-12-18 02:02:53]
  msec_first   =                 0
  msec_last    =                 0
  src addr     =   143.255.131.167
  dst addr     =    187.33.229.224
  src port     =              6363
  dst port     =               443
  fwd status   =                 0
  tcp flags    =              0x04 ...R..
  proto        =                 6 TCP
  (src)tos     =               108
  (in)packets  =                 1
  (in)bytes    =                60
  input        =                75
  output       =                74
  src as       =                 0
  dst as       =                 0

I've attached a nfcapd file for further analysis, if needed.
[nfcapd.zip](https://github.com/phaag/nfdump/files/1566704/nfcapd.zip)

**Comment by phaag** [comment]
I would need a pcap of network data, which your Huawei sends to nfcapd. If you can provide me that, I can have a look.

**Comment by gabrielmocan** [comment]
I've attached a nfcapd file in the original post. How can I get a pcap?

**Comment by phaag** [comment]
You need to tcpdump the packets sent to from the exporter to the nfcpad collector.

**Comment by gabrielmocan** [comment]
There you go!

[huawei_ne-20.zip](https://github.com/phaag/nfdump/files/1583872/huawei_ne-20.zip)

**Comment by phaag** [comment]
Your devices do not export any sampling related information in any of the v9 templates. If you have more information, if and how it gets exported, please let me know.

**Comment by gabrielmocan** [comment]
Ok, thanks for checking this out. I'm considering sending an email to Huawei pointing out this issue. If I find anything I'll let you know.

**Comment by phaag** [comment]
Ok - meanwhile I close the ticket

**Comment by gabrielmocan** [comment]
I've made contact with Huawei and they told me about a certain configuration -- "ip netstream export template option sampler" that is used to export sampling options. I've tried it and the router seems to be exporting sampling ratio properly now, as one can see in packets 1770 and 1771 (Hex Value 64 which is 100 in decimal, and that's the ratio configured for this router, 1:100) from the pcap file attached below.

[huawei-3rdSample.zip](https://github.com/phaag/nfdump/files/1591888/huawei-3rdSample.zip)

**Comment by phaag** [comment]
Huawei sampling works a different to CSICO sampling. I would need more documentation on that. So I can implement that.

**Comment by phaag** [comment]
Ok - here some questions:
netstream announces sampling interval per interface - ingress/egress - and hash value.
Per interface - ingress/egress is fine, but I can not understand the hash value. 
In you packet stream I see announcements for interval 100 for
```
Interface 6, ingress, hash 4
Interface 6, egress,  hash 4
Interface 6, ingress, hash 50
Interface 6, egress,  hash 326

interface 7, ingress, hash 4
interface 7, egress,  hash 2
interface 7, ingress, hash 4
interface 7, egress,  hash 2
```
The hash value in all record data is 0. 
I could not find a decent paper, which explains that.

I can implement sampling based on interface ingress/egress and skip the hash, but what if the interval of announcements with different hash differ?

**Comment by gabrielmocan** [comment]
Well, sampling configurations can be done in global level (which is the case for all samples I've submitted), and per-interface also. Maybe if per-interface intervals is enabled, hash pattern may change. I'm not really good at the inside mechanics of NetFlow/IPFIX so I don't know exactly how I can help on that.

**Comment by phaag** [comment]
If you could ask Huawei for more information on that issue, or documents describing the behaviour, this would be good.

**Comment by phaag** [comment]
Any progress here, otherwise I close meanwhile the issue.

**Comment by phaag** [comment]
No answer - closed
