### ISSUE TITLE
nfdump -h missing json format 

### ISSUE THREAD

**Issue by fdulau** [phaag/nfdump#91]
When using the internal help of nfdump, we miss the JSON format documentation

-o <mode>       Use <mode> to print out netflow records:
                 raw      Raw record dump.
                 line     Standard output line format.
                 long     Standard output line format with additional fields.
                 extended Even more information.
                 csv      ',' separated, machine parseable output format.
                 pipe     '|' separated legacy machine parseable output format.
                        mode may be extended by '6' for full IPv6 listing. e.g.long6, extended6.

The JSON export is a great idea. Thanks for it.

**Comment by phaag** [comment]
Thanks! - Fixed.
