### ISSUE TITLE
JunOS low bps/pps

### ISSUE THREAD

**Issue by TheGreatDoc** [phaag/nfdump#93]
Hello.

Im using nfdump 1.6.13 and I'm feeding nfcapd with a Juniper MX104 and a Cisco ASR1002X.

In the flows of the MX104, the bps/pps are really low, sometimes less than 1Mb/s where, in same condition, the ASR is giving more than 400Mb/s for almost the same total bytes and packets.

For example, for 1 hour samples:
MX104
![image](https://user-images.githubusercontent.com/32565115/34934901-5dfff510-f9dc-11e7-95c0-27292eb4fc93.png)

ASR1k2x
![image](https://user-images.githubusercontent.com/32565115/34934933-76acdd26-f9dc-11e7-86cf-7f6aedc1bf78.png)

I cant find any info on how to fix this from the router side. Is there any way to change bps/pps calculation in nfdump/nfsen to make it from total bytes / timeslot? 

Thanks and AWESOME tool @phaag

**Comment by phaag** [comment]
Do you have some sampling on the Juniper MX104? If so, is it also exported? Maybe nfcapd does not recognised sampling correctly. 
You can send me offlist a pcap with data sent to the collector. This helps me best to debug.
Many thanks

**Comment by TheGreatDoc** [comment]
Where to send you the pcap?

**Comment by gabrielmocan** [comment]
@TheGreatDoc have you tried compiling from master branch? I think this issue was solved in #47

**Comment by TheGreatDoc** [comment]
@gabrielmocan Im using 1 to 1, no sampling and using v9 instead of ipfix.

**Comment by gabrielmocan** [comment]
@TheGreatDoc Oh, I see. You can try IPFIX to see if you have better results. I have a few MX-104's being monitored using different sampling rations (1:100, 1:1000) and they all have excellent precision comparing against SNMP measurements.

**Comment by TheGreatDoc** [comment]
@gabrielmocan Oh, no no, the problem is not the overall traffic. Its funny becouse the overall traffic seems to be good, the problem is when I try to filter for a Top Source AS, its there when the low bps/pps happens (as you can see in my first post).

What happens when you do a Top Source AS? Is shows bps/pps "near" correct?

Can you share your mx104 conf?

Thanks!

**Comment by gabrielmocan** [comment]
@TheGreatDoc Well, by looking at your first post I'll say that the problem that you're having is related to flow duration. You see, the total value is not too far, as you've mentioned, but the "per second" stats are calculated using flow duration as a parameter.

Now look at flows duration for your Cisco device. They're around ~5600 secs. Now looking at your Juniper box we see that flows duration is way bigger than it should, like 365612 secs, and that's why you are having such low bps/pps stats in that particular router. I would try to set active flow timeout to 1 minute for the Juniper box and 5 minutes for Cisco box and see if you have better results. Or you can simple match active flow timeout with your sampling period (or twice, if you want to respect Shannon's theorem -- meaning that if you are collecting for 10 minutes, you should set active timeouts to 5 minutes). As a last tip, I suggest you to not use active timeouts lower than 1 minute, as hinted in nfdump code.

**Comment by TheGreatDoc** [comment]
@gabrielmocan This is my current configuration in the MX104 and a flow captured with tcpdump from each router

https://pastebin.com/2U1c8SBx

Thats makes no sense for me...

Is it possible for you to share your mx104 netflow conf?

Thanks!

**Comment by gabrielmocan** [comment]
@TheGreatDoc there you go https://pastebin.com/cqFGa5QH

If that's not enough, I guess it's better to send pcap data to @phaag so he come up with something.

Good luck!

**Comment by TheGreatDoc** [comment]
@gabrielmocan Thank you very much!

i'll try your config with ipfix, but forgot to ask you something. What JunOS version are you running?

Also, you told me to not set inactive timeout less than a minute and you set it up in 15 seconds. Thats correct?

Again, thank you very much!

**Comment by gabrielmocan** [comment]
@TheGreatDoc this particular box is running JUNOS 15.1R6-S2.1 built 2017-07-20.

The 1 minute thing is for **active** timeouts, not **inactive**.

Keep us informed about results, please!

**Comment by TheGreatDoc** [comment]
@gabrielmocan How you did configured the run-length?

I got:

sampling inline configuration error
    run-length is not supported for inline JFlow

**Comment by TheGreatDoc** [comment]
@gabrielmocan @phaag 
I've git clone the last release and I got this:

Flow Record:
  Flags        =              0x06 FLOW, **Unsampled**
  label        =            <none>
  export sysid =                 3
  size         =                72
  first        =        1519905645 [2018-03-01 13:00:45]
  last         =        1519905645 [2018-03-01 13:00:45]
  msec_first   =               312
  msec_last    =               312
  src addr     =     **
  dst addr     =    **
  src port     =             42557
  dst port     =                23
  fwd status   =                 0
  tcp flags    =              0x10 .A....
  proto        =                 6 TCP
  (src)tos     =                 0
  (in)packets  =                 1
  (in)bytes    =                52
  input        =               533
  output       =               531
  src as       =             **
  dst as       =              8708

nfdump: Version: 1.6.16

**Comment by gabrielmocan** [comment]
@TheGreatDoc Well I don't know why your router didn't accept the run length line but this part isn't crucial for proper results.

Did you download 1.6.16 release or did you clone 'n compile from master branch? I was having the same issue using release 1.6.16 but it was fixed after latter #47 resolution, which is only available in master branch.

**Comment by TheGreatDoc** [comment]
@gabrielmocan I did clone https://github.com/phaag/nfdump  'n compiled. 

Should I download other? How?

**Comment by gabrielmocan** [comment]
@TheGreatDoc No, your procedure is correct. Well, I guess I ran out of options. As a last advice I would suggest sending pcap data to @phaag so he can debug what's going on.

**Comment by TheGreatDoc** [comment]
@gabrielmocan quick question. Whats your
set chassis afeb slot 0 inline-services flow-table-size ipv4-flow-table-size ??

I'm seeing a big difference between your pcap and mine. While you have all flows with 440 bytes, Mines are 105bytes and after a while, I get Partial IPFIX Flow (105/4294967295 bytes)

**Comment by TheGreatDoc** [comment]
FYI, Seems like git clone url is not enough. I've checked ipfix.c to see the changes for the sampling and there isnt. So I did a git clone url --branch master and it downloaded the correct files.

**Comment by gabrielmocan** [comment]
@TheGreatDoc I did not set this option to be honest, so most likely it's using default values, which I also don't know how much it is.

About the git stuff, that's weird because I always do 'git clone https://github.com/phaag/nfdump' to get master branch with no issue so far.

But the most important thing: now you're getting correct readings?

**Comment by TheGreatDoc** [comment]
@gabrielmocan Unfortunately, no I'm not getting correct readings. a nfdump -o raw keep saying unsampled.

I'll try to do a couple of tests this weekend and if nothing works, send a pcap to @phaag 

The funny thing is that total bytes/packets transmitted seems to be correct but the bps/pps values are totally wrong.

Thanks for all your help, will keep this thread update if I find something or if Peter found something.

**Comment by phaag** [comment]
Checking my mails I did not find a pcap. Did I miss it or didn't you send it?
If it is still an issue, you will find my email in the AUTHORS file in the master branch.
Feel free to send me pcaps :)

**Comment by TheGreatDoc** [comment]
@phaag Sorry, didnt sent it. I was doing lot of tests with no luck.
Like how many time of pcap file? 5-10min?

**Comment by phaag** [comment]
I just need a full capture of all template records and a few data records. 
It depends on the template refresh rate you set in the config on the exporter. Worst case is a sample taken for the length of the template refresh rate. Usually 5-10 min should be ok.

**Comment by TheGreatDoc** [comment]
Pcap sent!

**Comment by phaag** [comment]
Thanks for the pcap. Technically everything looks good. It's an IPFIX stream with explicit sampling set to 1.
Although sampling is announced, nfdump still says, it's unsampled as sampling rate is 1 which is identical to unsampled. You can check sampling with ./nfdump -E <file> to see, if the exporter announces sampling.
As of pps and bps: These values are calculated over the lifetime of a flow. The lifetime is the duration 
( flow end - flow start ), which are reported in the data records. The router seems not to be really busy, few flows, light traffic.
Wrong bps and pps can result from two sides: wrong counter data or wrong duration. I  can not assess if the bytes transferred per flow are correct or not. Maybe you can setup somewhere a lab environment and create flows of known content (bytes). 
The duration is another topic: Flow records have ms resolution: Very short flows < 1ms are reported with a duration of 0. This also results in bps and pps as 0. TCP flows should have exact time stamps (SYN, FIN) UDP may depend on active timeouts, however first seen, last seen should also result in correct time stamps. But if somehow these timestamps are wrong, you also get wrong bps, pps.

Unfortunately I can not really help as on protocol level it looks good, but it seems a matter of the content of the data.

**Comment by TheGreatDoc** [comment]
Total bytes and overall traffic are correct. I have cacti and librenms monitoring that router and values are the same.

The only that fails is the bps/pps by src/dst

I also have a ticket with juniper so can you tell me what to tell them??

Other posibility is to tell nfdump to ignore flow durations and use the file or files duration. Is that possible??

**Comment by phaag** [comment]
Well bps and pps are flow parameters are calculated per flow individually. So I can not ignore the duration. 
If pps/bps are to low, and the counters are correct, then the flow start/end time stamps are incorrect somehow.
I keep the ticket open for some time. If you have more information, let me know.

**Comment by TheGreatDoc** [comment]
How can be overall bps/pps correct (the graph one) but incorrect for "individuals"? How is overall calculated?

**Comment by phaag** [comment]
Overall simply aggregate all data over the reported timeslot. It is basically an extrem smoothing over all data. Inaccuracies get flattened, individual flow start/end do not matter any more. As you reported the counter values are correct, all accumulated flow bytes and packets result in a mean bps/pps value.
These facts lead to the conclusion, that individual flow stat/end timestamps are not accurate enough.
Maybe JunOS add somewhere some latency?

**Comment by avisom** [comment]
Hi guys!

Maybe i can add new information to this discussion.

We noted that after switching from RE-based sampling (at control plane) to inline-based (at hardware) on our routers something changed at pps and bps calculation, then we opened a ticket at JTAC and as a result got this information:

> Sampling Behavior on MS-DPC
> 
> The start time should not change for the same active flow in every export record. The behavior in MS-DPC is correct, as the start time should not change for the same flow. With that, you will know if the record is from a new flow or a long existing active flow.
> 
> Sampling Behavior on RE 
> 
> The behavior on RE is different. As the flow record is not kept within the RE, the entries will be removed, when the stats are exported. So, the new statistics that are coming in will be treated as a new flow and that is why the start time keeps changing. It is renewed for every export record and it does not hold the flow record in the RE.
> https://kb.juniper.net/InfoCenter/index?page=content&id=KB25893

As a practical result of this behaviour we have little number of tcp flows with long duration, and when we try to calculate aggregated data per second units by nfdump - we get incorrect numbers because of incorrect time window.
Of course we have both active and inactive timeout set to 60 seconds, but it doesn't help and i think can't in this situation.

I tried to imagine how nfdump or nfcapd can handle this and got failed...

@phaag Maybe you have some ideas about it?

**Comment by phaag** [comment]
If you aggregate in both cases, you should get decent values for pps/bps - averaged over the total duration. If the start time is always the same or if it changes does not make any difference for the aggregation, given that you have no dead time (holes) between two exported records. If a flow ends 
(F flag), it should get correct values. This should be true for TCP, however, it gets more difficult for UDP, as this protocol potentially has more short living connections.

**Comment by avisom** [comment]
Thank you for reply.

I telling about the case when actual aggregation period is much smaller then the life time of the at least one tcp flow in it, for example period about several minutes and tcp flow life time about thirty minutes. And then aggregated bps/pps should been calculated for time window of five minutes (or one minute), but actually we get time window about twenty or thirty minutes calculated because of start time of flow not being reset when it exporting from router.

**Comment by avisom** [comment]
@TheGreatDoc it looks like that you have this https://prsearch.juniper.net/InfoCenter/index?page=prcontent&id=PR1294296 bug or similar. 
> When inline-jflow is configured, the last timestamp of some flow records might be incorrectly getting changed to zero. Such flows are not able to get aged out inactively and remain stuck in the flow table. Over a period of time, such flows increase and the flow table overruns. This prevents flow table from learning new flows as there is no space left in the flow table. So it might be observed some flows are not exported to collector.

As a result of it you can have flow with unpredictable timestamps/duration.

**Comment by phaag** [comment]
I close this ticket. If anything new shows up, please reopen.
