### ISSUE TITLE
nfreplay -h missing netflow version 

### ISSUE THREAD

**Issue by MariaRigaki** [phaag/nfdump#95]
The displayed text does not mention the -v option while it seems like a supported option in the code.

[xxxx@yyyyyy]$ nfreplay -h
usage nfreplay [options] ["filter"]
-h		this text you see right here
-V		Print version and exit.
-H <Host/ip>	Target IP address default: 127.0.0.1
-j <mcast>	Send packets to multicast group
-4		Force IPv4 protocol.
-6		Force IPv6 protocol.
-L <log>	Log to syslog facility <log>
-p <port>	Target port default 9995
-d <usec>	Delay in usec between packets. default 10
-c <cnt>	Packet count. default send all packets
-b <bsize>	Send buffer size.
-r <input>	read from file. default: stdin
-f <filter>	filter syntaxfile
-t <time>	time window for sending packets
		yyyy/MM/dd.hh:mm:ss[-yyyy/MM/dd.hh:mm:ss]

That's an easy one, let me know if you would prefer a pull request :)

**Comment by phaag** [comment]
Thanks! - It's fixed.
