### ISSUE TITLE
nfreplay does not forward NSEL/NEL extensions

### ISSUE THREAD

**Issue by MariaRigaki** [phaag/nfdump#96]
nfreplay version: 1.6.16 (latest version pulled from github repo).

We have a box A that receives flows (via nfcapd) that contain NSEL/NEL extensions and we want to forward these flows with nfreplay to another box B. Both of them have nfdump tools compiled with --enable-nsel and --enable-nel options. Box A receives and interprets the extensions properly but box B does not seem to receive the `X-Dst  IP Addr:Port` and `X-Src IP Addr:Port` (they are zero-ed out). Not sure if there is something that we should be doing differently, but here are the commands and outputs:

**nfreplay command**
`nfreplay -v 9 -H X.X.X.X -p 8888 -r nfcapd.201802061048`

**Box A nfdump:**
`Date first seen          Event  XEvent Proto      Src IP Addr:Port          Dst IP Addr:Port     X-Src IP Addr:Port        X-Dst IP Addr:Port   In Byte Out Byte`
`2018-02-06 09:35:46.860 INVALID  Ignore TCP     a.b.c.d:443   ->    x.y.z.w:52166   a.b.c.d:443   ->  192.168.202.107:52166     3439        0`

**Box B nfdump:**
`Date first seen          Event  XEvent Proto      Src IP Addr:Port          Dst IP Addr:Port     X-Src IP Addr:Port        X-Dst IP Addr:Port   In Byte Out Byte`
`2018-02-06 09:35:46.860 INVALID  Ignore TCP     a.b.c.d:443   ->    x.y.z.w:52166          0.0.0.0:0     ->          0.0.0.0:0         3439        0`

**tshark output in box B:**

Flow 18
            [Duration: 6.010000000 seconds (switched)]
                StartTime: 86494.860000000 seconds
                EndTime: 86500.870000000 seconds
            Forwarding Status
                00.. .... = ForwardingStatus: Unknown (0)
                ..00 0000 = ForwardingStatusUnknown: Unknown (0)
            TCP Flags: 0x12, ACK, SYN
                00.. .... = Reserved: 0x0
                ..0. .... = URG: Not used
                ...1 .... = ACK: Used
                .... 0... = PSH: Not used
                .... .0.. = RST: Not used
                .... ..1. = SYN: Used
                .... ...0 = FIN: Not used
            Protocol: TCP (6)
            IP ToS: 0x00
            SrcPort: 443 (443)
            DstPort: 52166 (52166)
            ICMP Type: 0x0000
            SrcAddr: a.b.c.d
            DstAddr: x.y.z.w
            Packets: 8
            Octets: 3439
            InputInt: 11
            OutputInt: 25
            Post IP ToS: 0x00
            Direction: Ingress (0)
            SrcMask: 0
            DstMask: 0
            NextHop: 192.168.250.253
            Destination Mac Address: Routerbo_59:80:77 (4c:5e:0c:59:80:77)
            Post Source Mac Address: Routerbo_59:80:77 (4c:5e:0c:59:80:77)
            EngineType: RP (0)
            EngineId: 0

**Comment by phaag** [comment]
That's correct. Currently no NSEL/NEL extension are resent. 
It's unclear to me, if nfreplay is needed any longer. People are requested to comment here :)

**Comment by MariaRigaki** [comment]
Ok, good to know :) We do use it, but if there is another way to proxy the flows between machines without having to sent the files I would also like to hear about it.

**Comment by phaag** [comment]
Well - you can directly use -R on nfcapd to add forwarding to another destination.
If this is not flexible enough you may try samplicator
