### ISSUE TITLE
nfprofile -i                                      Segmentation fault

### ISSUE THREAD

**Issue by paolss** [phaag/nfdump#99]
compiled latest version from GIT and try running nfprofile with -i  - always get segemtation fault.
no matter if i will put parameters like:
nfprofile -r /opt/nfcapd.current.25270 -p /opt/ -i "http://127.0.0.1:8086/write?db=sfcapd&u=ad&p=123"

or
nfprofile -r /opt/nfcapd.current.25270 -p /opt/ -i http://127.0.0.1:8086/write?db=sfcapd&u=ad&p=123

nfprofile -V
nfprofile: Version: 1.6.16

**Comment by phaag** [comment]
Thanks for reporting. I fixed the argument processing in nfprofile.
Please not, that your command line does not work with the nfcapd.current file. This is the file nfcapd currently collects new data and can not be accessed by other processes.
